// solid/src/features/posts/feed-side-panel/feed-side-panel.tsx
import type { JSX } from "@solidjs/web";
import { Show, createEffect, createSignal, onCleanup } from "solid-js";

import { IconButton, IconX, Sheet, SheetContent, Type, cn } from "../../../design-system";
import { FEED_DOCK_QUERY } from "./feed-side-panel-model";

export function FeedPanelLayout(props: {
  children: JSX.Element;
  class?: string;
  panel?: JSX.Element;
}) {
  return (
    <div class={cn("grid min-h-0 w-full grid-cols-1", props.panel && "xl:grid-cols-[minmax(0,1fr)_26rem]", props.class)} data-feed-panel-layout>
      <div class="min-h-0 min-w-0">{props.children}</div>
      {props.panel}
    </div>
  );
}

export interface FeedSidePanelProps {
  children: JSX.Element;
  closeLabel: string;
  description?: string;
  onOpenChange: (open: boolean) => void;
  open: boolean;
  title: string;
  initialFocusRef?: HTMLElement;
  returnFocusRef?: HTMLElement;
}

/** Responsive comments/booking surface: dock on wide screens and bottom sheet on mobile. */
export function FeedSidePanel(props: FeedSidePanelProps) {
  const close = () => {
    props.onOpenChange(false);
    props.returnFocusRef?.focus();
  };
  const docked = createIsFeedDocked();

  createEffect(
    () => props.open,
    (open) => {
      if (open) props.initialFocusRef?.focus();
    },
  );

  const handleOpenChange = (open: boolean) => {
    props.onOpenChange(open);
    if (!open) props.returnFocusRef?.focus();
  };

  return (
    <Show when={props.open}>
      <Show
        when={docked()}
        fallback={
          <Sheet onOpenChange={handleOpenChange} open>
            <SheetContent aria-label={props.title} class="flex h-[88dvh] w-full flex-col overflow-hidden px-0 pb-[env(safe-area-inset-bottom)]" hideCloseButton side="bottom">
              <PanelHeader close={() => handleOpenChange(false)} closeLabel={props.closeLabel} description={props.description} title={props.title} />
              <div class="min-h-0 flex-1 overflow-hidden">{props.children}</div>
            </SheetContent>
          </Sheet>
        }
      >
        <aside
          aria-label={props.title}
          class="flex min-h-0 border-s border-border-soft bg-card xl:flex xl:flex-col"
          data-feed-side-panel
          onKeyDown={(event) => {
            if (event.key === "Escape") {
              event.stopPropagation();
              handleOpenChange(false);
            }
          }}
        >
          <PanelHeader close={close} closeLabel={props.closeLabel} description={props.description} title={props.title} />
          <div class="min-h-0 flex-1 overflow-hidden">{props.children}</div>
        </aside>
      </Show>
    </Show>
  );
}

function createIsFeedDocked() {
  const [docked, setDocked] = createSignal(false, { ownedWrite: true });

  createEffect(
    () => FEED_DOCK_QUERY,
    (query) => {
      if (typeof window === "undefined" || typeof window.matchMedia !== "function") return;
      const media = window.matchMedia(query);
      const update = () => setDocked(media.matches);
      update();
      media.addEventListener("change", update);
      onCleanup(() => media.removeEventListener("change", update));
    },
  );

  return docked;
}

function PanelHeader(props: { close: () => void; closeLabel: string; description?: string; title: string }) {
  return (
    <header class="flex min-h-16 shrink-0 items-center justify-between gap-3 border-b border-border-soft px-5">
      <div class="min-w-0">
        <Type as="h2" variant="h3">{props.title}</Type>
        <Show when={props.description}>
          <Type class="line-clamp-1" variant="caption">{props.description}</Type>
        </Show>
      </div>
      <IconButton aria-label={props.closeLabel} class="size-10" onClick={props.close} type="button" variant="ghost"><IconX class="size-5" /></IconButton>
    </header>
  );
}

// src/components/compositions/posts/feed-side-panel/feed-side-panel.tsx
"use client";

import * as React from "react";
import { X } from "@phosphor-icons/react";

import { IconButton } from "@/components/primitives/icon-button";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/primitives/sheet";
import { Type } from "@/components/primitives/type";
import { cn } from "@/lib/utils";

const FEED_DOCK_QUERY = "(min-width: 1024px)";

function useFeedDockDesktop(): boolean {
  return React.useSyncExternalStore(
    (callback) => {
      const media = window.matchMedia(FEED_DOCK_QUERY);
      media.addEventListener("change", callback);
      return () => media.removeEventListener("change", callback);
    },
    () => window.matchMedia(FEED_DOCK_QUERY).matches,
    () => false,
  );
}

export type FeedPanelState =
  | { kind: "none" }
  | { kind: "comments"; itemId: string; postId: string }
  | { kind: "booking"; basePriceCents: number; hostUserId: string; itemId: string };

export function feedPanelBlocksPlayback(panel: FeedPanelState, itemId: string): boolean {
  return panel.kind === "booking" && panel.itemId === itemId;
}

export function FeedPanelLayout({
  children,
  className,
  panel,
}: {
  children: React.ReactNode;
  className?: string;
  panel?: React.ReactNode;
}) {
  return (
    <div className={cn(
      "grid min-h-0 w-full grid-cols-1",
      panel && "lg:grid-cols-[minmax(0,1fr)_26rem]",
      className,
    )}>
      <div className="min-h-0 min-w-0">{children}</div>
      {panel}
    </div>
  );
}

export function FeedSidePanel({
  children,
  closeLabel,
  description,
  initialFocusRef,
  onOpenChange,
  open,
  returnFocusRef,
  title,
}: {
  children: React.ReactNode;
  closeLabel: string;
  description?: string;
  initialFocusRef?: React.RefObject<HTMLElement | null>;
  onOpenChange: (open: boolean) => void;
  open: boolean;
  returnFocusRef?: React.RefObject<HTMLElement | null>;
  title: string;
}) {
  const desktop = useFeedDockDesktop();
  const handleOpenChange = React.useCallback((nextOpen: boolean) => {
    onOpenChange(nextOpen);
    if (!nextOpen) returnFocusRef?.current?.focus();
  }, [onOpenChange, returnFocusRef]);

  React.useLayoutEffect(() => {
    if (open) initialFocusRef?.current?.focus();
  }, [initialFocusRef, open]);

  if (!open) return null;

  if (!desktop) {
    return (
      <Sheet onOpenChange={handleOpenChange} open>
        <SheetContent className="flex h-[88dvh] w-full flex-col overflow-hidden px-0 pb-[env(safe-area-inset-bottom)]" side="bottom">
          <SheetHeader className="shrink-0 px-5 text-start">
            <SheetTitle>{title}</SheetTitle>
            {description ? <SheetDescription>{description}</SheetDescription> : null}
          </SheetHeader>
          <div className="min-h-0 flex-1 overflow-hidden">{children}</div>
        </SheetContent>
      </Sheet>
    );
  }

  return (
    <aside
      aria-label={title}
      className="hidden min-h-0 border-s border-border-soft bg-card lg:flex lg:flex-col"
      data-feed-side-panel
      onKeyDown={(event) => {
        if (event.key === "Escape") {
          event.stopPropagation();
          handleOpenChange(false);
        }
      }}
    >
      <header className="flex min-h-16 shrink-0 items-center justify-between gap-3 border-b border-border-soft px-5">
        <div className="min-w-0">
          <Type as="h2" variant="h3">{title}</Type>
          {description ? <Type className="line-clamp-1" variant="caption">{description}</Type> : null}
        </div>
        <IconButton aria-label={closeLabel} onClick={() => handleOpenChange(false)} size="sm" variant="ghost">
          <X aria-hidden className="size-5" weight="bold" />
        </IconButton>
      </header>
      <div className="min-h-0 flex-1 overflow-hidden">{children}</div>
    </aside>
  );
}
