// src/components/primitives/formatted-text.tsx
import * as React from "react";

import { cn } from "@/lib/utils";

const formattedTextWrap = "min-w-0 max-w-full break-words [overflow-wrap:anywhere] [word-break:break-word]" as const;
const formattedTextLinkWrap = "break-all [word-break:break-all]" as const;

function renderInline(text: string, keyPrefix: string): React.ReactNode[] {
  const inlinePattern =
    /(\[([^\]]+)\]\((https?:\/\/[^)\s]+)\)|\*\*\*([\s\S]+?)\*\*\*|\*\*([\s\S]+?)\*\*|\*([\s\S]+?)\*|~~([\s\S]+?)~~)/g;
  const nodes: React.ReactNode[] = [];
  let lastIndex = 0;
  let match: RegExpExecArray | null = inlinePattern.exec(text);

  while (match) {
    if (match.index > lastIndex) {
      nodes.push(text.slice(lastIndex, match.index));
    }

    const [
      fullMatch,
      ,
      linkLabel,
      linkHref,
      boldItalicText,
      boldText,
      italicText,
      strikeText,
    ] = match;
    const key = `${keyPrefix}-${match.index}`;

    if (linkLabel && linkHref) {
      nodes.push(
        <a
          className={cn(formattedTextWrap, formattedTextLinkWrap, "text-primary underline underline-offset-4")}
          href={linkHref}
          key={key}
          rel="noreferrer"
          target="_blank"
        >
          {linkLabel}
        </a>,
      );
    } else if (boldItalicText) {
      nodes.push(
        <strong key={key}>
          <em>{renderInline(boldItalicText, `${key}-strong-em`)}</em>
        </strong>,
      );
    } else if (boldText) {
      nodes.push(<strong key={key}>{renderInline(boldText, `${key}-strong`)}</strong>);
    } else if (italicText) {
      nodes.push(<em key={key}>{renderInline(italicText, `${key}-em`)}</em>);
    } else if (strikeText) {
      nodes.push(<s key={key}>{renderInline(strikeText, `${key}-strike`)}</s>);
    } else {
      nodes.push(fullMatch);
    }

    lastIndex = match.index + fullMatch.length;
    match = inlinePattern.exec(text);
  }

  if (lastIndex < text.length) {
    nodes.push(text.slice(lastIndex));
  }

  return nodes;
}

function FormattedInline({ text, keyPrefix }: { text: string; keyPrefix: string }) {
  return <>{renderInline(text, keyPrefix)}</>;
}

function FormattedParagraph({ lines, textKey }: { lines: string[]; textKey: string }) {
  const text = lines.join(" ");
  const isBareUrl = /^https?:\/\/\S+$/u.test(text.trim());

  return (
    <p className={cn(formattedTextWrap, isBareUrl && formattedTextLinkWrap, "leading-snug text-inherit")}>
      <FormattedInline keyPrefix={textKey} text={text} />
    </p>
  );
}

function FormattedHeading({
  displayDepth,
  text,
  textKey,
}: {
  displayDepth: 2 | 3 | 4;
  text: string;
  textKey: string;
}) {
  const headingClassName = cn(
    formattedTextWrap,
    "leading-tight text-foreground",
    displayDepth === 2 ? "text-[1.0625rem] font-semibold" : "text-base font-semibold",
    displayDepth === 4 ? "text-base uppercase tracking-normal text-muted-foreground" : undefined,
  );
  const Tag = `h${displayDepth}` as const;

  return (
    <Tag className={headingClassName}>
      <FormattedInline keyPrefix={textKey} text={text} />
    </Tag>
  );
}

function nextFormattedTextKey(
  keyCounts: Map<string, number>,
  kind: string,
  value: string,
): string {
  const baseKey = `${kind}:${value}`;
  const occurrence = keyCounts.get(baseKey) ?? 0;
  keyCounts.set(baseKey, occurrence + 1);
  return occurrence === 0 ? baseKey : `${baseKey}:${occurrence}`;
}

export function FormattedText({
  className,
  dir = "auto",
  lang,
  value,
}: {
  className?: string;
  dir?: React.HTMLAttributes<HTMLDivElement>["dir"];
  lang?: string;
  value: string;
}) {
  const lines = value.split("\n");
  const blocks: React.ReactNode[] = [];
  const keyCounts = new Map<string, number>();
  let index = 0;

  while (index < lines.length) {
    const trimmed = lines[index]?.trim() ?? "";

    if (!trimmed) {
      index += 1;
      continue;
    }

    const headingMatch = /^(#{1,4})\s+(.+)$/.exec(trimmed);
    if (headingMatch) {
      const markdownDepth = headingMatch[1].length;
      const displayDepth = Math.min(markdownDepth + 1, 4) as 2 | 3 | 4;
      const text = headingMatch[2].trim();
      const headingKey = nextFormattedTextKey(keyCounts, "heading", `${markdownDepth}:${text}`);
      blocks.push(
        <FormattedHeading displayDepth={displayDepth} key={headingKey} text={text} textKey={headingKey} />,
      );
      index += 1;
      continue;
    }

    if (/^>\s?/.test(trimmed)) {
      const quoteLines: string[] = [];
      while (index < lines.length && /^>\s?/.test(lines[index]?.trim() ?? "")) {
        quoteLines.push((lines[index] ?? "").trim().replace(/^>\s?/, ""));
        index += 1;
      }
      const quoteKey = nextFormattedTextKey(keyCounts, "quote", quoteLines.join("\n"));
      blocks.push(
        <blockquote
          className={cn(formattedTextWrap, "border-s-2 border-border-soft ps-4 italic text-muted-foreground")}
          key={quoteKey}
        >
          <FormattedParagraph lines={quoteLines} textKey={quoteKey} />
        </blockquote>,
      );
      continue;
    }

    if (/^[-*]\s+/.test(trimmed)) {
      const items: React.ReactNode[] = [];
      const itemLines: string[] = [];
      while (index < lines.length && /^[-*]\s+/.test(lines[index]?.trim() ?? "")) {
        const itemLine = (lines[index] ?? "").trim().replace(/^[-*]\s+/, "");
        const itemKey = nextFormattedTextKey(keyCounts, "ul-item", itemLine);
        itemLines.push(itemLine);
        items.push(
          <li className={formattedTextWrap} key={itemKey}>
            <FormattedInline keyPrefix={itemKey} text={itemLine} />
          </li>,
        );
        index += 1;
      }
      const listKey = nextFormattedTextKey(keyCounts, "ul-block", itemLines.join("\n"));
      blocks.push(
        <ul className={cn(formattedTextWrap, "list-disc space-y-1 ps-6 leading-snug text-inherit")} key={listKey}>
          {items}
        </ul>,
      );
      continue;
    }

    if (/^\d+\.\s+/.test(trimmed)) {
      const items: React.ReactNode[] = [];
      const itemLines: string[] = [];
      while (index < lines.length && /^\d+\.\s+/.test(lines[index]?.trim() ?? "")) {
        const itemLine = (lines[index] ?? "").trim().replace(/^\d+\.\s+/, "");
        const itemKey = nextFormattedTextKey(keyCounts, "ol-item", itemLine);
        itemLines.push(itemLine);
        items.push(
          <li className={formattedTextWrap} key={itemKey}>
            <FormattedInline keyPrefix={itemKey} text={itemLine} />
          </li>,
        );
        index += 1;
      }
      const listKey = nextFormattedTextKey(keyCounts, "ol-block", itemLines.join("\n"));
      blocks.push(
        <ol className={cn(formattedTextWrap, "list-decimal space-y-1 ps-6 leading-snug text-inherit")} key={listKey}>
          {items}
        </ol>,
      );
      continue;
    }

    const paragraphLines: string[] = [];
    while (index < lines.length) {
      const line = lines[index] ?? "";
      const lineTrimmed = line.trim();
      if (!lineTrimmed || /^(#{1,4})\s+(.+)$/.test(lineTrimmed) || /^>\s?/.test(lineTrimmed) || /^[-*]\s+/.test(lineTrimmed) || /^\d+\.\s+/.test(lineTrimmed)) {
        break;
      }
      paragraphLines.push(line);
      index += 1;
    }
    const paragraphKey = nextFormattedTextKey(keyCounts, "p", paragraphLines.join("\n"));
    blocks.push(
      <FormattedParagraph key={paragraphKey} lines={paragraphLines} textKey={paragraphKey} />,
    );
  }

  return (
    <div
      className={cn(formattedTextWrap, "space-y-3 text-base", className)}
      dir={dir}
      lang={lang}
    >
      {blocks}
    </div>
  );
}

// packages/solid-ui/src/components/data-display/formatted-text/formatted-text.tsx
import type { JSX } from "@solidjs/web";
import { Dynamic } from "@solidjs/web";
import { createMemo } from "solid-js";

import { typeVariants } from "@/components/data-display/type/type";
import { cn } from "@/lib/cn";

const formattedTextWrap =
  "min-w-0 max-w-full break-words [overflow-wrap:anywhere] [word-break:break-word]";
const formattedTextLinkWrap = "break-all [word-break:break-all]";

const inlinePattern =
  /(\[([^\]]+)\]\((https?:\/\/[^)\s]+)\)|\*\*\*([\s\S]+?)\*\*\*|\*\*([\s\S]+?)\*\*|\*([\s\S]+?)\*|~~([\s\S]+?)~~)/g;

function renderInline(text: string): JSX.Element[] {
  const nodes: JSX.Element[] = [];
  let lastIndex = 0;

  for (const match of text.matchAll(inlinePattern)) {
    const index = match.index ?? 0;

    if (index > lastIndex) {
      nodes.push(text.slice(lastIndex, index));
    }

    const [, , linkLabel, linkHref, boldItalicText, boldText, italicText, strikeText] =
      match;

    if (linkLabel && linkHref) {
      nodes.push(
        <a
          class={cn(
            formattedTextWrap,
            formattedTextLinkWrap,
            "text-primary-text underline underline-offset-4",
          )}
          href={linkHref}
          rel="noreferrer"
          target="_blank"
        >
          {linkLabel}
        </a>,
      );
    } else if (boldItalicText) {
      nodes.push(
        <strong>
          <em>{renderInline(boldItalicText)}</em>
        </strong>,
      );
    } else if (boldText) {
      nodes.push(<strong>{renderInline(boldText)}</strong>);
    } else if (italicText) {
      nodes.push(<em>{renderInline(italicText)}</em>);
    } else if (strikeText) {
      nodes.push(<s>{renderInline(strikeText)}</s>);
    } else {
      nodes.push(match[0]);
    }

    lastIndex = index + match[0].length;
  }

  if (lastIndex < text.length) {
    nodes.push(text.slice(lastIndex));
  }

  return nodes;
}

function FormattedInline(props: { text: string }) {
  return <>{renderInline(props.text)}</>;
}

function FormattedParagraph(props: { lines: string[] }) {
  const text = () => props.lines.join(" ");
  const isBareUrl = () => /^https?:\/\/\S+$/u.test(text().trim());

  return (
    <p
      class={cn(
        formattedTextWrap,
        "leading-snug text-inherit",
        isBareUrl() && formattedTextLinkWrap,
      )}
    >
      <FormattedInline text={text()} />
    </p>
  );
}

function FormattedHeading(props: { displayDepth: 2 | 3 | 4; text: string }) {
  return (
    <Dynamic
      component={`h${props.displayDepth}`}
      class={cn(
        formattedTextWrap,
        "leading-tight",
        typeVariants({
          variant: props.displayDepth === 4 ? "overline" : "body-strong",
        }),
      )}
    >
      <FormattedInline text={props.text} />
    </Dynamic>
  );
}

function parseBlocks(value: string): JSX.Element[] {
  const lines = value.split("\n");
  const blocks: JSX.Element[] = [];
  let index = 0;

  while (index < lines.length) {
    const trimmed = lines[index]?.trim() ?? "";

    if (!trimmed) {
      index += 1;
      continue;
    }

    const headingMatch = /^(#{1,4})\s+(.+)$/.exec(trimmed);
    if (headingMatch) {
      const markdownDepth = headingMatch[1].length;
      const displayDepth = Math.min(markdownDepth + 1, 4) as 2 | 3 | 4;
      const text = headingMatch[2].trim();
      blocks.push(<FormattedHeading displayDepth={displayDepth} text={text} />);
      index += 1;
      continue;
    }

    if (/^>\s?/.test(trimmed)) {
      const quoteLines: string[] = [];
      while (index < lines.length && /^>\s?/.test(lines[index]?.trim() ?? "")) {
        quoteLines.push((lines[index] ?? "").trim().replace(/^>\s?/, ""));
        index += 1;
      }
      blocks.push(
        <blockquote
          class={cn(
            formattedTextWrap,
            "border-s-2 border-border-soft ps-4 italic text-muted-foreground",
          )}
        >
          <FormattedParagraph lines={quoteLines} />
        </blockquote>,
      );
      continue;
    }

    if (/^[-*]\s+/.test(trimmed)) {
      const items: JSX.Element[] = [];
      while (index < lines.length && /^[-*]\s+/.test(lines[index]?.trim() ?? "")) {
        const itemLine = (lines[index] ?? "").trim().replace(/^[-*]\s+/, "");
        items.push(
          <li class={formattedTextWrap}>
            <FormattedInline text={itemLine} />
          </li>,
        );
        index += 1;
      }
      blocks.push(
        <ul class={cn(formattedTextWrap, "list-disc space-y-1 ps-6 leading-snug text-inherit")}>
          {items}
        </ul>,
      );
      continue;
    }

    if (/^\d+\.\s+/.test(trimmed)) {
      const items: JSX.Element[] = [];
      while (index < lines.length && /^\d+\.\s+/.test(lines[index]?.trim() ?? "")) {
        const itemLine = (lines[index] ?? "").trim().replace(/^\d+\.\s+/, "");
        items.push(
          <li class={formattedTextWrap}>
            <FormattedInline text={itemLine} />
          </li>,
        );
        index += 1;
      }
      blocks.push(
        <ol class={cn(formattedTextWrap, "list-decimal space-y-1 ps-6 leading-snug text-inherit")}>
          {items}
        </ol>,
      );
      continue;
    }

    const paragraphLines: string[] = [];
    while (index < lines.length) {
      const line = lines[index] ?? "";
      const lineTrimmed = line.trim();
      if (
        !lineTrimmed ||
        /^(#{1,4})\s+(.+)$/.test(lineTrimmed) ||
        /^>\s?/.test(lineTrimmed) ||
        /^[-*]\s+/.test(lineTrimmed) ||
        /^\d+\.\s+/.test(lineTrimmed)
      ) {
        break;
      }
      paragraphLines.push(line);
      index += 1;
    }
    blocks.push(<FormattedParagraph lines={paragraphLines} />);
  }

  return blocks;
}

export interface FormattedTextProps {
  class?: string;
  dir?: "ltr" | "rtl" | "auto";
  lang?: string;
  value: string;
}

/**
 * FormattedText - renders markdown-lite content (headings `#`–`####`, `>`
 * quotes, `-`/`*` and `1.` lists, `**bold**`, `*italic*`, `~~strike~~`, and
 * `[label](https://...)` links) into semantic HTML. Headings start at `h2` so
 * document-level `h1` elements stay outside content. Use it for user-authored
 * post and comment bodies; do not use it for trusted app copy, which should
 * stay plain text.
 */
export function FormattedText(props: FormattedTextProps) {
  const blocks = createMemo(() => parseBlocks(props.value));
  const className = createMemo(() =>
    cn(formattedTextWrap, "space-y-3 text-base", props.class),
  );

  return (
    <div class={className()} dir={props.dir ?? "auto"} lang={props.lang}>
      {blocks()}
    </div>
  );
}
