// solid/src/features/bookings/profile-book-panel/profile-book-panel.tsx
import { Show, createMemo } from "solid-js";

import { AvailabilityCalendar } from "../availability-calendar/availability-calendar";
import { Button, Card, Type, cn } from "../../../design-system";
import type { IanaTz, ResolvedSlot } from "../view-models";
import { profileBookEmptyLabel, sessionFactsLine } from "./profile-book-panel-model";

interface ProfileBookPanelViewerProps {
  mode: "viewer";
  startingPriceCents: number;
  slots: ResolvedSlot[];
  loading?: boolean;
  viewerTimezone: IanaTz;
  getSlotHref?: (slot: ResolvedSlot) => string;
  onSelectSlot?: (slot: ResolvedSlot, event?: MouseEvent) => void;
  class?: string;
}

interface ProfileBookPanelOwnerProps {
  mode: "owner";
  configured: boolean;
  basePriceCents: number;
  slots: ResolvedSlot[];
  loading?: boolean;
  viewerTimezone: IanaTz;
  onEdit?: () => void;
  class?: string;
}

export type ProfileBookPanelProps = ProfileBookPanelViewerProps | ProfileBookPanelOwnerProps;

function OwnerBookPanel(props: ProfileBookPanelOwnerProps) {
  return (
    <Show when={props.configured} fallback={<Card class={cn("flex flex-col gap-4 border-border bg-card p-5 shadow-none", props.class)}><Type variant="body">Set up a schedule so people can book time with you.</Type><Button onClick={props.onEdit}>Set up bookings</Button></Card>}>
      <div class={cn("flex flex-col gap-4", props.class)} data-profile-book-panel="owner-configured">
        <div class="flex items-center justify-between gap-3"><Type as="h2" variant="h3">Your availability</Type><Button onClick={props.onEdit} size="sm" variant="outline">Edit schedule</Button></div>
        <Show when={!props.loading} fallback={<Type variant="caption">Loading availability…</Type>}>
          <Show when={props.slots.length > 0} fallback={<Type variant="caption">{profileBookEmptyLabel("owner")}</Type>}>
            <Type variant="caption">{sessionFactsLine(props.slots, props.viewerTimezone, props.basePriceCents)}</Type>
            <AvailabilityCalendar slots={props.slots} viewerTimezone={props.viewerTimezone} />
          </Show>
        </Show>
      </div>
    </Show>
  );
}

function ViewerBookPanel(props: ProfileBookPanelViewerProps) {
  return (
    <div class={cn("flex h-full min-h-0 flex-col gap-3", props.class)} data-profile-book-panel="viewer">
      <Show when={!props.loading} fallback={<Type variant="caption">Loading availability…</Type>}>
        <Show when={props.slots.length > 0} fallback={<Type variant="caption">{profileBookEmptyLabel("viewer")}</Type>}>
          <Type variant="body-strong">{sessionFactsLine(props.slots, props.viewerTimezone, props.startingPriceCents)}</Type>
          <AvailabilityCalendar class="min-h-0 flex-1" getSlotHref={props.getSlotHref} onSelectSlot={props.onSelectSlot} slots={props.slots} viewerTimezone={props.viewerTimezone} />
        </Show>
      </Show>
    </div>
  );
}

export function ProfileBookPanel(props: ProfileBookPanelProps) {
  const isOwner = createMemo(() => props.mode === "owner");
  return <Show when={isOwner()} fallback={<ViewerBookPanel {...(props as ProfileBookPanelViewerProps)} />}><OwnerBookPanel {...(props as ProfileBookPanelOwnerProps)} /></Show>;
}

// src/components/compositions/bookings/profile-book-panel/profile-book-panel.tsx
"use client";

import * as React from "react";

import { Button } from "@/components/primitives/button";
import { Card } from "@/components/primitives/card";
import { Type } from "@/components/primitives/type";
import { useUiLocale } from "@/lib/ui-locale";
import { getLocaleMessages } from "@/locales";
import { cn } from "@/lib/utils";
import { formatCentsAsStartingUsd } from "@/components/compositions/bookings/fixtures/bookings-format";

import { AvailabilityCalendar } from "@/components/compositions/bookings/availability-calendar/availability-calendar";
import type { IanaTz, ResolvedSlot } from "@/components/compositions/bookings/view-models";

interface ProfileBookPanelViewerProps {
  mode: "viewer";
  /** Canonical cheapest currently bookable slot, already resolved by the server/feed. */
  startingPriceCents: number;
  slots: ResolvedSlot[];
  /** Availability is still loading — show a loading hint instead of the empty state. */
  loading?: boolean;
  viewerTimezone: IanaTz;
  getSlotHref?: (slot: ResolvedSlot) => string;
  onSelectSlot: (slot: ResolvedSlot, event?: React.MouseEvent) => void;
  className?: string;
}

interface ProfileBookPanelOwnerProps {
  mode: "owner";
  /** Whether the host has a set-up schedule (bookable-configured). false → setup prompt. */
  configured: boolean;
  basePriceCents: number;
  slots: ResolvedSlot[];
  /** Availability is still loading — show a loading hint instead of the empty state. */
  loading?: boolean;
  viewerTimezone: IanaTz;
  onEdit: () => void;
  className?: string;
}

export type ProfileBookPanelProps = ProfileBookPanelViewerProps | ProfileBookPanelOwnerProps;

/**
 * Content of the profile "Calendar" tab. Presentational + controlled; the container supplies the
 * host's resolved slots. Owner sees their real availability (read-only) + an Edit-schedule action;
 * viewer sees availability + price and a slot tap → checkout. No data fetching, no money here.
 */
export function ProfileBookPanel(props: ProfileBookPanelProps) {
  const { locale } = useUiLocale();
  const copy = getLocaleMessages(locale, "routes").profile;

  if (props.mode === "owner") {
    if (!props.configured) {
      return (
        <Card className={cn("space-y-4 border-border bg-card p-5 shadow-none", props.className)}>
          <Type as="p" variant="body" className="text-muted-foreground">{copy.ownerSetupPrompt}</Type>
          <Button type="button" onClick={props.onEdit}>{copy.setUpBookings}</Button>
        </Card>
      );
    }
    return (
      <div className={cn("space-y-4", props.className)}>
        <div className="flex items-center justify-between gap-3">
          <Type as="p" variant="body-strong">{copy.ownerAvailabilityTitle}</Type>
          <Button variant="outline" size="sm" type="button" onClick={props.onEdit}>{copy.editSchedule}</Button>
        </div>
        {props.loading ? (
          <Type as="p" variant="caption" className="text-muted-foreground">Loading availability…</Type>
        ) : props.slots.length === 0 ? (
          <Type as="p" variant="caption" className="text-muted-foreground">{copy.bookNoAvailability}</Type>
        ) : (
          // Read-only for the owner (no slot tap).
          <AvailabilityCalendar slots={props.slots} viewerTimezone={props.viewerTimezone} />
        )}
      </div>
    );
  }

  return (
    <div className={cn("space-y-4", props.className)}>
      <Type as="p" variant="body-strong">
        {formatCentsAsStartingUsd(props.startingPriceCents)}
      </Type>
      {props.loading ? (
        <Type as="p" variant="caption" className="text-muted-foreground">Loading availability…</Type>
      ) : props.slots.length === 0 ? (
        <Type as="p" variant="caption" className="text-muted-foreground">{copy.bookNoAvailability}</Type>
      ) : (
        <AvailabilityCalendar
          slots={props.slots}
          viewerTimezone={props.viewerTimezone}
          getSlotHref={props.getSlotHref}
          onSelectSlot={props.onSelectSlot}
        />
      )}
    </div>
  );
}
