// solid/src/features/shell/content-rail-shell.tsx
import type { JSX } from "@solidjs/web";
import { Show } from "solid-js";

import { cn } from "../../lib/cn";

export interface ContentRailShellProps {
  children?: JSX.Element;
  class?: string;
  contentClass?: string;
  header?: JSX.Element;
  rail?: JSX.Element;
  railClass?: string;
  reserveRail?: boolean;
}

export function ContentRailShell(props: ContentRailShellProps) {
  const showRailColumn = () => props.reserveRail || Boolean(props.rail);

  return (
    <section class={cn("mx-auto flex w-full min-w-0 max-w-[65.5rem] flex-col gap-5", props.class)}>
      <Show when={props.header}>
        <div class="min-w-0">{props.header}</div>
      </Show>
      <div class="flex min-w-0 flex-col gap-6 xl:flex-row xl:items-start">
        <div class={cn("min-w-0 xl:flex-1", props.contentClass)}>{props.children}</div>
        <Show when={showRailColumn()}>
          <div class="min-w-0 xl:w-72 xl:shrink-0">
            <Show when={props.rail}>
              <aside class={cn("hidden xl:block", props.railClass)}>{props.rail}</aside>
            </Show>
          </div>
        </Show>
      </div>
    </section>
  );
}

// src/components/compositions/content-rail-shell/content-rail-shell.tsx
"use client";

import * as React from "react";

import { cn } from "@/lib/utils";

export interface ContentRailShellProps {
  children: React.ReactNode;
  className?: string;
  contentClassName?: string;
  header?: React.ReactNode;
  rail?: React.ReactNode;
  railClassName?: string;
}

export function ContentRailShell({
  children,
  className,
  contentClassName,
  header,
  rail,
  railClassName,
}: ContentRailShellProps) {
  return (
    <section className={cn("mx-auto flex w-full min-w-0 max-w-[65.5rem] flex-col gap-5", className)}>
      {header ? <div className="min-w-0">{header}</div> : null}
      <div className="flex min-w-0 flex-col gap-6 xl:flex-row xl:items-start">
        <div className={cn("min-w-0 xl:flex-1", contentClassName)}>{children}</div>
        {rail ? (
          <div className="min-w-0 xl:w-72 xl:shrink-0">
            <aside className={cn("hidden xl:block", railClassName)}>{rail}</aside>
            <div className="xl:hidden">{rail}</div>
          </div>
        ) : null}
      </div>
    </section>
  );
}
