// src/components/primitives/layout-shell.tsx
import type { HTMLAttributes } from "react";

import { cn } from "@/lib/utils";

export function CardShell({
  className,
  ...props
}: HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      className={cn("rounded-[var(--radius-3xl)] border border-border-soft bg-card", className)}
      {...props}
    />
  );
}

export function PageContainer({
  className,
  size = "default",
  gutter = false,
  ...props
}: HTMLAttributes<HTMLDivElement> & {
  size?: "default" | "feed" | "narrow" | "rail" | "wide";
  gutter?: boolean;
}) {
  const sizeClassName = {
    default: "max-w-5xl",
    feed: "max-w-[46rem]",
    narrow: "max-w-4xl",
    rail: "max-w-[65.5rem]",
    wide: "max-w-7xl",
  }[size];

  return (
    <div
      className={cn(
        "mx-auto w-full",
        sizeClassName,
        className,
        gutter && "px-[var(--page-gutter-x)] md:px-[var(--page-gutter-x-md)] lg:px-[var(--page-gutter-x-lg)]",
      )}
      {...props}
    />
  );
}

// packages/solid-ui/src/patterns/layout/layout-shell/layout-shell.tsx
import type { JSX } from "@solidjs/web";
import { createMemo, omit, type ParentProps } from "solid-js";

import { cn } from "@/lib/cn";

export function CardShell(
  props: ParentProps<JSX.HTMLAttributes<HTMLDivElement> & { class?: string }>,
) {
  const className = createMemo(() =>
    cn("rounded-[var(--radius-3xl)] border border-border-soft bg-card", props.class),
  );
  const rest = omit(props, "class", "children");

  return (
    <div class={className()} {...rest}>
      {props.children}
    </div>
  );
}

const pageSizeClasses = {
  default: "max-w-5xl",
  feed: "max-w-[46rem]",
  narrow: "max-w-4xl",
  rail: "max-w-[65.5rem]",
  wide: "max-w-7xl",
} as const;

export interface PageContainerProps
  extends JSX.HTMLAttributes<HTMLDivElement> {
  class?: string;
  size?: keyof typeof pageSizeClasses;
  gutter?: boolean;
}

export function PageContainer(props: ParentProps<PageContainerProps>) {
  const className = createMemo(() =>
    cn(
      "mx-auto w-full",
      pageSizeClasses[props.size ?? "default"],
      props.gutter &&
        "px-[var(--page-gutter-x)] md:px-[var(--page-gutter-x-md)] lg:px-[var(--page-gutter-x-lg)]",
      props.class,
    ),
  );
  const rest = omit(props, "class", "size", "gutter", "children");

  return (
    <div class={className()} {...rest}>
      {props.children}
    </div>
  );
}
