// packages/solid-ui/src/patterns/overlays/modal/modal.tsx
import { Dynamic } from "@solidjs/web";
import type { JSX } from "@solidjs/web";
import {
  createContext,
  useContext,
  type Accessor,
  type ParentProps,
} from "solid-js";

import { createClientHydrated } from "@/lib/hydration";
import { createIsMobile } from "@/lib/media-query";
import { cn } from "@/lib/cn";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/overlays/dialog/dialog";
import {
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetTitle,
} from "@/components/overlays/sheet/sheet";
import { typeVariants } from "@/components/data-display/type/type";

const ModalResponsiveContext = createContext<Accessor<boolean>>();

function useModalIsMobile(): Accessor<boolean> {
  const contextValue = useContext(ModalResponsiveContext);
  if (!contextValue) {
    throw new Error("Modal components must be rendered within <Modal>.");
  }
  return contextValue;
}

export interface ModalProps {
  children?: JSX.Element;
  forceMobile?: boolean;
  onOpenChange?: (open: boolean) => void;
  open?: boolean;
  defaultOpen?: boolean;
  modal?: boolean;
}

/**
 * Responsive modal root: renders its content as a centered Dialog on desktop
 * and a Sheet (bottom sheet by default) on mobile. Mobile detection is
 * hydration-gated so SSR always renders the desktop branch; forceMobile
 * overrides detection for stories and tests.
 */
export function Modal(props: ParentProps<ModalProps>) {
  const detectedMobile = createIsMobile();
  const hydrated = createClientHydrated();
  const isMobile = () => props.forceMobile ?? (hydrated() ? detectedMobile() : false);

  const rootProps = () =>
    ({
      open: props.open,
      defaultOpen: props.defaultOpen,
      onOpenChange: props.onOpenChange,
      modal: props.modal,
    }) as const;

  return (
    <ModalResponsiveContext value={isMobile}>
      <Dialog {...rootProps()}>{props.children}</Dialog>
    </ModalResponsiveContext>
  );
}

export interface ModalContentProps {
  children?: JSX.Element;
  class?: string;
  hideCloseButton?: boolean;
  hideCloseButtonOnMobile?: boolean;
  mobileSide?: "top" | "bottom" | "left" | "right";
}

export function ModalContent(props: ParentProps<ModalContentProps>) {
  const isMobile = useModalIsMobile();
  const shouldHideCloseButton = () =>
    props.hideCloseButton || (isMobile() && (props.hideCloseButtonOnMobile ?? false));

  return (
    <Dynamic
      component={isMobile() ? SheetContent : DialogContent}
      class={props.class}
      hideCloseButton={shouldHideCloseButton()}
      {...(isMobile() ? { side: props.mobileSide ?? "bottom" } : {})}
    >
      {props.children}
    </Dynamic>
  );
}

export function ModalHeader(props: ParentProps<{ class?: string }>) {
  const isMobile = useModalIsMobile();
  return (
    <Dynamic component={isMobile() ? SheetHeader : DialogHeader} class={props.class}>
      {props.children}
    </Dynamic>
  );
}

export function ModalFooter(props: ParentProps<{ class?: string }>) {
  const isMobile = useModalIsMobile();
  return (
    <Dynamic component={isMobile() ? SheetFooter : DialogFooter} class={props.class}>
      {props.children}
    </Dynamic>
  );
}

export function ModalTitle(props: ParentProps<{ class?: string }>) {
  const isMobile = useModalIsMobile();
  return (
    <Dynamic
      component={isMobile() ? SheetTitle : DialogTitle}
      class={cn(typeVariants({ variant: "h3" }), props.class)}
    >
      {props.children}
    </Dynamic>
  );
}

export function ModalDescription(props: ParentProps<{ class?: string }>) {
  const isMobile = useModalIsMobile();
  return (
    <Dynamic component={isMobile() ? SheetDescription : DialogDescription} class={props.class}>
      {props.children}
    </Dynamic>
  );
}

// src/components/compositions/modal/modal.tsx
"use client";

import * as React from "react";
import * as DialogPrimitive from "@radix-ui/react-dialog";

import { cn } from "@/lib/utils";
import { typeVariants } from "@/components/primitives/type";
import { useIsMobile } from "@/hooks/use-mobile";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/primitives/dialog";
import {
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetTitle,
} from "@/components/primitives/sheet";

export const ModalResponsiveContext = React.createContext<boolean | null>(null);

function useModalIsMobile() {
  const contextValue = React.useContext(ModalResponsiveContext);

  if (contextValue === null) {
    throw new Error("Modal components must be rendered within <Modal>.");
  }

  return contextValue;
}

interface ModalProps extends React.ComponentProps<typeof Dialog> {
  forceMobile?: boolean;
}

function Modal({ forceMobile, ...props }: ModalProps) {
  const detectedMobile = useIsMobile();
  const isMobile = forceMobile ?? detectedMobile;

  return (
    <ModalResponsiveContext.Provider value={isMobile}>
      <Dialog {...props} />
    </ModalResponsiveContext.Provider>
  );
}

interface ModalContentProps
  extends React.ComponentPropsWithoutRef<typeof DialogPrimitive.Content> {
  mobileSide?: "top" | "bottom" | "left" | "right";
}

const ModalContent = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Content>,
  ModalContentProps
>(({ className, mobileSide = "bottom", ...props }, ref) => {
  const isMobile = useModalIsMobile();

  if (isMobile) {
    return <SheetContent className={className} ref={ref} side={mobileSide} {...props} />;
  }

  return <DialogContent className={className} ref={ref} {...props} />;
});
ModalContent.displayName = "ModalContent";

const ModalHeader = ({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) => {
  const isMobile = useModalIsMobile();
  const Comp = isMobile ? SheetHeader : DialogHeader;

  return <Comp className={className} {...props} />;
};
ModalHeader.displayName = "ModalHeader";

const ModalFooter = ({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) => {
  const isMobile = useModalIsMobile();
  const Comp = isMobile ? SheetFooter : DialogFooter;

  return <Comp className={className} {...props} />;
};
ModalFooter.displayName = "ModalFooter";

const ModalTitle = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Title>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitive.Title>
>(({ className, ...props }, ref) => {
  const isMobile = useModalIsMobile();
  const Comp = isMobile ? SheetTitle : DialogTitle;

  return <Comp className={cn(typeVariants({ variant: "h3" }), className)} ref={ref} {...props} />;
});
ModalTitle.displayName = "ModalTitle";

const ModalDescription = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Description>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitive.Description>
>(({ className, ...props }, ref) => {
  const isMobile = useModalIsMobile();
  const Comp = isMobile ? SheetDescription : DialogDescription;

  return <Comp className={cn(className)} ref={ref} {...props} />;
});
ModalDescription.displayName = "ModalDescription";

export {
  Modal,
  ModalContent,
  ModalDescription,
  ModalFooter,
  ModalHeader,
  ModalTitle,
};
