// src/components/primitives/dropdown-menu.tsx
"use client";

import * as React from "react";
import * as DropdownMenuPrimitive from "@radix-ui/react-dropdown-menu";
import { cn } from "@/lib/utils";

const DropdownMenu = DropdownMenuPrimitive.Root;
const DropdownMenuTrigger = DropdownMenuPrimitive.Trigger;

const DropdownMenuContent = React.forwardRef<
  React.ElementRef<typeof DropdownMenuPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof DropdownMenuPrimitive.Content>
>(({ className, sideOffset = 4, ...props }, ref) => (
  <DropdownMenuPrimitive.Portal>
    <DropdownMenuPrimitive.Content
      ref={ref}
      sideOffset={sideOffset}
      className={cn(
        "relative z-50 max-h-96 min-w-[8rem] overflow-hidden rounded-[var(--radius-lg)] border border-border bg-popover text-popover-foreground shadow-md data-[state=open]:animate-in data-[state=closed]:animate-out",
        "data-[side=bottom]:translate-y-1 data-[side=left]:-translate-x-1 data-[side=right]:translate-x-1 data-[side=top]:-translate-y-1",
        className,
      )}
      {...props}
    />
  </DropdownMenuPrimitive.Portal>
));
DropdownMenuContent.displayName = DropdownMenuPrimitive.Content.displayName;

const DropdownMenuItem = React.forwardRef<
  React.ElementRef<typeof DropdownMenuPrimitive.Item>,
  React.ComponentPropsWithoutRef<typeof DropdownMenuPrimitive.Item>
>(({ className, ...props }, ref) => (
  <DropdownMenuPrimitive.Item
    className={cn(
      "relative flex w-full cursor-pointer select-none items-center rounded-none py-2.5 pl-8 pr-3 text-base outline-none transition-colors text-popover-foreground hover:text-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50",
      className,
    )}
    ref={ref}
    {...props}
  >
    {props.children}
  </DropdownMenuPrimitive.Item>
));
DropdownMenuItem.displayName = DropdownMenuPrimitive.Item.displayName;

const DropdownMenuSeparator = React.forwardRef<
  React.ElementRef<typeof DropdownMenuPrimitive.Separator>,
  React.ComponentPropsWithoutRef<typeof DropdownMenuPrimitive.Separator>
>(({ className, ...props }, ref) => (
  <DropdownMenuPrimitive.Separator
    className={cn("-mx-1 my-1 h-px bg-border", className)}
    ref={ref}
    {...props}
  />
));
DropdownMenuSeparator.displayName = DropdownMenuPrimitive.Separator.displayName;

export {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
};

// packages/solid-ui/src/components/overlays/dropdown-menu/dropdown-menu.tsx
import { DropdownMenu as KMenu } from "@kobalte/core/dropdown-menu";
import { createMemo, omit, type ParentProps } from "solid-js";

import { IconCheck } from "@/components/media/icons";
import { cn } from "@/lib/cn";

const DropdownMenu = KMenu;
const DropdownMenuTrigger = KMenu.Trigger;
const DropdownMenuGroup = KMenu.Group;
const DropdownMenuRadioGroup = KMenu.RadioGroup;

const itemClasses =
  "relative flex w-full cursor-pointer select-none items-center rounded-none py-2.5 pe-8 ps-3 text-start text-base text-popover-foreground outline-none transition-colors hover:text-foreground focus:bg-muted focus:text-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50 data-[highlighted]:bg-muted";

function DropdownMenuContent(
  props: ParentProps<Parameters<typeof KMenu.Content>[0]>,
) {
  const className = createMemo(() =>
    cn(
      "relative z-50 max-h-96 min-w-32 overflow-hidden rounded-[var(--radius-lg)] border border-border bg-popover p-0 text-popover-foreground shadow-md",
      props.class,
    ),
  );
  const rest = omit(props, "class", "children");

  return (
    <KMenu.Portal>
      <KMenu.Content class={className()} {...rest}>
        {props.children}
      </KMenu.Content>
    </KMenu.Portal>
  );
}

function DropdownMenuItem(
  props: ParentProps<Parameters<typeof KMenu.Item>[0]>,
) {
  const className = createMemo(() => cn(itemClasses, props.class));
  const rest = omit(props, "class", "children");

  return (
    <KMenu.Item class={className()} {...rest}>
      {props.children}
    </KMenu.Item>
  );
}

function DropdownMenuCheckboxItem(
  props: ParentProps<Parameters<typeof KMenu.CheckboxItem>[0]>,
) {
  const className = createMemo(() => cn(itemClasses, props.class));
  const rest = omit(props, "class", "children");

  return (
    <KMenu.CheckboxItem class={className()} {...rest}>
      <KMenu.ItemIndicator class="absolute end-2 inline-flex size-4 items-center justify-center">
        <IconCheck class="size-3.5" />
      </KMenu.ItemIndicator>
      {props.children}
    </KMenu.CheckboxItem>
  );
}

function DropdownMenuRadioItem(
  props: ParentProps<Parameters<typeof KMenu.RadioItem>[0]>,
) {
  const className = createMemo(() => cn(itemClasses, props.class));
  const rest = omit(props, "class", "children");

  return (
    <KMenu.RadioItem class={className()} {...rest}>
      <KMenu.ItemIndicator class="absolute end-2 inline-flex size-4 items-center justify-center">
        <IconCheck class="size-3.5" />
      </KMenu.ItemIndicator>
      {props.children}
    </KMenu.RadioItem>
  );
}

function DropdownMenuGroupLabel(
  props: ParentProps<Parameters<typeof KMenu.GroupLabel>[0]>,
) {
  const className = createMemo(() =>
    cn("px-3 py-2 text-base font-semibold text-muted-foreground", props.class),
  );
  const rest = omit(props, "class", "children");

  return (
    <KMenu.GroupLabel class={className()} {...rest}>
      {props.children}
    </KMenu.GroupLabel>
  );
}

function DropdownMenuSeparator(
  props: Parameters<typeof KMenu.Separator>[0],
) {
  const className = createMemo(() => cn("my-1 h-px bg-border", props.class));

  return <KMenu.Separator class={className()} {...omit(props, "class")} />;
}

export {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuGroupLabel,
  DropdownMenuItem,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
};
