// src/components/primitives/card.tsx
"use client";

import * as React from "react";

import { cn } from "@/lib/utils";
import { typeVariants } from "./type";

const Card = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div
      className={cn(
        "rounded-[var(--radius-lg)] border border-border-soft bg-card text-card-foreground shadow-[var(--shadow-md)]",
        className,
      )}
      ref={ref}
      {...props}
    />
  ),
);
Card.displayName = "Card";

const CardHeader = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div className={cn("flex flex-col space-y-1.5 p-6", className)} ref={ref} {...props} />
  ),
);
CardHeader.displayName = "CardHeader";

const CardTitle = React.forwardRef<HTMLHeadingElement, React.HTMLAttributes<HTMLHeadingElement>>(
  ({ className, ...props }, ref) => (
    <h2
      className={cn(typeVariants({ variant: "h3" }), "text-balance", className)}
      ref={ref}
      {...props}
    />
  ),
);
CardTitle.displayName = "CardTitle";

const CardDescription = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLParagraphElement>
>(({ className, ...props }, ref) => (
  <p className={cn(typeVariants({ variant: "caption" }), className)} ref={ref} {...props} />
));
CardDescription.displayName = "CardDescription";

const CardContent = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div className={cn("p-6 pt-0", className)} ref={ref} {...props} />
  ),
);
CardContent.displayName = "CardContent";

const CardFooter = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div className={cn("flex items-center p-6 pt-0", className)} ref={ref} {...props} />
  ),
);
CardFooter.displayName = "CardFooter";

export { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle };

// packages/solid-ui/src/components/data-display/card/card.tsx
import type { JSX } from "@solidjs/web";
import { createMemo, omit, type ParentProps } from "solid-js";

import { typeVariants } from "@/components/data-display/type/type";
import { cn } from "@/lib/cn";

function Card(props: ParentProps<JSX.HTMLAttributes<HTMLDivElement> & { class?: string }>) {
  const className = createMemo(() =>
    cn(
      "rounded-[var(--radius-lg)] border border-border-soft bg-card text-card-foreground shadow-[var(--shadow-md)]",
      props.class,
    ),
  );
  const rest = omit(props, "class", "children");

  return (
    <div class={className()} {...rest}>
      {props.children}
    </div>
  );
}

function CardHeader(props: ParentProps<JSX.HTMLAttributes<HTMLDivElement> & { class?: string }>) {
  const className = createMemo(() =>
    cn("flex flex-col space-y-1.5 p-6", props.class),
  );
  const rest = omit(props, "class", "children");

  return (
    <div class={className()} {...rest}>
      {props.children}
    </div>
  );
}

function CardTitle(props: ParentProps<JSX.HTMLAttributes<HTMLHeadingElement> & { class?: string }>) {
  const className = createMemo(() =>
    cn(typeVariants({ variant: "h3" }), "text-balance", props.class),
  );
  const rest = omit(props, "class", "children");

  return (
    <h3 class={className()} {...rest}>
      {props.children}
    </h3>
  );
}

function CardDescription(
  props: ParentProps<JSX.HTMLAttributes<HTMLParagraphElement> & { class?: string }>,
) {
  const className = createMemo(() =>
    cn(typeVariants({ variant: "caption" }), props.class),
  );
  const rest = omit(props, "class", "children");

  return (
    <p class={className()} {...rest}>
      {props.children}
    </p>
  );
}

function CardContent(props: ParentProps<JSX.HTMLAttributes<HTMLDivElement> & { class?: string }>) {
  const className = createMemo(() => cn("p-6 pt-0", props.class));
  const rest = omit(props, "class", "children");

  return (
    <div class={className()} {...rest}>
      {props.children}
    </div>
  );
}

function CardFooter(props: ParentProps<JSX.HTMLAttributes<HTMLDivElement> & { class?: string }>) {
  const className = createMemo(() => cn("flex items-center p-6 pt-0", props.class));
  const rest = omit(props, "class", "children");

  return (
    <div class={className()} {...rest}>
      {props.children}
    </div>
  );
}

export { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle };
