// src/components/primitives/combobox.tsx
"use client";

import * as React from "react";
import { Combobox as ComboboxPrimitive } from "@base-ui/react/combobox";
import { Check, X } from "@phosphor-icons/react";

import { cn } from "@/lib/utils";

function Combobox<Value, Multiple extends boolean | undefined = false>(
  props: React.ComponentProps<typeof ComboboxPrimitive.Root<Value, Multiple>>,
) {
  return <ComboboxPrimitive.Root {...props} />;
}

function ComboboxInput({ className, ref, ...props }: React.ComponentProps<typeof ComboboxPrimitive.Input>) {
  return (
    <ComboboxPrimitive.Input
      ref={ref}
      className={cn(
        "flex h-11 w-full rounded-full border border-input bg-background px-4 py-2 text-base shadow-sm transition-[color,box-shadow,border-color] outline-none placeholder:text-muted-foreground focus-visible:border-border focus-visible:ring-1 focus-visible:ring-border-soft disabled:cursor-not-allowed disabled:opacity-50",
        className,
      )}
      {...props}
    />
  );
}

function ComboboxChips({ className, ref, ...props }: React.ComponentProps<typeof ComboboxPrimitive.Chips>) {
  return (
    <ComboboxPrimitive.Chips
      ref={ref}
      className={cn(
        "flex min-h-11 w-full flex-wrap items-center gap-2 rounded-[var(--radius-2_5xl)] border border-input bg-background px-3 py-2 shadow-sm transition-[color,box-shadow,border-color] focus-within:border-border focus-within:ring-1 focus-within:ring-border-soft",
        className,
      )}
      {...props}
    />
  );
}

function ComboboxChipsInput({ className, ref, ...props }: React.ComponentProps<typeof ComboboxPrimitive.Input>) {
  return (
    <ComboboxPrimitive.Input
      ref={ref}
      className={cn(
        "min-w-32 flex-1 bg-transparent py-1 text-base outline-none placeholder:text-muted-foreground",
        className,
      )}
      {...props}
    />
  );
}

function ComboboxChip({ children, className, ref, ...props }: React.ComponentProps<typeof ComboboxPrimitive.Chip>) {
  return (
    <ComboboxPrimitive.Chip
      ref={ref}
      className={cn(
        "inline-flex items-center gap-2 rounded-full border border-border-soft bg-muted px-3 py-1.5 text-base font-medium text-foreground",
        className,
      )}
      {...props}
    >
      <span className="truncate">{children}</span>
      <ComboboxPrimitive.ChipRemove
        className="inline-flex size-5 items-center justify-center rounded-full text-muted-foreground transition-colors hover:bg-background hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
        aria-label="Remove item"
      >
        <X className="size-3.5" />
      </ComboboxPrimitive.ChipRemove>
    </ComboboxPrimitive.Chip>
  );
}

const ComboboxValue = ComboboxPrimitive.Value;

function ComboboxContent({
  align = "start",
  className,
  collisionPadding = 8,
  ref,
  sideOffset = 6,
  ...props
}: React.ComponentProps<typeof ComboboxPrimitive.Popup> & React.ComponentProps<typeof ComboboxPrimitive.Positioner>) {
  return (
    <ComboboxPrimitive.Portal>
      <ComboboxPrimitive.Positioner
        align={align}
        collisionPadding={collisionPadding}
        sideOffset={sideOffset}
      >
        <ComboboxPrimitive.Popup
          ref={ref}
          className={cn(
            "z-50 w-[var(--anchor-width)] overflow-hidden rounded-[var(--radius-lg)] border border-border bg-popover text-popover-foreground shadow-md outline-none data-[ending-style]:opacity-0 data-[starting-style]:opacity-0",
            className,
          )}
          {...props}
        />
      </ComboboxPrimitive.Positioner>
    </ComboboxPrimitive.Portal>
  );
}

function ComboboxEmpty({ className, ref, ...props }: React.ComponentProps<typeof ComboboxPrimitive.Empty>) {
  return (
    <ComboboxPrimitive.Empty
      ref={ref}
      className={cn("px-4 py-3 text-base text-muted-foreground", className)}
      {...props}
    />
  );
}

function ComboboxList({ className, ref, ...props }: React.ComponentProps<typeof ComboboxPrimitive.List>) {
  return (
    <ComboboxPrimitive.List
      ref={ref}
      className={cn("max-h-80 overflow-y-auto py-1", className)}
      {...props}
    />
  );
}

function ComboboxItem({ children, className, ref, ...props }: React.ComponentProps<typeof ComboboxPrimitive.Item>) {
  return (
    <ComboboxPrimitive.Item
      ref={ref}
      className={cn(
        "relative flex w-full cursor-pointer select-none items-center gap-3 px-4 py-2.5 text-base text-popover-foreground outline-none transition-colors data-[highlighted]:bg-muted data-[disabled]:pointer-events-none data-[disabled]:opacity-50",
        className,
      )}
      {...props}
    >
      <ComboboxPrimitive.ItemIndicator className="absolute start-2.5 flex size-5 items-center justify-center text-primary data-[selected=false]:hidden">
        <Check className="size-4" weight="bold" />
      </ComboboxPrimitive.ItemIndicator>
      <div className="min-w-0 flex-1 ps-6">{children}</div>
    </ComboboxPrimitive.Item>
  );
}

function ComboboxGroup({ className, ref, ...props }: React.ComponentProps<typeof ComboboxPrimitive.Group>) {
  return <ComboboxPrimitive.Group ref={ref} className={cn("py-1", className)} {...props} />;
}

function ComboboxLabel({ className, ref, ...props }: React.ComponentProps<typeof ComboboxPrimitive.GroupLabel>) {
  return (
    <ComboboxPrimitive.GroupLabel
      ref={ref}
      className={cn("px-4 py-2 text-base font-semibold text-foreground", className)}
      {...props}
    />
  );
}

const ComboboxCollection = ComboboxPrimitive.Collection;
const ComboboxSeparator = ComboboxPrimitive.Separator;
function ComboboxTrigger({ children, className, ref, ...props }: React.ComponentProps<typeof ComboboxPrimitive.Trigger>) {
  return (
    <ComboboxPrimitive.Trigger
      ref={ref}
      className={cn(
        "flex h-11 w-full items-center justify-between rounded-full border border-input bg-background px-4 py-2 text-base shadow-sm transition-[color,box-shadow,border-color] focus-visible:border-border focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-border-soft disabled:cursor-not-allowed disabled:opacity-50 data-[placeholder]:text-muted-foreground",
        className,
      )}
      {...props}
    >
      <span className="truncate">{children}</span>
      <span aria-hidden="true" className="ms-2 shrink-0 text-base text-muted-foreground">
        ▾
      </span>
    </ComboboxPrimitive.Trigger>
  );
}

export {
  Combobox,
  ComboboxChip,
  ComboboxChips,
  ComboboxChipsInput,
  ComboboxCollection,
  ComboboxContent,
  ComboboxEmpty,
  ComboboxGroup,
  ComboboxInput,
  ComboboxItem,
  ComboboxLabel,
  ComboboxList,
  ComboboxSeparator,
  ComboboxTrigger,
  ComboboxValue,
};

// packages/solid-ui/src/components/forms/combobox/combobox.tsx
import {
  Combobox as KCombobox,
  type ComboboxRootItemComponentProps,
} from "@kobalte/core/combobox";
import { createMemo } from "solid-js";

import { IconArrowDown, IconCheck } from "@/components/media/icons";
import { cn } from "@/lib/cn";

export interface ComboboxProps<Option> {
  /** Available options. */
  options: Option[];
  /** Extract the submitted value of an option. */
  optionValue: (option: Option) => string;
  /** Extract the display label of an option. */
  optionLabel: (option: Option) => string;
  /** Extract the disabled flag of an option. */
  optionDisabled?: (option: Option) => boolean;
  /** Controlled selected value. */
  value?: string | null;
  /** Uncontrolled default selected value. */
  defaultValue?: string;
  /** Called when the selection changes. */
  onChange?: (value: string | null) => void;
  /** Placeholder shown while the input is empty. */
  placeholder?: string;
  disabled?: boolean;
  class?: string;
  /** Extra classes for the input shell. */
  inputClass?: string;
  /** Extra classes for the popup content. */
  contentClass?: string;
  /** Accessible name for the combobox input. */
  "aria-label"?: string;
}

function ComboboxItem(props: ComboboxRootItemComponentProps<unknown>) {
  const item = props.item;

  return (
    <KCombobox.Item
      item={item}
      class="relative flex w-full cursor-pointer select-none items-center rounded-lg px-8 py-2.5 text-base outline-none transition-colors text-popover-foreground data-highlighted:bg-muted data-highlighted:text-foreground data-selected:text-foreground data-disabled:pointer-events-none data-disabled:opacity-50"
    >
      <KCombobox.ItemIndicator class="absolute start-2.5 flex size-5 items-center justify-center text-primary">
        <IconCheck class="size-4" />
      </KCombobox.ItemIndicator>
      <KCombobox.ItemLabel class="truncate">{item.textValue}</KCombobox.ItemLabel>
    </KCombobox.Item>
  );
}

/**
 * Combobox - a text input with an attached popup list of options. The input
 * accepts free text; picking an option commits its value. Data-driven like
 * Select. Use it when the value set is large and users benefit from typing
 * to narrow the list.
 */
export function Combobox<Option>(props: ComboboxProps<Option>) {
  const className = createMemo(() =>
    cn("flex w-full flex-col gap-1.5", props.class),
  );

  const findOption = (value: string) =>
    props.options.find((option) => props.optionValue(option) === value);

  const selectedOption = () =>
    props.value == null ? null : (findOption(props.value) ?? null);

  const defaultOption = () =>
    props.defaultValue == null ? undefined : findOption(props.defaultValue);

  const rootProps = () =>
    ({
      options: props.options,
      optionValue: props.optionValue,
      optionTextValue: props.optionLabel,
      optionLabel: props.optionLabel,
      optionDisabled: props.optionDisabled,
      value: selectedOption(),
      defaultValue: defaultOption(),
      onChange: (option: Option | Option[] | null) => {
        const first = Array.isArray(option) ? option[0] : option;
        props.onChange?.(
          first == null ? null : props.optionValue(first),
        );
      },
      placeholder: props.placeholder,
      disabled: props.disabled,
      multiple: false,
      itemComponent: ComboboxItem,
    }) as const;

  return (
    <KCombobox {...rootProps()} class={className()}>
      <KCombobox.Control
        class={cn(
          "flex h-11 w-full items-center rounded-full border border-input bg-background px-4 shadow-sm transition-[color,box-shadow,border-color] focus-within:border-border focus-within:ring-1 focus-within:ring-border-soft data-disabled:cursor-not-allowed data-disabled:opacity-50",
          props.inputClass,
        )}
      >
        <KCombobox.Input
          aria-label={props["aria-label"]}
          class="h-full w-full border-0 bg-transparent text-base outline-none placeholder:text-muted-foreground"
        />
        <KCombobox.Trigger class="group flex size-8 shrink-0 cursor-pointer items-center justify-center rounded-full text-muted-foreground transition-colors hover:bg-muted hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">
          <IconArrowDown class="size-4 transition-transform group-data-[expanded]:rotate-180" />
        </KCombobox.Trigger>
      </KCombobox.Control>
      <KCombobox.Portal>
        <KCombobox.Content
          class={cn(
            "z-50 max-w-[var(--kb-popper-anchor-width)] min-w-32 overflow-hidden rounded-[var(--radius-lg)] border border-border bg-popover p-1 text-popover-foreground shadow-md",
            props.contentClass,
          )}
        >
          <KCombobox.Listbox class="max-h-80 overflow-y-auto py-0 outline-none" />
        </KCombobox.Content>
      </KCombobox.Portal>
      <KCombobox.HiddenSelect />
    </KCombobox>
  );
}
