// src/components/compositions/bookings/host-availability-editor/host-availability-editor.tsx
import * as React from "react";
import { Plus, Trash } from "@phosphor-icons/react";

import { Button } from "@/components/primitives/button";
import { Card, CardContent } from "@/components/primitives/card";
import { Input } from "@/components/primitives/input";
import { Separator } from "@/components/primitives/separator";
import { Type } from "@/components/primitives/type";
import { cn } from "@/lib/utils";

const WEEKDAY_LABELS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"] as const;

export interface AvailabilityRuleDraft {
  id: string;
  byWeekday: number[];
  startLocal: string;
  endLocal: string;
  slotDurationMinutes: number;
}

export interface PriceRuleDraft {
  id: string;
  matchWeekday: number[];
  startLocal: string;
  endLocal: string;
  priceCents: number;
}

export interface AvailabilityExceptionDraft {
  id: string;
  kind: "block" | "open";
  startUtc: string;
  endUtc: string;
}

export interface HostAvailabilityEditorProps {
  rules: AvailabilityRuleDraft[];
  priceRules: PriceRuleDraft[];
  exceptions: AvailabilityExceptionDraft[];
  onRulesChange?: (rules: AvailabilityRuleDraft[]) => void;
  onPriceRulesChange?: (rules: PriceRuleDraft[]) => void;
  onExceptionsChange?: (exceptions: AvailabilityExceptionDraft[]) => void;
  className?: string;
}

let nextDraftId = 0;
function newDraftId(prefix: string): string {
  nextDraftId += 1;
  return `${prefix}-${nextDraftId}`;
}

export function HostAvailabilityEditor({
  rules,
  priceRules,
  exceptions,
  onRulesChange,
  onPriceRulesChange,
  onExceptionsChange,
  className,
}: HostAvailabilityEditorProps) {
  const toggleWeekday = (ruleId: string, day: number) => {
    if (!onRulesChange) return;
    const rule = rules.find((r) => r.id === ruleId);
    if (!rule) return;
    const has = rule.byWeekday.includes(day);
    onRulesChange(
      rules.map((r) =>
        r.id === ruleId
          ? {
              ...r,
              byWeekday: has
                ? r.byWeekday.filter((d) => d !== day)
                : [...r.byWeekday, day].sort(),
            }
          : r,
      ),
    );
  };

  const updateRule = (ruleId: string, patch: Partial<AvailabilityRuleDraft>) => {
    onRulesChange?.(rules.map((r) => (r.id === ruleId ? { ...r, ...patch } : r)));
  };

  const addRule = () => {
    onRulesChange?.([
      ...rules,
      {
        id: newDraftId("rule"),
        byWeekday: [1, 2, 3, 4, 5],
        startLocal: "09:00",
        endLocal: "17:00",
        slotDurationMinutes: 30,
      },
    ]);
  };

  const removeRule = (ruleId: string) => {
    onRulesChange?.(rules.filter((r) => r.id !== ruleId));
  };

  const addPriceRule = () => {
    onPriceRulesChange?.([
      ...priceRules,
      {
        id: newDraftId("price"),
        matchWeekday: [1, 2, 3, 4, 5],
        startLocal: "09:00",
        endLocal: "12:00",
        priceCents: 6000,
      },
    ]);
  };

  const removePriceRule = (id: string) => {
    onPriceRulesChange?.(priceRules.filter((r) => r.id !== id));
  };

  const updatePriceRule = (id: string, patch: Partial<PriceRuleDraft>) => {
    onPriceRulesChange?.(priceRules.map((r) => (r.id === id ? { ...r, ...patch } : r)));
  };

  const addException = () => {
    onExceptionsChange?.([
      ...exceptions,
      {
        id: newDraftId("exc"),
        kind: "block",
        startUtc: "2026-07-04T00:00:00Z",
        endUtc: "2026-07-04T23:59:59Z",
      },
    ]);
  };

  const removeException = (id: string) => {
    onExceptionsChange?.(exceptions.filter((e) => e.id !== id));
  };

  const updateException = (id: string, patch: Partial<AvailabilityExceptionDraft>) => {
    onExceptionsChange?.(exceptions.map((e) => (e.id === id ? { ...e, ...patch } : e)));
  };

  return (
    <div className={cn("flex flex-col gap-6", className)}>
      {/* Recurring rules */}
      <Card>
        <CardContent className="flex flex-col gap-4 p-6">
          <div className="flex items-center justify-between">
            <Type as="h2" variant="h3">
              Recurring availability
            </Type>
            <Button onClick={addRule} size="icon" variant="secondary">
              <Plus />
            </Button>
          </div>
          {rules.length === 0 ? (
            <Type variant="caption">No recurring rules yet.</Type>
          ) : null}
          {rules.map((rule) => (
            <div key={rule.id} className="flex flex-col gap-3 rounded-[var(--radius-md)] border border-border-soft p-4">
              <div className="flex items-center justify-between">
                <Type variant="label">Rule</Type>
                <Button onClick={() => removeRule(rule.id)} size="icon" variant="ghost">
                  <Trash />
                </Button>
              </div>
              <div className="flex flex-wrap gap-2">
                {WEEKDAY_LABELS.map((label, day) => (
                  <button
                    key={label}
                    className={cn(
                      "h-9 w-9 rounded-full border text-center transition-colors",
                      rule.byWeekday.includes(day)
                        ? "border-primary bg-primary text-primary-foreground"
                        : "border-border-soft bg-card",
                    )}
                    onClick={() => toggleWeekday(rule.id, day)}
                    type="button"
                  >
                    <Type as="span" variant="caption">
                      {label[0]}
                    </Type>
                  </button>
                ))}
              </div>
              <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:gap-4">
                <label className="flex flex-col gap-1">
                  <Type variant="caption">Start</Type>
                  <Input
                    onChange={(e) => updateRule(rule.id, { startLocal: e.target.value })}
                    type="time"
                    value={rule.startLocal}
                  />
                </label>
                <label className="flex flex-col gap-1">
                  <Type variant="caption">End</Type>
                  <Input
                    onChange={(e) => updateRule(rule.id, { endLocal: e.target.value })}
                    type="time"
                    value={rule.endLocal}
                  />
                </label>
                <label className="flex flex-col gap-1">
                  <Type variant="caption">Slot length (min)</Type>
                  <Input
                    min={5}
                    onChange={(e) =>
                      updateRule(rule.id, { slotDurationMinutes: parseInt(e.target.value, 10) || 30 })
                    }
                    type="number"
                    value={rule.slotDurationMinutes}
                  />
                </label>
              </div>
            </div>
          ))}
        </CardContent>
      </Card>

      {/* Price rules */}
      <Card>
        <CardContent className="flex flex-col gap-4 p-6">
          <div className="flex items-center justify-between">
            <Type as="h2" variant="h3">
              Variable pricing
            </Type>
            <Button onClick={addPriceRule} size="icon" variant="secondary">
              <Plus />
            </Button>
          </div>
          {priceRules.length === 0 ? (
            <Type variant="caption">No variable pricing — base price applies to all slots.</Type>
          ) : null}
          {priceRules.map((rule) => (
            <div key={rule.id} className="flex flex-col gap-3 rounded-[var(--radius-md)] border border-border-soft p-4">
              <div className="flex items-center justify-between">
                <Type variant="label">Price rule</Type>
                <Button onClick={() => removePriceRule(rule.id)} size="icon" variant="ghost">
                  <Trash />
                </Button>
              </div>
              <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:gap-4">
                <label className="flex flex-col gap-1">
                  <Type variant="caption">Start</Type>
                  <Input
                    onChange={(e) => updatePriceRule(rule.id, { startLocal: e.target.value })}
                    type="time"
                    value={rule.startLocal}
                  />
                </label>
                <label className="flex flex-col gap-1">
                  <Type variant="caption">End</Type>
                  <Input
                    onChange={(e) => updatePriceRule(rule.id, { endLocal: e.target.value })}
                    type="time"
                    value={rule.endLocal}
                  />
                </label>
                <label className="flex flex-col gap-1">
                  <Type variant="caption">Price (cents)</Type>
                  <Input
                    min={0}
                    onChange={(e) =>
                      updatePriceRule(rule.id, { priceCents: parseInt(e.target.value, 10) || 0 })
                    }
                    type="number"
                    value={rule.priceCents}
                  />
                </label>
              </div>
            </div>
          ))}
        </CardContent>
      </Card>

      {/* Exceptions */}
      <Card>
        <CardContent className="flex flex-col gap-4 p-6">
          <div className="flex items-center justify-between">
            <Type as="h2" variant="h3">
              One-off exceptions
            </Type>
            <Button onClick={addException} size="icon" variant="secondary">
              <Plus />
            </Button>
          </div>
          {exceptions.length === 0 ? (
            <Type variant="caption">No exceptions — recurring rules apply as-is.</Type>
          ) : null}
          {exceptions.map((exc) => (
            <div key={exc.id} className="flex flex-col gap-3 rounded-[var(--radius-md)] border border-border-soft p-4">
              <div className="flex items-center justify-between">
                <Type variant="label">{exc.kind === "block" ? "Block" : "Open window"}</Type>
                <Button onClick={() => removeException(exc.id)} size="icon" variant="ghost">
                  <Trash />
                </Button>
              </div>
              <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:gap-4">
                <label className="flex flex-col gap-1">
                  <Type variant="caption">Start (UTC)</Type>
                  <Input
                    onChange={(e) => updateException(exc.id, { startUtc: e.target.value })}
                    type="datetime-local"
                    value={exc.startUtc.replace("Z", "")}
                  />
                </label>
                <label className="flex flex-col gap-1">
                  <Type variant="caption">End (UTC)</Type>
                  <Input
                    onChange={(e) => updateException(exc.id, { endUtc: e.target.value })}
                    type="datetime-local"
                    value={exc.endUtc.replace("Z", "")}
                  />
                </label>
                <label className="flex flex-col gap-1">
                  <Type variant="caption">Type</Type>
                  <select
                    className="h-11 rounded-full border border-border-soft bg-card px-4 text-base"
                    onChange={(e) =>
                      updateException(exc.id, { kind: e.target.value as "block" | "open" })
                    }
                    value={exc.kind}
                  >
                    <option value="block">Block</option>
                    <option value="open">Open</option>
                  </select>
                </label>
              </div>
            </div>
          ))}
        </CardContent>
      </Card>
    </div>
  );
}

// solid/src/features/bookings/host-availability-editor/host-availability-editor.tsx
import { For, Show } from "solid-js";

import { Button, Card, CardContent, IconPlus, IconX, Input, Type, cn } from "../../../design-system";
import {
  WEEKDAY_LABELS,
  clampPriceCents,
  clampSlotDurationMinutes,
  localUtcInput,
  nextDraftId,
  toggleDay,
  utcFromLocalInput,
  type AvailabilityExceptionDraft,
  type AvailabilityRuleDraft,
  type PriceRuleDraft,
} from "./host-availability-editor-model";

export interface HostAvailabilityEditorProps {
  rules: AvailabilityRuleDraft[];
  priceRules: PriceRuleDraft[];
  exceptions: AvailabilityExceptionDraft[];
  onRulesChange?: (rules: AvailabilityRuleDraft[]) => void;
  onPriceRulesChange?: (rules: PriceRuleDraft[]) => void;
  onExceptionsChange?: (exceptions: AvailabilityExceptionDraft[]) => void;
  class?: string;
}

export function HostAvailabilityEditor(props: HostAvailabilityEditorProps) {
  const updateRule = (id: string, patch: Partial<AvailabilityRuleDraft>) => props.onRulesChange?.(props.rules.map((rule) => rule.id === id ? { ...rule, ...patch } : rule));
  const updatePrice = (id: string, patch: Partial<PriceRuleDraft>) => props.onPriceRulesChange?.(props.priceRules.map((rule) => rule.id === id ? { ...rule, ...patch } : rule));
  const updateException = (id: string, patch: Partial<AvailabilityExceptionDraft>) => props.onExceptionsChange?.(props.exceptions.map((entry) => entry.id === id ? { ...entry, ...patch } : entry));
  const addRule = () => props.onRulesChange?.([...props.rules, { id: nextDraftId("rule", props.rules.map((rule) => rule.id)), byWeekday: [1, 2, 3, 4, 5], startLocal: "09:00", endLocal: "17:00", slotDurationMinutes: 30 }]);
  const addPrice = () => props.onPriceRulesChange?.([...props.priceRules, { id: nextDraftId("price", props.priceRules.map((rule) => rule.id)), matchWeekday: [1, 2, 3, 4, 5], startLocal: "09:00", endLocal: "12:00", priceCents: 6000 }]);
  const addException = () => props.onExceptionsChange?.([...props.exceptions, { id: nextDraftId("exc", props.exceptions.map((entry) => entry.id)), kind: "block", startUtc: "2026-07-04T00:00:00Z", endUtc: "2026-07-04T23:59:59Z" }]);

  return (
    <div class={cn("flex flex-col gap-6", props.class)} data-availability-editor>
      <Card><CardContent class="flex flex-col gap-4 p-6">
        <div class="flex items-center justify-between"><Type as="h2" variant="h3">Recurring availability</Type><Button aria-label="Add recurring rule" onClick={addRule} size="icon" variant="secondary"><IconPlus aria-hidden="true" /></Button></div>
        <Show when={props.rules.length > 0} fallback={<Type variant="caption">No recurring rules yet.</Type>}>
          <For each={props.rules}>{(rule) => <div class="flex flex-col gap-3 rounded-[var(--radius-md)] border border-border-soft p-4">
            <div class="flex items-center justify-between"><Type variant="label">Rule</Type><Button aria-label={`Remove rule ${rule.id}`} onClick={() => props.onRulesChange?.(props.rules.filter((entry) => entry.id !== rule.id))} size="icon" variant="ghost"><IconX aria-hidden="true" /></Button></div>
            <div class="flex flex-wrap gap-2" role="group" aria-label="Days of week"><For each={WEEKDAY_LABELS}>{(label, day) => <button aria-label={`${label} availability`} aria-pressed={rule.byWeekday.includes(day()) ? "true" : "false"} class={cn("size-11 rounded-full border", rule.byWeekday.includes(day()) ? "border-primary bg-primary text-primary-foreground" : "border-border-soft bg-card")} onClick={() => updateRule(rule.id, { byWeekday: toggleDay(rule.byWeekday, day()) })} type="button"><Type as="span" variant="caption" class={rule.byWeekday.includes(day()) ? "text-primary-foreground" : undefined}>{label.slice(0, 1)}</Type></button>}</For></div>
            <div class="grid gap-3 sm:grid-cols-3">
              <label class="flex flex-col gap-1"><Type variant="caption">Start</Type><Input aria-label={`Start time for ${rule.id}`} onInput={(event) => updateRule(rule.id, { startLocal: event.currentTarget.value })} type="time" value={rule.startLocal} /></label>
              <label class="flex flex-col gap-1"><Type variant="caption">End</Type><Input aria-label={`End time for ${rule.id}`} onInput={(event) => updateRule(rule.id, { endLocal: event.currentTarget.value })} type="time" value={rule.endLocal} /></label>
              <label class="flex flex-col gap-1"><Type variant="caption">Slot length (min)</Type><Input aria-label={`Slot length for ${rule.id}`} min="5" onInput={(event) => updateRule(rule.id, { slotDurationMinutes: clampSlotDurationMinutes(Number(event.currentTarget.value)) })} type="number" value={rule.slotDurationMinutes} /></label>
            </div>
          </div>}</For>
        </Show>
      </CardContent></Card>

      <Card><CardContent class="flex flex-col gap-4 p-6">
        <div class="flex items-center justify-between"><Type as="h2" variant="h3">Variable pricing</Type><Button aria-label="Add price rule" onClick={addPrice} size="icon" variant="secondary"><IconPlus aria-hidden="true" /></Button></div>
        <Show when={props.priceRules.length > 0} fallback={<Type variant="caption">No variable pricing — base price applies to all slots.</Type>}>
          <For each={props.priceRules}>{(rule) => <div class="flex flex-col gap-3 rounded-[var(--radius-md)] border border-border-soft p-4">
            <div class="flex items-center justify-between"><Type variant="label">Price rule</Type><Button aria-label={`Remove price rule ${rule.id}`} onClick={() => props.onPriceRulesChange?.(props.priceRules.filter((entry) => entry.id !== rule.id))} size="icon" variant="ghost"><IconX aria-hidden="true" /></Button></div>
            <div class="grid gap-3 sm:grid-cols-3"><label class="flex flex-col gap-1"><Type variant="caption">Start</Type><Input aria-label={`Price start for ${rule.id}`} onInput={(event) => updatePrice(rule.id, { startLocal: event.currentTarget.value })} type="time" value={rule.startLocal} /></label><label class="flex flex-col gap-1"><Type variant="caption">End</Type><Input aria-label={`Price end for ${rule.id}`} onInput={(event) => updatePrice(rule.id, { endLocal: event.currentTarget.value })} type="time" value={rule.endLocal} /></label><label class="flex flex-col gap-1"><Type variant="caption">Price (cents)</Type><Input aria-label={`Price cents for ${rule.id}`} min="1" onInput={(event) => updatePrice(rule.id, { priceCents: clampPriceCents(Number(event.currentTarget.value)) })} type="number" value={rule.priceCents} /></label></div>
          </div>}</For>
        </Show>
      </CardContent></Card>

      <Card><CardContent class="flex flex-col gap-4 p-6">
        <div class="flex items-center justify-between"><Type as="h2" variant="h3">One-off exceptions</Type><Button aria-label="Add availability exception" onClick={addException} size="icon" variant="secondary"><IconPlus aria-hidden="true" /></Button></div>
        <Show when={props.exceptions.length > 0} fallback={<Type variant="caption">No exceptions — recurring rules apply as-is.</Type>}>
          <For each={props.exceptions}>{(entry) => <div class="flex flex-col gap-3 rounded-[var(--radius-md)] border border-border-soft p-4"><div class="flex items-center justify-between"><Type variant="label">{entry.kind === "block" ? "Block" : "Open window"}</Type><Button aria-label={`Remove exception ${entry.id}`} onClick={() => props.onExceptionsChange?.(props.exceptions.filter((candidate) => candidate.id !== entry.id))} size="icon" variant="ghost"><IconX aria-hidden="true" /></Button></div><div class="grid gap-3 sm:grid-cols-3"><label class="flex flex-col gap-1"><Type variant="caption">Start (UTC)</Type><Input aria-label={`Exception start for ${entry.id}`} onInput={(event) => updateException(entry.id, { startUtc: utcFromLocalInput(event.currentTarget.value) })} type="datetime-local" value={localUtcInput(entry.startUtc)} /></label><label class="flex flex-col gap-1"><Type variant="caption">End (UTC)</Type><Input aria-label={`Exception end for ${entry.id}`} onInput={(event) => updateException(entry.id, { endUtc: utcFromLocalInput(event.currentTarget.value) })} type="datetime-local" value={localUtcInput(entry.endUtc)} /></label><label class="flex flex-col gap-1"><Type variant="caption">Type</Type><select aria-label={`Exception type for ${entry.id}`} class="h-11 rounded-full border border-border-soft bg-card px-4" onChange={(event) => updateException(entry.id, { kind: event.currentTarget.value as "block" | "open" })} value={entry.kind}><option value="block">Block</option><option value="open">Open</option></select></label></div></div>}</For>
        </Show>
      </CardContent></Card>
    </div>
  );
}

export type { AvailabilityExceptionDraft, AvailabilityRuleDraft, PriceRuleDraft } from "./host-availability-editor-model";
