// solid/src/features/bookings/booking-checkout/booking-checkout.tsx
import { Show, createMemo } from "solid-js";

import { Button, Card, CardContent, Type, cn } from "../../../design-system";
import { formatCentsAsUsdc } from "../booking-format";
import type { BookingQuotePreview, IanaTz } from "../view-models";
import {
  checkoutHeading,
  formatHoldCountdown,
  secondsUntilHoldExpires,
  type BookingCheckoutPhase,
} from "./booking-checkout-model";

export interface BookingCheckoutProps {
  quote: BookingQuotePreview;
  viewerTimezone: IanaTz;
  phase: BookingCheckoutPhase;
  holdExpiresAtUtc: string;
  nowUtc: string;
  onPay?: () => void;
  onReleaseHold?: () => void;
  class?: string;
}

export function BookingCheckout(props: BookingCheckoutProps) {
  const secondsRemaining = createMemo(() => secondsUntilHoldExpires(props.holdExpiresAtUtc, props.nowUtc));
  return (
    <Card class={props.class} data-booking-checkout data-phase={props.phase}>
      <CardContent class="flex flex-col gap-4 p-6">
        <div class="flex flex-col gap-1">
          <Type as="h2" variant="h3">{checkoutHeading(props.phase)}</Type>
          <Show when={props.phase === "holding"}>
            <Type variant="caption">Pay {formatCentsAsUsdc(props.quote.grossCents)} to confirm your session.</Type>
          </Show>
          <Show when={props.phase === "pending"}>
            <Type variant="caption">Waiting for your payment to be confirmed on-chain. This usually takes a few seconds.</Type>
          </Show>
          <Show when={props.phase === "conflict"}>
            <Type variant="caption">Someone else booked it while you were viewing. Pick another slot to continue.</Type>
          </Show>
        </div>

        <Show when={props.phase === "holding"}>
          <div class="flex flex-col gap-1" aria-live="polite">
            <Type variant="caption">Slot held for</Type>
            <Type as="span" variant="h2" class={cn(secondsRemaining() <= 60 && "text-warning")}>
              {formatHoldCountdown(secondsRemaining())}
            </Type>
          </div>
          <Button class="w-full" onClick={props.onPay} size="lg">
            Pay {formatCentsAsUsdc(props.quote.grossCents)}
          </Button>
          <Show when={props.onReleaseHold}>
            <Button onClick={props.onReleaseHold} variant="ghost">Cancel</Button>
          </Show>
        </Show>

        <Show when={props.phase === "pending"}>
          <div class="flex items-center justify-between gap-3 border-t border-border-soft pt-4">
            <Type variant="body">Total</Type>
            <Type variant="body-strong">{formatCentsAsUsdc(props.quote.grossCents)}</Type>
          </div>
        </Show>

        <Show when={props.phase === "conflict" && props.onReleaseHold}>
          <Button onClick={props.onReleaseHold} variant="secondary">Back to slots</Button>
        </Show>
      </CardContent>
    </Card>
  );
}

// src/components/compositions/bookings/booking-checkout/booking-checkout.tsx
import * as React from "react";

import { Button } from "@/components/primitives/button";
import { Card, CardContent } from "@/components/primitives/card";
import { Type } from "@/components/primitives/type";
import { cn } from "@/lib/utils";
import type { BookingQuotePreview, IanaTz } from "../view-models";

import { formatCentsAsUsdc } from "../fixtures/bookings-format";

type CheckoutPhase = "holding" | "pending" | "conflict";

export interface BookingCheckoutProps {
  quote: BookingQuotePreview;
  viewerTimezone: IanaTz;
  phase: CheckoutPhase;
  holdExpiresAtUtc: string;
  nowUtc: string;
  onPay?: () => void;
  onReleaseHold?: () => void;
  className?: string;
}

function formatCountdown(secondsRemaining: number): string {
  if (secondsRemaining <= 0) return "0:00";
  const m = Math.floor(secondsRemaining / 60);
  const s = secondsRemaining % 60;
  return `${m}:${String(s).padStart(2, "0")}`;
}

export function BookingCheckout({
  quote,
  phase,
  holdExpiresAtUtc,
  nowUtc,
  onPay,
  onReleaseHold,
  className,
}: BookingCheckoutProps) {
  const secondsRemaining = React.useMemo(() => {
    const diff = Math.floor((Date.parse(holdExpiresAtUtc) - Date.parse(nowUtc)) / 1000);
    return Math.max(0, diff);
  }, [holdExpiresAtUtc, nowUtc]);

  if (phase === "conflict") {
    return (
      <Card className={className}>
        <CardContent className="flex flex-col gap-4 p-6">
          <div className="flex flex-col gap-1">
            <Type variant="label">That slot was released</Type>
            <Type variant="caption">
              Someone else booked it while you were viewing. Pick another slot to continue.
            </Type>
          </div>
          {onReleaseHold ? (
            <Button onClick={onReleaseHold} variant="secondary">
              Back to slots
            </Button>
          ) : null}
        </CardContent>
      </Card>
    );
  }

  if (phase === "pending") {
    return (
      <Card className={className}>
        <CardContent className="flex flex-col gap-4 p-6">
          <div className="flex flex-col gap-1">
            <Type variant="label">Payment verifying</Type>
            <Type variant="caption">
              Waiting for your payment to be confirmed on-chain. This usually takes a few seconds.
            </Type>
          </div>
          <div className="flex items-center justify-between">
            <Type variant="body">Total</Type>
            <Type variant="body-strong">{formatCentsAsUsdc(quote.grossCents)}</Type>
          </div>
        </CardContent>
      </Card>
    );
  }

  // holding
  return (
    <Card className={className}>
      <CardContent className="flex flex-col gap-4 p-6">
        <div className="flex flex-col gap-1">
          <Type variant="label">Complete your payment</Type>
          <Type variant="caption">
            Pay {formatCentsAsUsdc(quote.grossCents)} to confirm your session.
          </Type>
        </div>

        <div className="flex flex-col gap-1">
          <Type variant="caption">Slot held for</Type>
          <Type
            as="span"
            variant="h3"
            className={cn(secondsRemaining <= 60 && "text-warning")}
          >
            {formatCountdown(secondsRemaining)}
          </Type>
        </div>

        <Button className="w-full" onClick={onPay} size="lg">
          Pay {formatCentsAsUsdc(quote.grossCents)}
        </Button>

        {onReleaseHold ? (
          <Button onClick={onReleaseHold} variant="ghost">
            Cancel
          </Button>
        ) : null}
      </CardContent>
    </Card>
  );
}
