// src/components/primitives/checkbox-card.tsx
"use client";

import * as React from "react";

import { Checkbox } from "@/components/primitives/checkbox";
import { cn } from "@/lib/utils";

export interface CheckboxCardProps
  extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, "onChange"> {
  title: string;
  description?: string;
  checked?: boolean;
  onCheckedChange?: (checked: boolean) => void;
  disabled?: boolean;
  disabledHint?: string;
}

export const CheckboxCard = React.forwardRef<
  HTMLButtonElement,
  CheckboxCardProps
>(
  (
    {
      title,
      description,
      checked = false,
      onCheckedChange,
      disabled,
      disabledHint,
      className,
      ...props
    },
    ref,
  ) => {
    const handleClick = React.useCallback(() => {
      if (disabled) return;
      onCheckedChange?.(!checked);
    }, [checked, disabled, onCheckedChange]);

    return (
      <button
        ref={ref}
        type="button"
        disabled={disabled}
        onClick={handleClick}
        className={cn(
          "flex w-full items-start gap-3 rounded-[var(--radius-lg)] border px-4 py-4 text-start transition-[border-color,background-color]",
          checked
            ? "border-primary bg-primary/10"
            : "border-border-soft bg-background hover:border-primary/40",
          disabled && "cursor-not-allowed border-border-soft bg-muted/30 opacity-60",
          className,
        )}
        {...props}
      >
        <Checkbox
          checked={checked}
          disabled={disabled}
          className="mt-0.5"
          tabIndex={-1}
          aria-hidden="true"
        />
        <div className="min-w-0 flex-1 space-y-1">
          <p
            className={cn(
              "text-base font-semibold leading-tight",
              disabled && "text-muted-foreground",
            )}
          >
            {title}
          </p>
          {description ? (
            <p className="text-base leading-6 text-muted-foreground">
              {description}
            </p>
          ) : null}
          {disabled && disabledHint ? (
            <p className="text-base leading-6 text-warning">{disabledHint}</p>
          ) : null}
        </div>
      </button>
    );
  },
);
CheckboxCard.displayName = "CheckboxCard";

// packages/solid-ui/src/patterns/forms/checkbox-card/checkbox-card.tsx
import { createMemo } from "solid-js";
import { Show } from "solid-js";

import { Checkbox } from "@/components/forms/checkbox/checkbox";
import { cn } from "@/lib/cn";

export interface CheckboxCardProps {
  class?: string;
  title: string;
  description?: string;
  checked?: boolean;
  onCheckedChange?: (checked: boolean) => void;
  disabled?: boolean;
  disabledHint?: string;
}

/**
 * CheckboxCard - a selectable card row: one Checkbox plus title, description,
 * and optional disabled hint. The whole card is a label for the checkbox
 * input, so every click toggles and the keyboard interaction is native. Use
 * it for multi-select lists; do not use it for mutually exclusive choices
 * (that is a RadioGroup or OptionCard).
 */
export function CheckboxCard(props: CheckboxCardProps) {
  const className = createMemo(() =>
    cn(
      "flex w-full cursor-pointer items-start gap-3 rounded-[var(--radius-lg)] border p-4 text-start transition-[border-color,background-color]",
      props.checked
        ? "border-primary bg-primary-subtle"
        : "border-border-soft bg-background hover:border-primary/40",
      props.disabled && "cursor-not-allowed border-border-soft bg-muted/30 opacity-60",
      props.class,
    ),
  );

  return (
    <label class={className()} data-disabled={props.disabled ? "" : undefined}>
      <Checkbox
        aria-label={props.title}
        checked={props.checked}
        disabled={props.disabled}
        onChange={(next) => props.onCheckedChange?.(next === true)}
      />
      <div class="min-w-0 flex-1 space-y-1">
        <p
          class={cn(
            "text-base font-semibold leading-tight",
            props.disabled && "text-muted-foreground",
          )}
        >
          {props.title}
        </p>
        <Show when={props.description}>
          <p class="text-base leading-6 text-muted-foreground">
            {props.description}
          </p>
        </Show>
        <Show when={props.disabled && props.disabledHint}>
          <p class="text-base leading-6 text-warning">{props.disabledHint}</p>
        </Show>
      </div>
    </label>
  );
}
