// src/components/primitives/formatted-textarea.tsx
"use client";

import * as React from "react";
import { LinkSimple, ListBullets, ListNumbers, Quotes } from "@phosphor-icons/react";

import { cn } from "@/lib/utils";
import { Textarea } from "./textarea";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "./tooltip";

const toolbar = [
  { action: "bold", label: "B", title: "Bold" },
  { action: "italic", label: "I", title: "Italic" },
  { action: "strike", label: "S", title: "Strikethrough" },
  { action: "quote", label: <Quotes className="size-5" />, title: "Blockquote" },
  { action: "link", label: <LinkSimple className="size-5" />, title: "Link" },
  { action: "bulletList", label: <ListBullets className="size-5" />, title: "Bulleted list" },
  { action: "orderedList", label: <ListNumbers className="size-5" />, title: "Numbered list" },
] as const;

type ToolbarAction = (typeof toolbar)[number]["action"];

export interface FormattedTextareaProps
  extends Omit<React.ComponentProps<"textarea">, "onChange" | "value"> {
  containerClassName?: string;
  focusOnMount?: boolean;
  onChange?: (value: string) => void;
  value: string;
}

export function FormattedTextarea({
  className,
  containerClassName,
  focusOnMount = false,
  onChange,
  value,
  ...props
}: FormattedTextareaProps) {
  const textareaRef = React.useRef<HTMLTextAreaElement | null>(null);

  React.useEffect(() => {
    if (focusOnMount) {
      textareaRef.current?.focus();
    }
  }, [focusOnMount]);

  const updateSelection = React.useCallback((selectionStart: number, selectionEnd: number) => {
    requestAnimationFrame(() => {
      const textarea = textareaRef.current;
      if (!textarea) return;
      textarea.focus();
      textarea.setSelectionRange(selectionStart, selectionEnd);
    });
  }, []);

  const applyWrap = React.useCallback((
    token: string,
    fallbackText: string,
  ) => {
    const textarea = textareaRef.current;
    if (!textarea) return;
    const start = textarea.selectionStart ?? value.length;
    const end = textarea.selectionEnd ?? value.length;
    const selectedText = value.slice(start, end);
    const insertedText = `${token}${selectedText || fallbackText}${token}`;
    const nextValue = `${value.slice(0, start)}${insertedText}${value.slice(end)}`;
    onChange?.(nextValue);
    const cursorStart = start + token.length;
    const cursorEnd = cursorStart + (selectedText || fallbackText).length;
    updateSelection(cursorStart, cursorEnd);
  }, [onChange, updateSelection, value]);

  const applyLinePrefix = React.useCallback((
    getPrefix: (index: number) => string,
    fallbackText: string,
  ) => {
    const textarea = textareaRef.current;
    if (!textarea) return;
    const start = textarea.selectionStart ?? value.length;
    const end = textarea.selectionEnd ?? value.length;
    const lineStart = value.lastIndexOf("\n", Math.max(0, start - 1)) + 1;
    const nextLineBreak = value.indexOf("\n", end);
    const lineEnd = nextLineBreak === -1 ? value.length : nextLineBreak;
    const selectedBlock = value.slice(lineStart, lineEnd);
    const lines = selectedBlock.split("\n");
    const prefixedBlock = lines
      .map((line, index) => `${getPrefix(index)}${line || fallbackText}`)
      .join("\n");
    const nextValue = `${value.slice(0, lineStart)}${prefixedBlock}${value.slice(lineEnd)}`;
    onChange?.(nextValue);
    updateSelection(lineStart, lineStart + prefixedBlock.length);
  }, [onChange, updateSelection, value]);

  const applyLink = React.useCallback(() => {
    const textarea = textareaRef.current;
    if (!textarea) return;
    const start = textarea.selectionStart ?? value.length;
    const end = textarea.selectionEnd ?? value.length;
    const selectedText = value.slice(start, end) || "Link text";
    const insertedText = `[${selectedText}](https://)`;
    const nextValue = `${value.slice(0, start)}${insertedText}${value.slice(end)}`;
    onChange?.(nextValue);
    const urlStart = start + selectedText.length + 3;
    const urlEnd = urlStart + "https://".length;
    updateSelection(urlStart, urlEnd);
  }, [onChange, updateSelection, value]);

  const handleToolbarAction = React.useCallback((action: ToolbarAction) => {
    switch (action) {
      case "bold":
        applyWrap("**", "bold text");
        return;
      case "italic":
        applyWrap("*", "italic text");
        return;
      case "strike":
        applyWrap("~~", "struck text");
        return;
      case "quote":
        applyLinePrefix(() => "> ", "Quoted text");
        return;
      case "link":
        applyLink();
        return;
      case "bulletList":
        applyLinePrefix(() => "- ", "List item");
        return;
      case "orderedList":
        applyLinePrefix((index) => `${index + 1}. `, "List item");
        return;
    }
  }, [applyLinePrefix, applyLink, applyWrap]);

  return (
    <div className={cn("overflow-hidden rounded-xl border border-input bg-background shadow-sm", containerClassName)}>
      <TooltipProvider delayDuration={100}>
        <div className="flex flex-wrap items-center gap-2 border-b border-border-soft p-3">
          {toolbar.map((item) => (
            <Tooltip key={item.action}>
              <TooltipTrigger asChild>
                <button
                  aria-label={item.title}
                  className="inline-flex h-10 min-w-10 items-center justify-center rounded-full border border-transparent px-3 text-base font-semibold text-muted-foreground transition-colors hover:border-border-soft hover:bg-muted hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                  onClick={() => handleToolbarAction(item.action)}
                  type="button"
                >
                  {item.label}
                </button>
              </TooltipTrigger>
              <TooltipContent side="top">{item.title}</TooltipContent>
            </Tooltip>
          ))}
        </div>
      </TooltipProvider>
      <Textarea
        {...props}
        className={cn("min-h-32 rounded-none border-0 shadow-none focus-visible:ring-0", className)}
        dir={props.dir ?? "auto"}
        onChange={(event) => onChange?.(event.target.value)}
        ref={textareaRef}
        value={value}
      />
    </div>
  );
}

// packages/solid-ui/src/patterns/forms/formatted-textarea/formatted-textarea.tsx
import type { JSX } from "@solidjs/web";
import { For, createMemo, omit, onSettled } from "solid-js";

import { Textarea } from "@/components/forms/textarea/textarea";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/overlays/tooltip/tooltip";
import { cn } from "@/lib/cn";
import {
  IconLinkSimple,
  IconListBullets,
  IconListNumbers,
  IconQuote,
} from "./toolbar-icons";

type ToolbarAction =
  | "bold"
  | "italic"
  | "strike"
  | "quote"
  | "link"
  | "bulletList"
  | "orderedList";

const toolbar: Array<{ action: ToolbarAction; label: JSX.Element; title: string }> = [
  { action: "bold", label: "B", title: "Bold" },
  { action: "italic", label: "I", title: "Italic" },
  { action: "strike", label: "S", title: "Strikethrough" },
  { action: "quote", label: <IconQuote class="size-5" />, title: "Blockquote" },
  { action: "link", label: <IconLinkSimple class="size-5" />, title: "Link" },
  { action: "bulletList", label: <IconListBullets class="size-5" />, title: "Bulleted list" },
  { action: "orderedList", label: <IconListNumbers class="size-5" />, title: "Numbered list" },
];

const toolbarButtonClass =
  "inline-flex h-10 min-w-10 cursor-pointer items-center justify-center rounded-full border border-transparent px-3 text-base font-semibold text-muted-foreground transition-colors motion-reduce:transition-none hover:border-border-soft hover:bg-muted hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50";

export interface FormattedTextareaProps
  extends Omit<
    JSX.TextareaHTMLAttributes<HTMLTextAreaElement>,
    "class" | "onChange" | "onInput" | "value"
  > {
  class?: string;
  containerClass?: string;
  /** Focus the textarea when the pattern mounts. */
  focusOnMount?: boolean;
  /** Called with the next string value after typing or a toolbar action. */
  onChange?: (value: string) => void;
  value: string;
}

/**
 * FormattedTextarea - a controlled Textarea with a formatting toolbar that
 * inserts markdown-lite tokens around the current selection (bold, italic,
 * strikethrough, blockquote, link, bulleted and numbered lists) and previews
 * nothing. Toolbar buttons carry accessible names and tooltips. The host owns
 * the value; use it for post and comment composers backed by a local store.
 */
export function FormattedTextarea(props: FormattedTextareaProps) {
  const className = createMemo(() =>
    cn("min-h-32", props.class),
  );
  const containerClassName = createMemo(() =>
    cn(
      "overflow-hidden rounded-xl border border-input bg-background shadow-sm",
      props.containerClass,
    ),
  );
  const rest = omit(
    props,
    "class",
    "containerClass",
    "focusOnMount",
    "onChange",
    "value",
  );

  let textareaRef: HTMLTextAreaElement | undefined;

  const emitInput = (event: Event & { currentTarget: HTMLTextAreaElement }) => {
    props.onChange?.(event.currentTarget.value);
  };

  onSettled(() => {
    if (props.focusOnMount) {
      textareaRef?.focus();
    }
  });

  const updateSelection = (selectionStart: number, selectionEnd: number) => {
    requestAnimationFrame(() => {
      const textarea = textareaRef;
      if (!textarea) return;
      textarea.focus();
      textarea.setSelectionRange(selectionStart, selectionEnd);
    });
  };

  const applyWrap = (token: string, fallbackText: string) => {
    const textarea = textareaRef;
    if (!textarea) return;
    const start = textarea.selectionStart ?? props.value.length;
    const end = textarea.selectionEnd ?? props.value.length;
    const selectedText = props.value.slice(start, end);
    const insertedText = `${token}${selectedText || fallbackText}${token}`;
    const nextValue = `${props.value.slice(0, start)}${insertedText}${props.value.slice(end)}`;
    props.onChange?.(nextValue);
    const cursorStart = start + token.length;
    const cursorEnd = cursorStart + (selectedText || fallbackText).length;
    updateSelection(cursorStart, cursorEnd);
  };

  const applyLinePrefix = (
    getPrefix: (index: number) => string,
    fallbackText: string,
  ) => {
    const textarea = textareaRef;
    if (!textarea) return;
    const start = textarea.selectionStart ?? props.value.length;
    const end = textarea.selectionEnd ?? props.value.length;
    const lineStart = props.value.lastIndexOf("\n", Math.max(0, start - 1)) + 1;
    const nextLineBreak = props.value.indexOf("\n", end);
    const lineEnd = nextLineBreak === -1 ? props.value.length : nextLineBreak;
    const selectedBlock = props.value.slice(lineStart, lineEnd);
    const lines = selectedBlock.split("\n");
    const prefixedBlock = lines
      .map((line, index) => `${getPrefix(index)}${line || fallbackText}`)
      .join("\n");
    const nextValue = `${props.value.slice(0, lineStart)}${prefixedBlock}${props.value.slice(lineEnd)}`;
    props.onChange?.(nextValue);
    updateSelection(lineStart, lineStart + prefixedBlock.length);
  };

  const applyLink = () => {
    const textarea = textareaRef;
    if (!textarea) return;
    const start = textarea.selectionStart ?? props.value.length;
    const end = textarea.selectionEnd ?? props.value.length;
    const selectedText = props.value.slice(start, end) || "Link text";
    const insertedText = `[${selectedText}](https://)`;
    const nextValue = `${props.value.slice(0, start)}${insertedText}${props.value.slice(end)}`;
    props.onChange?.(nextValue);
    const urlStart = start + selectedText.length + 3;
    const urlEnd = urlStart + "https://".length;
    updateSelection(urlStart, urlEnd);
  };

  const handleToolbarAction = (action: ToolbarAction) => {
    switch (action) {
      case "bold":
        applyWrap("**", "bold text");
        return;
      case "italic":
        applyWrap("*", "italic text");
        return;
      case "strike":
        applyWrap("~~", "struck text");
        return;
      case "quote":
        applyLinePrefix(() => "> ", "Quoted text");
        return;
      case "link":
        applyLink();
        return;
      case "bulletList":
        applyLinePrefix(() => "- ", "List item");
        return;
      case "orderedList":
        applyLinePrefix((index) => `${index + 1}. `, "List item");
        return;
    }
  };

  return (
    <div class={containerClassName()}>
      <div class="flex flex-wrap items-center gap-2 border-b border-border-soft p-3">
        <For each={toolbar}>
          {(item) => (
            <Tooltip openDelay={100}>
              <TooltipTrigger
                aria-label={item.title}
                class={toolbarButtonClass}
                disabled={props.disabled}
                onClick={() => handleToolbarAction(item.action)}
              >
                {item.label}
              </TooltipTrigger>
              <TooltipContent>{item.title}</TooltipContent>
            </Tooltip>
          )}
        </For>
      </div>
      <Textarea
        {...rest}
        class={className()}
        onInput={emitInput}
        ref={(element) => {
          textareaRef = element;
        }}
        value={props.value}
        variant="flat"
      />
    </div>
  );
}
