// solid/src/features/posts/post-thread/post-thread.tsx
import { createEffect, createSignal, onCleanup, Show } from "solid-js";

import {
  Button,
  FormattedTextarea,
  Input,
  ResponsiveOptionSelect,
  Type,
  cn,
  createIsMobile,
} from "../../../design-system";
import { createUiLocale } from "../../../lib/ui-locale";
import { PostCard } from "../post-card/post-card";
import { CommentTree } from "./comment-tree";
import { ReplyAttachmentControl, revokeReplyAttachment } from "./comment-media";
import { MobileReplyScreen } from "./mobile-reply-screen";
import { ReplyContextCard } from "./reply-context-card";
import { ReplyIdentitySelect } from "./reply-identity-select";
import { replyToolbarLabels } from "./copy";
import { postThreadCommonCopy } from "./copy";
import type {
  CommentSort,
  PostThreadComment,
  PostThreadIdentityMode,
  PostThreadProps,
  PostThreadReplyAttachment,
  PostThreadReplyInput,
} from "./types";

interface MobileReplyTarget {
  kind: "root" | "comment";
  authorLabel: string;
  body: string;
  eyebrow?: string;
  metadata?: string;
  onSubmit: (input: PostThreadReplyInput) => Promise<"blocked" | "submitted" | void> | "blocked" | "submitted" | void;
}

export function PostThread(props: PostThreadProps) {
  const { locale } = createUiLocale();
  const copy = () => postThreadCommonCopy(locale());
  const items = () => props.comments ?? props.replies ?? [];
  const [showOriginalPost, setShowOriginalPost] = createSignal(false);
  const [rootReplyOpen, setRootReplyOpen] = createSignal(false);
  const [rootReplyBody, setRootReplyBody] = createSignal("");
  const [rootReplyAttachment, setRootReplyAttachment] = createSignal<PostThreadReplyAttachment | null>(null);
  const [rootReplyIdentityMode, setRootReplyIdentityMode] = createSignal<PostThreadIdentityMode>("public");
  const [rootReplyBusy, setRootReplyBusy] = createSignal(false);
  const rootReplyBusyRef = { current: false };
  let rootReplyContainerRef: HTMLDivElement | undefined;
  let rootReplyPointerActive = false;
  const isMobile = createIsMobile();

  const [mobileReplyTarget, setMobileReplyTarget] = createSignal<MobileReplyTarget | null>(null);
  const [mobileReplyBody, setMobileReplyBody] = createSignal("");
  const [mobileReplyAttachment, setMobileReplyAttachment] = createSignal<PostThreadReplyAttachment | null>(null);
  const [mobileReplyIdentityMode, setMobileReplyIdentityMode] = createSignal<PostThreadIdentityMode>("public");
  const [mobileReplyBusy, setMobileReplyBusy] = createSignal(false);
  const mobileReplyBusyRef = { current: false };

  createEffect(() => rootReplyOpen(), (open) => {
    if (open) rootReplyContainerRef?.scrollIntoView({ behavior: "smooth", block: "center" });
  });
  createEffect(() => props.post.postHref, () => {
    setShowOriginalPost(false);
  });
  createEffect(() => props.postOriginal?.postHref, () => {
    setShowOriginalPost(false);
  });
  onCleanup(() => {
    revokeReplyAttachment(rootReplyAttachment());
    revokeReplyAttachment(mobileReplyAttachment());
  });

  const activePost = () => showOriginalPost() && props.postOriginal ? props.postOriginal : props.post;
  const canToggleOriginalPost = () => Boolean(props.postOriginal);
  const hasRootReplyBlock = () => Boolean(props.rootReplyBlockedLabel && props.onRootReplyBlocked);
  const canReplyAtRoot = () => Boolean(props.onRootReplySubmit || hasRootReplyBlock() || props.rootReplyDisabled);
  const resolvedEmptyCommentsLabel = () => props.emptyCommentsLabel === "No comments yet." ? copy().noComments : props.emptyCommentsLabel ?? copy().noComments;
  const resolvedRootReplyPlaceholder = () => props.rootReplyPlaceholder || props.rootReplyActionLabel || copy().replyAction;
  const activeSort = () => props.commentSort ?? props.availableCommentSorts?.[0]?.value;
  const canSubmitRootReply = () => Boolean(rootReplyBody().trim() || rootReplyAttachment());
  const canSubmitMobileReply = () => Boolean(mobileReplyBody().trim() || mobileReplyAttachment());

  const handleRootAttachmentChange = (attachment: PostThreadReplyAttachment | null) => {
    revokeReplyAttachment(rootReplyAttachment());
    setRootReplyAttachment(attachment);
  };
  const handleMobileAttachmentChange = (attachment: PostThreadReplyAttachment | null) => {
    revokeReplyAttachment(mobileReplyAttachment());
    setMobileReplyAttachment(attachment);
  };

  const handleRootReplySubmit = async () => {
    const trimmed = rootReplyBody().trim();
    if (!canSubmitRootReply() || !props.onRootReplySubmit || rootReplyBusyRef.current) return;
    rootReplyBusyRef.current = true;
    setRootReplyBusy(true);
    try {
      const result = await props.onRootReplySubmit({
        anonymousScope: rootReplyIdentityMode() === "anonymous" ? props.replyIdentity?.anonymousScope ?? null : null,
        attachment: rootReplyAttachment(),
        authorMode: "human",
        body: trimmed,
        identityMode: rootReplyIdentityMode(),
      });
      if (result === "blocked") return;
      setRootReplyBody("");
      handleRootAttachmentChange(null);
      setRootReplyIdentityMode("public");
      setRootReplyOpen(false);
    } finally {
      rootReplyBusyRef.current = false;
      setRootReplyBusy(false);
    }
  };

  const handleMobileReplySubmit = async () => {
    const target = mobileReplyTarget();
    const trimmed = mobileReplyBody().trim();
    if (!canSubmitMobileReply() || !target || mobileReplyBusyRef.current) return;
    mobileReplyBusyRef.current = true;
    setMobileReplyBusy(true);
    try {
      const result = await target.onSubmit({
        anonymousScope: mobileReplyIdentityMode() === "anonymous" ? props.replyIdentity?.anonymousScope ?? null : null,
        attachment: mobileReplyAttachment(),
        authorMode: "human",
        body: trimmed,
        identityMode: mobileReplyIdentityMode(),
      });
      if (result === "blocked") return;
      setMobileReplyBody("");
      handleMobileAttachmentChange(null);
      setMobileReplyIdentityMode("public");
      setMobileReplyTarget(null);
    } finally {
      mobileReplyBusyRef.current = false;
      setMobileReplyBusy(false);
    }
  };

  const handleMobileReplyCancel = () => {
    setMobileReplyTarget(null);
    setMobileReplyBody("");
    handleMobileAttachmentChange(null);
    setMobileReplyIdentityMode("public");
  };

  const handleCommentReplyRequest = (comment: PostThreadComment) => {
    if (!comment.onReplySubmit) return;
    setMobileReplyTarget({
      kind: "comment",
      authorLabel: comment.authorLabel,
      body: comment.body ?? "",
      metadata: comment.timestampLabel,
      onSubmit: comment.onReplySubmit,
    });
    setMobileReplyBody("");
    handleMobileAttachmentChange(null);
    setMobileReplyIdentityMode("public");
  };

  const rootReplyBodyFromPost = () => {
    const content = props.post.content;
    if (content.type === "text") return content.body;
    if (content.type === "link" || content.type === "embed") return content.body ?? props.post.title ?? "";
    return props.post.title ?? "";
  };

  const openMobileRootReply = () => {
    if (!props.onRootReplySubmit) return;
    setMobileReplyTarget({
      kind: "root",
      authorLabel: props.post.byline.author?.label ?? props.post.byline.community?.label ?? "",
      body: rootReplyBodyFromPost(),
      eyebrow: props.post.byline.community?.label,
      metadata: props.post.byline.timestampLabel,
      onSubmit: props.onRootReplySubmit,
    });
    setMobileReplyBody("");
    handleMobileAttachmentChange(null);
    setMobileReplyIdentityMode("public");
  };

  return (
    <div class={cn("space-y-4", props.class)}>
      <div class="overflow-hidden">
        <PostCard
          {...activePost()}
          class="border-b-0"
          postHref={undefined}
          isViewingOriginal={showOriginalPost()}
          onToggleOriginal={canToggleOriginalPost() ? () => setShowOriginalPost((value) => !value) : activePost().onToggleOriginal}
        />
      </div>

      <section>
        <Show when={canReplyAtRoot() && !rootReplyOpen()}>
          <div class="px-4 pb-5">
            <Show
              when={hasRootReplyBlock()}
              fallback={(
                <Input
                  aria-label={props.rootReplyActionLabel ?? copy().replyAction}
                  class="h-12 w-full rounded-full px-4"
                  disabled={props.rootReplyDisabled}
                  onClick={() => {
                    rootReplyPointerActive = false;
                    props.onReplyIntent?.();
                    if (isMobile()) openMobileRootReply(); else setRootReplyOpen(true);
                  }}
                  onFocus={() => {
                    if (rootReplyPointerActive) return;
                    if (isMobile()) openMobileRootReply(); else setRootReplyOpen(true);
                  }}
                  onPointerCancel={() => { rootReplyPointerActive = false; }}
                  onPointerDown={() => { rootReplyPointerActive = true; }}
                  onPointerUp={() => { rootReplyPointerActive = false; }}
                  placeholder={resolvedRootReplyPlaceholder()}
                  readonly
                  type="text"
                />
              )}
            >
              <Button class="w-full" onClick={() => void props.onRootReplyBlocked?.()}>{props.rootReplyBlockedLabel}</Button>
            </Show>
          </div>
        </Show>
        <Show when={props.commentsBody}><Type as="p" variant="caption" class="px-4 pb-2">{props.commentsBody}</Type></Show>
        <Show when={rootReplyOpen()}>
          <div class="mx-4 mb-5 space-y-3" ref={(element) => { rootReplyContainerRef = element; }}>
            <FormattedTextarea
              class="min-h-28"
              focusOnMount
              onChange={setRootReplyBody}
              placeholder={resolvedRootReplyPlaceholder()}
              toolbarLabels={replyToolbarLabels(locale())}
              value={rootReplyBody()}
            />
            <ReplyAttachmentControl attachment={rootReplyAttachment()} disabled={rootReplyBusy()} onChange={handleRootAttachmentChange} />
            <div class="flex flex-wrap items-center justify-between gap-2">
              <ReplyIdentitySelect identity={props.replyIdentity} onChange={setRootReplyIdentityMode} value={rootReplyIdentityMode()} />
              <div class="flex items-center gap-2">
                <Button
                  size="sm"
                  variant="secondary"
                  onClick={() => {
                    setRootReplyOpen(false);
                    setRootReplyBody("");
                    setRootReplyIdentityMode("public");
                    handleRootAttachmentChange(null);
                  }}
                >
              {props.rootReplyCancelLabel ?? copy().cancelReply}
                </Button>
                <Button disabled={rootReplyBusy() || !canSubmitRootReply()} size="sm" onClick={() => void handleRootReplySubmit()}>
                  {props.rootReplySubmitLabel ?? copy().submitReply}
                </Button>
              </div>
            </div>
          </div>
        </Show>

        <Show when={(props.availableCommentSorts?.length ?? 0) > 0 && activeSort()}>
          <div class="flex justify-end px-4 pb-3">
            <ResponsiveOptionSelect
              ariaLabel={copy().commentSortLabel}
              class="hidden md:inline-flex"
              drawerTitle={copy().commentsHeading}
              onValueChange={(value) => props.onCommentSortChange?.(value as CommentSort)}
              options={props.availableCommentSorts ?? []}
              value={activeSort()}
            />
          </div>
        </Show>

        <Show
          when={items().length > 0}
          fallback={<Type as="div" variant="caption" class="px-4 py-5">{resolvedEmptyCommentsLabel()}</Type>}
        >
          <CommentTree
            class="px-4"
            comments={items()}
            onReplyIntent={props.onReplyIntent}
            onReplyRequest={isMobile() ? handleCommentReplyRequest : undefined}
            replyIdentity={props.replyIdentity}
          />
        </Show>
      </section>

      <Show when={mobileReplyTarget()}>
        {(target) => (
          <div class="fixed inset-0 z-50">
            <MobileReplyScreen
              body={mobileReplyBody()}
              attachment={mobileReplyAttachment()}
              busy={mobileReplyBusy()}
              context={(
                <ReplyContextCard
                  authorLabel={target().authorLabel}
                  body={target().body}
                  eyebrow={target().eyebrow}
                  metadata={target().metadata}
                />
              )}
              identityControl={(
                <ReplyIdentitySelect
                  identity={props.replyIdentity}
                  onChange={setMobileReplyIdentityMode}
                  value={mobileReplyIdentityMode()}
                />
              )}
              onAttachmentChange={handleMobileAttachmentChange}
              onBodyChange={setMobileReplyBody}
              onCancel={handleMobileReplyCancel}
              onSubmit={() => void handleMobileReplySubmit()}
              placeholder={props.rootReplyPlaceholder}
              postLabel={copy().submitReply}
              title={props.rootReplyActionLabel ?? copy().replyAction}
            />
          </div>
        )}
      </Show>
    </div>
  );
}

// src/components/compositions/posts/post-thread/post-thread.tsx
"use client";

import * as React from "react";

import { PostCard } from "@/components/compositions/posts/post-card/post-card";
import { ResponsiveOptionSelect } from "@/components/compositions/system/responsive-option-select/responsive-option-select";
import { Button } from "@/components/primitives/button";
import { FormattedTextarea } from "@/components/primitives/formatted-textarea";
import { useUiLocale } from "@/lib/ui-locale";
import { getLocaleMessages } from "@/locales";
import { cn } from "@/lib/utils";
import { useIsMobile } from "@/hooks/use-mobile";
import { CommentTree } from "./comment-tree";
import { ReplyAttachmentControl, revokeReplyAttachment } from "./comment-media";
import { MobileReplyScreen } from "./mobile-reply-screen";
import { ReplyContextCard } from "./reply-context-card";
import { ReplyIdentitySelect } from "./reply-identity-select";
import type { CommentSort, PostThreadIdentityMode, PostThreadProps, PostThreadReplyAttachment, PostThreadReplyInput } from "./post-thread.types";
import { Type } from "@/components/primitives/type";

export function PostThread({
  post,
  postOriginal,
  commentsBody,
  comments,
  replies,
  emptyCommentsLabel = "No comments yet.",
  rootReplyActionLabel,
  rootReplyPlaceholder,
  rootReplyCancelLabel,
  rootReplySubmitLabel,
  rootReplyBlockedLabel,
  rootReplyDisabled = false,
  onRootReplyBlocked,
  onReplyIntent,
  onRootReplySubmit,
  replyIdentity,
  commentSort,
  availableCommentSorts,
  onCommentSortChange,
  className,
}: PostThreadProps) {
  const { locale } = useUiLocale();
  const copy = getLocaleMessages(locale, "routes");
  const items = comments ?? replies ?? [];
  const [showOriginalPost, setShowOriginalPost] = React.useState(false);
  const [rootReplyOpen, setRootReplyOpen] = React.useState(false);
  const [rootReplyBody, setRootReplyBody] = React.useState("");
  const [rootReplyAttachment, setRootReplyAttachment] = React.useState<PostThreadReplyAttachment | null>(null);
  const [rootReplyIdentityMode, setRootReplyIdentityMode] = React.useState<PostThreadIdentityMode>("public");
  const [rootReplyBusy, setRootReplyBusy] = React.useState(false);
  const rootReplyContainerRef = React.useRef<HTMLDivElement>(null);
  const rootReplyPointerActiveRef = React.useRef(false);
  const isMobile = useIsMobile();

  const [mobileReplyTarget, setMobileReplyTarget] = React.useState<{
    kind: "root" | "comment";
    authorLabel: string;
    body: string;
    eyebrow?: string;
    metadata?: string;
    onSubmit: (input: PostThreadReplyInput) => Promise<"blocked" | "submitted" | void> | "blocked" | "submitted" | void;
  } | null>(null);
  const [mobileReplyBody, setMobileReplyBody] = React.useState("");
  const [mobileReplyAttachment, setMobileReplyAttachment] = React.useState<PostThreadReplyAttachment | null>(null);
  const [mobileReplyIdentityMode, setMobileReplyIdentityMode] = React.useState<PostThreadIdentityMode>("public");
  const [mobileReplyBusy, setMobileReplyBusy] = React.useState(false);
  const rootReplyBusyRef = React.useRef(false);
  const mobileReplyBusyRef = React.useRef(false);

  React.useEffect(() => {
    if (rootReplyOpen && rootReplyContainerRef.current) {
      rootReplyContainerRef.current.scrollIntoView({ behavior: "smooth", block: "center" });
    }
  }, [rootReplyOpen]);

  React.useEffect(() => () => revokeReplyAttachment(rootReplyAttachment), [rootReplyAttachment]);
  React.useEffect(() => () => revokeReplyAttachment(mobileReplyAttachment), [mobileReplyAttachment]);
  const activePost = showOriginalPost && postOriginal ? postOriginal : post;
  const canToggleOriginalPost = Boolean(postOriginal);
  const hasRootReplyBlock = Boolean(rootReplyBlockedLabel && onRootReplyBlocked);
  const canReplyAtRoot = Boolean(onRootReplySubmit || hasRootReplyBlock || rootReplyDisabled);
  const resolvedEmptyCommentsLabel = emptyCommentsLabel === "No comments yet." ? copy.common.noComments : emptyCommentsLabel;
  const resolvedRootReplyPlaceholder = rootReplyPlaceholder || rootReplyActionLabel || copy.common.replyAction;
  const activeSort = commentSort ?? availableCommentSorts?.[0]?.value;
  const canSubmitRootReply = Boolean(rootReplyBody.trim() || rootReplyAttachment);
  const canSubmitMobileReply = Boolean(mobileReplyBody.trim() || mobileReplyAttachment);

  React.useEffect(() => {
    setShowOriginalPost(false);
  }, [post.postHref, postOriginal?.postHref]);

  const handleRootReplySubmit = React.useCallback(async () => {
    const trimmed = rootReplyBody.trim();
    if (!canSubmitRootReply || !onRootReplySubmit || rootReplyBusyRef.current) {
      return;
    }
    rootReplyBusyRef.current = true;
    try {
      setRootReplyBusy(true);
      const result = await onRootReplySubmit({
        anonymousScope: rootReplyIdentityMode === "anonymous" ? replyIdentity?.anonymousScope ?? null : null,
        attachment: rootReplyAttachment,
        authorMode: "human",
        body: trimmed,
        identityMode: rootReplyIdentityMode,
      });
      if (result === "blocked") {
        return;
      }
      setRootReplyBody("");
      setRootReplyAttachment(null);
      setRootReplyIdentityMode("public");
      setRootReplyOpen(false);
    } finally {
      rootReplyBusyRef.current = false;
      setRootReplyBusy(false);
    }
  }, [canSubmitRootReply, onRootReplySubmit, replyIdentity?.anonymousScope, rootReplyAttachment, rootReplyBody, rootReplyIdentityMode]);

  const handleMobileReplySubmit = React.useCallback(async () => {
    const trimmed = mobileReplyBody.trim();
    if (!canSubmitMobileReply || !mobileReplyTarget || mobileReplyBusyRef.current) {
      return;
    }
    mobileReplyBusyRef.current = true;
    try {
      setMobileReplyBusy(true);
      const result = await mobileReplyTarget.onSubmit({
        anonymousScope: mobileReplyIdentityMode === "anonymous" ? replyIdentity?.anonymousScope ?? null : null,
        attachment: mobileReplyAttachment,
        authorMode: "human",
        body: trimmed,
        identityMode: mobileReplyIdentityMode,
      });
      if (result === "blocked") {
        return;
      }
      setMobileReplyBody("");
      setMobileReplyAttachment(null);
      setMobileReplyIdentityMode("public");
      setMobileReplyTarget(null);
    } finally {
      mobileReplyBusyRef.current = false;
      setMobileReplyBusy(false);
    }
  }, [canSubmitMobileReply, mobileReplyAttachment, mobileReplyBody, mobileReplyIdentityMode, mobileReplyTarget, replyIdentity?.anonymousScope]);

  const handleMobileReplyCancel = React.useCallback(() => {
    setMobileReplyTarget(null);
    setMobileReplyBody("");
    setMobileReplyAttachment(null);
    setMobileReplyIdentityMode("public");
  }, []);

  const handleRootAttachmentChange = React.useCallback((attachment: PostThreadReplyAttachment | null) => {
    setRootReplyAttachment((current) => {
      revokeReplyAttachment(current);
      return attachment;
    });
  }, []);

  const handleMobileAttachmentChange = React.useCallback((attachment: PostThreadReplyAttachment | null) => {
    setMobileReplyAttachment((current) => {
      revokeReplyAttachment(current);
      return attachment;
    });
  }, []);

  const handleCommentReplyRequest = React.useCallback((comment: import("./post-thread.types").PostThreadComment) => {
    if (!comment.onReplySubmit) return;
    setMobileReplyTarget({
      kind: "comment",
      authorLabel: comment.authorLabel,
      body: comment.body ?? "",
      metadata: comment.timestampLabel,
      onSubmit: comment.onReplySubmit,
    });
    setMobileReplyBody("");
    setMobileReplyAttachment(null);
    setMobileReplyIdentityMode("public");
  }, []);

  const openMobileRootReply = React.useCallback(() => {
    if (!onRootReplySubmit) return;
    const body = post.content.type === "text"
      ? post.content.body
      : post.content.type === "link"
        ? (post.content.body ?? post.title ?? "")
        : post.content.type === "embed"
          ? (post.content.body ?? post.title ?? "")
          : (post.title ?? "");
    setMobileReplyTarget({
      kind: "root",
      authorLabel: post.byline.author?.label ?? post.byline.community?.label ?? "",
      body,
      eyebrow: post.byline.community?.label,
      metadata: post.byline.timestampLabel,
      onSubmit: onRootReplySubmit,
    });
    setMobileReplyBody("");
    setMobileReplyAttachment(null);
    setMobileReplyIdentityMode("public");
  }, [onRootReplySubmit, post]);

  return (
    <div className={cn("space-y-4", className)}>
      <div className="overflow-hidden">
        <PostCard
          {...activePost}
          className="border-b-0"
          postHref={undefined}
          isViewingOriginal={showOriginalPost}
          onToggleOriginal={canToggleOriginalPost ? () => setShowOriginalPost((value) => !value) : activePost.onToggleOriginal}
        />
      </div>

      <section>
        {canReplyAtRoot && !rootReplyOpen ? (
          <div className="px-4 pb-5">
            {hasRootReplyBlock ? (
              <Button className="w-full" onClick={() => void onRootReplyBlocked?.()}>
                {rootReplyBlockedLabel}
              </Button>
            ) : (
              <input
                aria-label={rootReplyActionLabel ?? copy.common.replyAction}
                className="h-12 w-full rounded-full border border-border-soft bg-background px-4 text-base text-foreground shadow-sm outline-none transition-[color,box-shadow,border-color] placeholder:text-muted-foreground focus-visible:border-border focus-visible:ring-1 focus-visible:ring-border-soft"
                onClick={() => {
                  rootReplyPointerActiveRef.current = false;
                  onReplyIntent?.();
                  if (isMobile) {
                    openMobileRootReply();
                  } else {
                    setRootReplyOpen(true);
                  }
                }}
                onFocus={() => {
                  if (rootReplyPointerActiveRef.current) return;
                  if (isMobile) {
                    openMobileRootReply();
                  } else {
                    setRootReplyOpen(true);
                  }
                }}
                onPointerCancel={() => {
                  rootReplyPointerActiveRef.current = false;
                }}
                onPointerDown={() => {
                  rootReplyPointerActiveRef.current = true;
                }}
                onPointerUp={() => {
                  rootReplyPointerActiveRef.current = false;
                }}
                placeholder={resolvedRootReplyPlaceholder}
                readOnly
                disabled={rootReplyDisabled}
                type="text"
              />
            )}
          </div>
        ) : null}
        {commentsBody ? (
          <Type as="p" variant="caption" className="px-4 pb-2">{commentsBody}</Type>
        ) : null}
        {rootReplyOpen ? (
          <div ref={rootReplyContainerRef} className="mx-4 mb-5 space-y-3">
            <FormattedTextarea
              className="min-h-28"
              focusOnMount
              onChange={setRootReplyBody}
              placeholder={rootReplyPlaceholder}
              value={rootReplyBody}
            />
            <ReplyAttachmentControl
              attachment={rootReplyAttachment}
              disabled={rootReplyBusy}
              onChange={handleRootAttachmentChange}
            />
            <div className="flex flex-wrap items-center justify-between gap-2">
              <ReplyIdentitySelect
                identity={replyIdentity}
                onChange={setRootReplyIdentityMode}
                value={rootReplyIdentityMode}
              />
              <div className="flex items-center gap-2">
                <Button
                  size="sm"
                  variant="secondary"
                  onClick={() => {
                    setRootReplyOpen(false);
                    setRootReplyBody("");
                    setRootReplyIdentityMode("public");
                    handleRootAttachmentChange(null);
                  }}
                >
                  {rootReplyCancelLabel}
                </Button>
                <Button
                  disabled={rootReplyBusy || !canSubmitRootReply}
                  size="sm"
                  onClick={() => void handleRootReplySubmit()}
                >
                  {rootReplySubmitLabel}
                </Button>
              </div>
            </div>
          </div>
        ) : null}
        {availableCommentSorts && availableCommentSorts.length > 0 && activeSort ? (
          <div className="flex justify-end px-4 pb-3">
            <ResponsiveOptionSelect<CommentSort>
              ariaLabel="Sort comments"
              className="hidden md:inline-flex"
              drawerTitle={copy.common.commentsHeading}
              onValueChange={onCommentSortChange}
              options={availableCommentSorts}
              value={activeSort}
            />
          </div>
        ) : null}

        {items.length > 0 ? (
          <CommentTree
            className="px-4"
            comments={items}
            onReplyRequest={isMobile ? handleCommentReplyRequest : undefined}
            onReplyIntent={onReplyIntent}
            replyIdentity={replyIdentity}
          />
        ) : (
          <Type as="div" variant="caption" className="px-4 py-5">{resolvedEmptyCommentsLabel}</Type>
        )}
      </section>

      {mobileReplyTarget && (
        <div className="fixed inset-0 z-50">
          <MobileReplyScreen
            body={mobileReplyBody}
            attachment={mobileReplyAttachment}
            busy={mobileReplyBusy}
            context={(
              <ReplyContextCard
                authorLabel={mobileReplyTarget.authorLabel}
                body={mobileReplyTarget.body}
                eyebrow={mobileReplyTarget.eyebrow}
                metadata={mobileReplyTarget.metadata}
              />
            )}
            identityControl={(
              <ReplyIdentitySelect
                identity={replyIdentity}
                onChange={setMobileReplyIdentityMode}
                value={mobileReplyIdentityMode}
              />
            )}
            onAttachmentChange={handleMobileAttachmentChange}
            onBodyChange={setMobileReplyBody}
            onCancel={handleMobileReplyCancel}
            onSubmit={handleMobileReplySubmit}
            placeholder={rootReplyPlaceholder}
            postLabel={copy.createPost.actions.post}
            title={rootReplyActionLabel ?? copy.common.replyAction}
          />
        </div>
      )}
    </div>
  );
}
