// solid/src/features/posts/post-thread/reply-identity-select.tsx
import { createEffect, createMemo, Show } from "solid-js";

import { FormFieldLabel, ResponsiveOptionSelect, cn } from "../../../design-system";
import type { PostThreadIdentityMode, PostThreadReplyIdentity } from "./types";

export interface ReplyIdentitySelectProps {
  class?: string;
  identity?: PostThreadReplyIdentity;
  label?: string;
  onChange: (mode: PostThreadIdentityMode) => void;
  value: PostThreadIdentityMode;
}

export function ReplyIdentitySelect(props: ReplyIdentitySelectProps) {
  const label = () => props.label ?? "Reply as";
  const options = createMemo(() => [
    { value: "public", label: props.identity?.publicLabel ?? "Public" },
    ...(props.identity?.allowAnonymousIdentity === true
      ? [{ value: "anonymous", label: props.identity.anonymousLabel ?? "Anonymous" }]
      : []),
  ] as const);
  const selected = createMemo(() => options().find((option) => option.value === props.value) ?? options()[0]);

  createEffect(() => selected().value, (selectedValue) => {
    if (selectedValue !== props.value) props.onChange(selectedValue as PostThreadIdentityMode);
  });

  return (
    <Show when={props.identity?.allowAnonymousIdentity === true}>
      <div class={cn("flex min-w-0 items-center gap-2", props.class)}>
        <FormFieldLabel class="shrink-0" label={label()} />
        <ResponsiveOptionSelect
          ariaLabel={label()}
          drawerTitle={label()}
          onValueChange={(value) => props.onChange(value as PostThreadIdentityMode)}
          options={options()}
          triggerClass="h-auto min-w-0 py-1.5"
          triggerContent={<span class="truncate">{selected().label}</span>}
          value={selected().value}
        />
      </div>
    </Show>
  );
}

// src/components/compositions/posts/post-thread/reply-identity-select.tsx
"use client";

import * as React from "react";

import { ResponsiveOptionSelect } from "@/components/compositions/system/responsive-option-select/responsive-option-select";
import { FormFieldLabel } from "@/components/primitives/form-layout";
import { cn } from "@/lib/utils";
import type { PostThreadIdentityMode, PostThreadReplyIdentity } from "./post-thread.types";

interface ReplyIdentitySelectProps {
  className?: string;
  identity?: PostThreadReplyIdentity;
  label?: string;
  onChange: (mode: PostThreadIdentityMode) => void;
  value: PostThreadIdentityMode;
}

export function ReplyIdentitySelect({
  className,
  identity,
  label = "Reply as",
  onChange,
  value,
}: ReplyIdentitySelectProps) {
  const options = React.useMemo(() => [
    { value: "public" as const, label: identity?.publicLabel ?? "Public" },
    ...(identity?.allowAnonymousIdentity === true
      ? [{ value: "anonymous" as const, label: identity.anonymousLabel ?? "Anonymous" }]
      : []),
  ], [identity?.allowAnonymousIdentity, identity?.anonymousLabel, identity?.publicLabel]);
  const selected = options.find((option) => option.value === value) ?? options[0];

  React.useEffect(() => {
    if (selected.value !== value) {
      onChange(selected.value);
    }
  }, [onChange, selected.value, value]);

  if (!identity?.allowAnonymousIdentity) {
    return null;
  }

  return (
    <div className={cn("flex min-w-0 items-center gap-2", className)}>
      <FormFieldLabel className="shrink-0" label={label} />
      <ResponsiveOptionSelect<PostThreadIdentityMode>
        ariaLabel={label}
        drawerTitle={label}
        onValueChange={onChange}
        options={options}
        selectAlign="start"
        triggerClassName="h-auto min-w-0 py-1.5"
        triggerContent={<span className="truncate">{selected.label}</span>}
        value={selected.value}
      />
    </div>
  );
}
