// src/components/compositions/posts/post-thread/comment-media.tsx
"use client";

import * as React from "react";
import { Image as ImageIcon, X } from "@phosphor-icons/react";

import { Button } from "@/components/primitives/button";
import { Type } from "@/components/primitives/type";
import { cn } from "@/lib/utils";
import type { PostThreadCommentMedia, PostThreadReplyAttachment } from "./post-thread.types";

const commentImageAccept = "image/jpeg,image/png,image/webp,image/gif,image/avif";

function createReplyAttachment(file: File): PostThreadReplyAttachment {
  return {
    file,
    label: file.name || "Image",
    mimeType: file.type || null,
    previewUrl: URL.createObjectURL(file),
    sizeBytes: file.size,
  };
}

export function revokeReplyAttachment(attachment: PostThreadReplyAttachment | null | undefined) {
  if (attachment?.file && attachment.previewUrl.startsWith("blob:")) {
    URL.revokeObjectURL(attachment.previewUrl);
  }
}

export function CommentMediaGrid({
  className,
  media,
}: {
  className?: string;
  media?: PostThreadCommentMedia[];
}) {
  const items = (media ?? []).filter((item) => item.storageRef.trim());
  if (items.length === 0) return null;

  return (
    <div className={cn("mt-2 grid max-w-sm gap-2", className)}>
      {items.map((item) => (
        <div
          className="block overflow-hidden rounded-[var(--radius-lg)] border border-border-soft bg-muted"
          key={item.storageRef}
        >
          <img
            alt={item.alt ?? ""}
            className="max-h-80 w-full object-contain"
            loading="lazy"
            src={item.storageRef}
          />
        </div>
      ))}
    </div>
  );
}

export function ReplyAttachmentControl({
  attachment,
  className,
  disabled,
  onChange,
}: {
  attachment: PostThreadReplyAttachment | null;
  className?: string;
  disabled?: boolean;
  onChange: (attachment: PostThreadReplyAttachment | null) => void;
}) {
  const inputRef = React.useRef<HTMLInputElement | null>(null);

  function handleFileList(files: FileList | null) {
    const file = files?.[0] ?? null;
    if (!file) return;
    onChange(createReplyAttachment(file));
  }

  return (
    <div className={cn("space-y-2", className)}>
      {attachment ? (
        <div className="grid max-w-sm grid-cols-[72px_1fr_auto] items-center gap-3 rounded-[var(--radius-lg)] border border-border-soft bg-background p-2">
          <div className="size-[72px] overflow-hidden rounded-[var(--radius-md)] bg-muted">
            <img alt="" className="size-full object-cover" src={attachment.previewUrl} />
          </div>
          <div className="min-w-0">
            <Type as="div" variant="body-strong" className="truncate">{attachment.label}</Type>
            <Type as="div" variant="caption" className="truncate text-muted-foreground">
              {attachment.mimeType ?? "Image"}
            </Type>
          </div>
          <button
            aria-label="Remove image"
            className="grid size-10 place-items-center rounded-full text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
            disabled={disabled}
            onClick={() => onChange(null)}
            type="button"
          >
            <X className="size-5" weight="bold" />
          </button>
        </div>
      ) : null}

      <Button
        disabled={disabled}
        leadingIcon={<ImageIcon className="size-5" />}
        onClick={() => inputRef.current?.click()}
        size="sm"
        variant="secondary"
      >
        {attachment ? "Replace image" : "Add image"}
      </Button>
      <input
        accept={commentImageAccept}
        className="sr-only"
        onChange={(event) => {
          handleFileList(event.target.files);
          event.currentTarget.value = "";
        }}
        ref={inputRef}
        type="file"
      />
    </div>
  );
}

// solid/src/features/posts/post-thread/comment-media.tsx
import { createSignal, Show } from "solid-js";

import { Button, IconImage, IconX, Type, cn } from "../../../design-system";
import type { PostThreadCommentMedia, PostThreadReplyAttachment } from "./types";

const commentImageAccept = "image/jpeg,image/png,image/webp,image/gif,image/avif";

function createReplyAttachment(file: File): PostThreadReplyAttachment {
  return {
    file,
    label: file.name || "Image",
    mimeType: file.type || null,
    previewUrl: URL.createObjectURL(file),
    sizeBytes: file.size,
  };
}

export function revokeReplyAttachment(attachment: PostThreadReplyAttachment | null | undefined) {
  if (attachment?.file && attachment.previewUrl.startsWith("blob:")) {
    URL.revokeObjectURL(attachment.previewUrl);
  }
}

export function CommentMediaGrid(props: { class?: string; media?: PostThreadCommentMedia[] }) {
  const items = () => (props.media ?? []).filter((item) => item.storageRef.trim());
  return (
    <Show when={items().length > 0}>
      <div class={cn("mt-2 grid max-w-sm gap-2", props.class)}>
        {items().map((item) => (
          <div class="block overflow-hidden rounded-[var(--radius-lg)] border border-border-soft bg-muted">
            <img alt={item.alt ?? ""} class="max-h-80 w-full object-contain" loading="lazy" src={item.storageRef} />
          </div>
        ))}
      </div>
    </Show>
  );
}

export function ReplyAttachmentControl(props: {
  attachment: PostThreadReplyAttachment | null;
  class?: string;
  disabled?: boolean;
  onChange: (attachment: PostThreadReplyAttachment | null) => void;
}) {
  let inputRef: HTMLInputElement | undefined;
  const [fileRevision, setFileRevision] = createSignal(0);

  const handleFileList = (files: FileList | null) => {
    const file = files?.[0];
    if (!file) return;
    props.onChange(createReplyAttachment(file));
    setFileRevision((value) => value + 1);
  };

  return (
    <div class={cn("space-y-2", props.class)} data-file-revision={fileRevision()}>
      <Show when={props.attachment}>
        {(attachment) => (
          <div class="grid max-w-sm grid-cols-[4.5rem_1fr_auto] items-center gap-3 rounded-[var(--radius-lg)] border border-border-soft bg-background p-2">
            <div class="size-[4.5rem] overflow-hidden rounded-[var(--radius-md)] bg-muted">
              <img alt="" class="size-full object-cover" src={attachment().previewUrl} />
            </div>
            <div class="min-w-0">
              <Type as="div" variant="body-strong" class="truncate">{attachment().label}</Type>
              <Type as="div" variant="caption" class="truncate">{attachment().mimeType ?? "Image"}</Type>
            </div>
            <button
              aria-label="Remove image"
              class="grid size-10 place-items-center rounded-full text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
              disabled={props.disabled}
              onClick={() => props.onChange(null)}
              type="button"
            >
              <IconX class="size-5" />
            </button>
          </div>
        )}
      </Show>

      <Button
        disabled={props.disabled}
        leadingIcon={<IconImage class="size-5" />}
        onClick={() => inputRef?.click()}
        size="sm"
        variant="secondary"
      >
        {props.attachment ? "Replace image" : "Add image"}
      </Button>
      <input
        accept={commentImageAccept}
        aria-label="Image attachment"
        class="sr-only"
        onChange={(event) => {
          handleFileList(event.currentTarget.files);
          event.currentTarget.value = "";
        }}
        ref={(element) => { inputRef = element; }}
        type="file"
      />
    </div>
  );
}
