// src/components/primitives/sheet.tsx
"use client";

import * as React from "react";
import * as DialogPrimitive from "@radix-ui/react-dialog";
import { X } from "@phosphor-icons/react";
import { cva, type VariantProps } from "class-variance-authority";

import { cn } from "@/lib/utils";

const Sheet = DialogPrimitive.Root;
const SheetTrigger = DialogPrimitive.Trigger;
const SheetClose = DialogPrimitive.Close;
const SheetPortal = DialogPrimitive.Portal;

const SheetOverlay = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Overlay>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitive.Overlay>
>(({ className, ...props }, ref) => (
  <DialogPrimitive.Overlay
    className={cn(
      "fixed inset-0 z-50 bg-black/55 backdrop-blur-sm",
      "data-[state=open]:animate-in data-[state=closed]:animate-out",
      "data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0",
      className,
    )}
    ref={ref}
    {...props}
  />
));
SheetOverlay.displayName = DialogPrimitive.Overlay.displayName;

const sheetVariants = cva(
  "fixed z-50 gap-4 border border-border bg-card p-6 shadow-xl data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:duration-200 data-[state=open]:duration-300",
  {
    variants: {
      side: {
        top: "inset-x-0 top-0 border-b data-[state=closed]:slide-out-to-top data-[state=open]:slide-in-from-top",
        bottom:
          "inset-x-0 bottom-0 rounded-t-[var(--radius-xl)] border-t data-[state=closed]:slide-out-to-bottom data-[state=open]:slide-in-from-bottom",
        left: "inset-y-0 left-0 h-full w-3/4 border-r sm:max-w-sm data-[state=closed]:slide-out-to-left data-[state=open]:slide-in-from-left",
        right:
          "inset-y-0 right-0 h-full w-3/4 border-l sm:max-w-sm data-[state=closed]:slide-out-to-right data-[state=open]:slide-in-from-right",
      },
    },
    defaultVariants: {
      side: "right",
    },
  },
);

interface SheetContentProps
  extends React.ComponentPropsWithoutRef<typeof DialogPrimitive.Content>,
    VariantProps<typeof sheetVariants> {
  hideCloseButton?: boolean;
}

const SheetContent = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Content>,
  SheetContentProps
>(({ side = "right", className, children, hideCloseButton = false, ...props }, ref) => (
  <SheetPortal>
    <SheetOverlay />
    <DialogPrimitive.Content
      className={cn(sheetVariants({ side }), className)}
      ref={ref}
      {...props}
    >
      {children}
      {!hideCloseButton ? (
        <DialogPrimitive.Close className="absolute right-4 top-4 inline-flex h-10 w-10 items-center justify-center rounded-full text-muted-foreground transition-colors hover:bg-muted hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">
          <X aria-hidden="true" className="h-5 w-5" weight="bold" />
          <span className="sr-only">Close</span>
        </DialogPrimitive.Close>
      ) : null}
    </DialogPrimitive.Content>
  </SheetPortal>
));
SheetContent.displayName = DialogPrimitive.Content.displayName;

const SheetHeader = ({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) => (
  <div className={cn("flex flex-col space-y-2 text-center sm:text-left", className)} {...props} />
);
SheetHeader.displayName = "SheetHeader";

const SheetFooter = ({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) => (
  <div className={cn("mt-auto flex flex-col-reverse gap-2 sm:flex-row sm:justify-end", className)} {...props} />
);
SheetFooter.displayName = "SheetFooter";

const SheetTitle = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Title>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitive.Title>
>(({ className, ...props }, ref) => (
  <DialogPrimitive.Title
    className={cn("text-lg font-semibold text-foreground", className)}
    ref={ref}
    {...props}
  />
));
SheetTitle.displayName = DialogPrimitive.Title.displayName;

const SheetDescription = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Description>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitive.Description>
>(({ className, ...props }, ref) => (
  <DialogPrimitive.Description
    className={cn("text-sm leading-6 text-muted-foreground", className)}
    ref={ref}
    {...props}
  />
));
SheetDescription.displayName = DialogPrimitive.Description.displayName;

export {
  Sheet,
  SheetClose,
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetOverlay,
  SheetPortal,
  SheetTitle,
  SheetTrigger,
};

// packages/solid-ui/src/components/overlays/sheet/sheet.tsx
import {
  Dialog as KDialog,
  useDialogContext,
  type DialogContentProps as KDialogContentProps,
} from "@kobalte/core/dialog";
import type { JSX } from "@solidjs/web";
import {
  createMemo,
  omit,
  Show,
  type ParentProps,
} from "solid-js";

import {
  DialogCloseButtonLayout,
  DialogFooterLayout,
  DialogHeaderLayout,
  dialogDescriptionClass,
  dialogTitleClass,
} from "@/components/overlays/dialog-presentation";
import { cn } from "@/lib/cn";
import { cva, type VariantProps } from "@/lib/recipe";

const Sheet = KDialog;
const SheetTrigger = KDialog.Trigger;
const SheetClose = KDialog.CloseButton;

const sheetOverlayClass =
  "fixed inset-0 z-50 bg-black/55 backdrop-blur-sm transition-opacity duration-300 ease-out data-expanded:opacity-100 data-closed:opacity-0 motion-reduce:transition-none";

const sheetContentVariants = cva(
  "fixed z-50 grid gap-4 border border-border bg-card p-6 shadow-xl transition-transform duration-300 ease-[cubic-bezier(0.22,1,0.36,1)] motion-reduce:transition-none",
  {
    variants: {
      side: {
        top: "inset-x-0 top-0 rounded-b-[var(--radius-xl)] border-b data-expanded:translate-y-0 data-closed:-translate-y-full",
        bottom: "inset-x-0 bottom-0 rounded-t-[var(--radius-xl)] border-t data-expanded:translate-y-0 data-closed:translate-y-full",
        left: "inset-y-0 start-0 h-full w-3/4 border-e sm:max-w-sm data-expanded:translate-x-0 data-closed:-translate-x-full",
        right: "inset-y-0 end-0 h-full w-3/4 border-s sm:max-w-sm data-expanded:translate-x-0 data-closed:translate-x-full",
      },
    },
    defaultVariants: {
      side: "right",
    },
  },
);

export interface SheetContentProps
  extends KDialogContentProps,
    VariantProps<typeof sheetContentVariants> {
  class?: string;
  hideCloseButton?: boolean;
}

function SheetContent(props: ParentProps<SheetContentProps>) {
  const className = createMemo(() =>
    cn(sheetContentVariants({ side: props.side }), props.class),
  );
  const rest = omit(props, "class", "side", "hideCloseButton", "children");

  return (
    <KDialog.Portal>
      <KDialog.Overlay class={sheetOverlayClass} />
      <KDialog.Content class={className()} {...rest}>
        {props.children}
        <Show when={!props.hideCloseButton}>
          <DialogCloseButtonLayout part={KDialog.CloseButton} />
        </Show>
      </KDialog.Content>
    </KDialog.Portal>
  );
}

function SheetHeader(props: ParentProps<JSX.HTMLAttributes<HTMLDivElement>>) {
  return <DialogHeaderLayout {...props} class={cn("space-y-2", props.class)} />;
}

function SheetFooter(props: ParentProps<JSX.HTMLAttributes<HTMLDivElement>>) {
  return <DialogFooterLayout {...props} class={cn("mt-auto", props.class)} />;
}

function SheetTitle(props: ParentProps<Parameters<typeof KDialog.Title>[0] & { class?: string }>) {
  const className = createMemo(() => cn(dialogTitleClass, props.class));
  const rest = omit(props, "class", "children");

  return (
    <KDialog.Title class={className()} {...rest}>
      {props.children}
    </KDialog.Title>
  );
}

function SheetDescription(
  props: ParentProps<Parameters<typeof KDialog.Description>[0] & { class?: string }>,
) {
  const className = createMemo(() => cn(dialogDescriptionClass, props.class));
  const rest = omit(props, "class", "children");

  return (
    <KDialog.Description class={className()} {...rest}>
      {props.children}
    </KDialog.Description>
  );
}

export {
  Sheet,
  SheetClose,
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
  useDialogContext,
};
