// src/components/compositions/system/sidebar/sidebar.shared.tsx
"use client";

import * as React from "react";

export const SIDEBAR_COOKIE_NAME = "sidebar_state";
export const SIDEBAR_COOKIE_MAX_AGE = 60 * 60 * 24 * 7;
export const SIDEBAR_WIDTH = "22rem";
export const SIDEBAR_WIDTH_MOBILE = "min(20rem, calc(100vw - 3rem))";
export const SIDEBAR_WIDTH_MOBILE_VARIABLE = "--sidebar-width-mobile";
export const SIDEBAR_WIDTH_ICON = "4rem";
export const SIDEBAR_KEYBOARD_SHORTCUT = "b";

export type SidebarContextProps = {
  state: "expanded" | "collapsed";
  open: boolean;
  setOpen: (open: boolean) => void;
  openMobile: boolean;
  setOpenMobile: (open: boolean) => void;
  isMobile: boolean;
  toggleSidebar: () => void;
};

export const SidebarContext = React.createContext<SidebarContextProps | null>(null);
export const SidebarSideContext = React.createContext<"left" | "right">("left");

export function useSidebar() {
  const context = React.useContext(SidebarContext);
  if (!context) {
    throw new Error("useSidebar must be used within a SidebarProvider.");
  }

  return context;
}

export function useSidebarSide() {
  return React.useContext(SidebarSideContext);
}

// packages/solid-ui/src/patterns/navigation/sidebar/sidebar.shared.ts
import { createContext, useContext, type Accessor } from "solid-js";

export const SIDEBAR_WIDTH = "22rem";
export const SIDEBAR_WIDTH_MOBILE = "min(20rem, calc(100vw - 3rem))";
export const SIDEBAR_WIDTH_MOBILE_VARIABLE = "--sidebar-width-mobile";
export const SIDEBAR_WIDTH_ICON = "4rem";
export const SIDEBAR_KEYBOARD_SHORTCUT = "b";

export interface SidebarContextValue {
  state: Accessor<"expanded" | "collapsed">;
  open: Accessor<boolean>;
  setOpen: (open: boolean) => void;
  openMobile: Accessor<boolean>;
  setOpenMobile: (open: boolean) => void;
  isMobile: Accessor<boolean>;
  toggleSidebar: () => void;
}

export const SidebarContext = createContext<SidebarContextValue>();
export const SidebarSideContext = createContext<"left" | "right">("left");

export function useSidebar(): SidebarContextValue {
  const context = useContext(SidebarContext);
  if (!context) {
    throw new Error("useSidebar must be used within a SidebarProvider.");
  }
  return context;
}

export function useSidebarSide(): "left" | "right" {
  return useContext(SidebarSideContext);
}
