// solid/src/features/community/join-request-modal/community-join-request-modal.tsx
/** @jsxImportSource @solidjs/web */

import { Show, createEffect, createSignal, createUniqueId } from "solid-js";

import {
  Button,
  FormNote,
  IconCheckCircle,
  IconUsersThree,
  Modal,
  ModalContent,
  ModalDescription,
  ModalHeader,
  ModalTitle,
  Textarea,
  Type,
} from "../../../design-system";
import { getLocaleMessages, interpolateMessage } from "../../../locales";
import type { GeneratedLocaleCatalogs } from "../../../locales/generated";
import { useUiLocale } from "../../../lib/ui-locale";
import {
  joinRequestNoteCount,
  limitJoinRequestNote,
  MAX_NOTE_LENGTH,
  submitJoinRequestNote,
} from "./join-request-modal-model";

export interface CommunityJoinRequestModalProps {
  communityName: string;
  error?: string | null;
  forceMobile?: boolean;
  initialNote?: string;
  onOpenChange: (open: boolean) => void;
  onSubmit: (note: string) => Promise<void> | void;
  open: boolean;
  submitted?: boolean;
  submitting?: boolean;
}

type JoinRequestCopy = {
  [Key in keyof GeneratedLocaleCatalogs["en"]["routes"]["joinRequest"]]: string;
};

export function CommunityJoinRequestModal(props: CommunityJoinRequestModalProps) {
  const { dir, locale } = useUiLocale();
  const copy = () => getLocaleMessages(locale(), "routes").joinRequest as JoinRequestCopy;
  const resolvedDir = () => {
    if (typeof document !== "undefined" && document.documentElement.dir) {
      return document.documentElement.dir as "ltr" | "rtl" | "auto";
    }
    return dir();
  };
  const uniqueId = createUniqueId();
  const noteId = () => `community-join-request-note-${uniqueId}`;
  const [note, setNote] = createSignal(limitJoinRequestNote(props.initialNote));
  let noteInput: HTMLTextAreaElement | undefined;

  createEffect(() => {
    if (props.open) setNote(limitJoinRequestNote(props.initialNote));
  });

  const focusNote = () => {
    if (typeof document === "undefined") return;
    queueMicrotask(() => noteInput?.focus());
  };

  createEffect(() => {
    if (props.open && !props.submitted) focusNote();
  });

  const submit = (event: SubmitEvent) => {
    event.preventDefault();
    if (props.submitting) return;
    void props.onSubmit(submitJoinRequestNote(note()));
  };

  return (
    <Modal forceMobile={props.forceMobile} onOpenChange={props.onOpenChange} open={props.open}>
      <ModalContent dir={resolvedDir()}
        class="flex max-h-[90vh] flex-col overflow-y-auto px-5 pb-[calc(1.25rem+env(safe-area-inset-bottom))] pt-5 sm:max-w-2xl sm:px-8 sm:pb-8 sm:pt-8"
        mobileSide="bottom"
      >
        <div class="contents">
          <ModalHeader class="space-y-5 pe-10 text-start">
            <div class="flex items-center gap-4">
              <span aria-hidden="true" class="grid size-14 shrink-0 place-items-center rounded-full border border-border-soft bg-muted/45 text-foreground sm:size-16">
                <Show when={props.submitted} fallback={<IconUsersThree class="size-8" />}>
                  <IconCheckCircle class="size-8" />
                </Show>
              </span>
              {/* @ts-expect-error ModalTitle forwards dir to its semantic heading. */}
              <ModalTitle class="min-w-0 text-2xl leading-8 sm:text-3xl sm:leading-tight" dir="auto" leading="tight" variant="h1">
                {props.submitted ? copy().submittedTitle : copy().title}
              </ModalTitle>
            </div>
            {/* @ts-expect-error ModalDescription forwards dir to its semantic description. */}
            <ModalDescription class="w-full text-lg leading-8 text-foreground" dir="auto" leading="roomy" variant="body">
              {props.submitted ? copy().submittedDescription : copy().description}
            </ModalDescription>
          </ModalHeader>

          <Show when={props.submitted} fallback={
            <form class="mt-8 space-y-6" onSubmit={submit}>
              <div class="flex flex-col gap-2">
                <div class="flex items-center justify-between gap-4">
                  <label class="min-w-0" for={noteId()}>
                    <Type variant="body-strong">{copy().messageOptional}</Type>
                  </label>
                  <Type as="span" class="shrink-0" variant="caption">
                    {joinRequestNoteCount(note())}/{MAX_NOTE_LENGTH}
                  </Type>
                </div>
                {/* @ts-expect-error Textarea forwards the native ref but its frozen facade type omits it. */}
                <Textarea ref={noteInput} disabled={props.submitting} id={noteId()} maxLength={MAX_NOTE_LENGTH}
                  onInput={(event) => setNote(limitJoinRequestNote(event.currentTarget.value))}
                  placeholder={interpolateMessage(copy().whyJoinPlaceholder, { communityName: props.communityName })}
                  rows={5}
                  value={note()}
                />
              </div>

              <Show when={props.error}>
                <div aria-live="assertive" role="alert">
                  <FormNote tone="warning">{props.error}</FormNote>
                </div>
              </Show>

              <Button class="h-14 w-full" loading={props.submitting} type="submit">
                {copy().submit}
              </Button>
            </form>
          }>
            <div class="mt-8">
              <Button class="h-14 w-full" onClick={() => props.onOpenChange(false)}>
                {copy().done}
              </Button>
            </div>
          </Show>
        </div>
      </ModalContent>
    </Modal>
  );
}

// src/components/compositions/community-join-request-modal/community-join-request-modal.tsx
"use client";

import * as React from "react";
import { CheckCircle, UserPlus } from "@phosphor-icons/react";

import { Modal } from "@/components/compositions/modal/modal";
import {
  StandardModalContent,
  StandardModalHeader,
  StandardModalIconBadge,
} from "@/components/compositions/modal/standard-modal-layout";
import { Button } from "@/components/primitives/button";
import { FormNote } from "@/components/primitives/form-layout";
import { Textarea } from "@/components/primitives/textarea";
import { Type, typeVariants } from "@/components/primitives/type";
import { useRouteMessages } from "@/app/authenticated-routes/route-core";

export interface CommunityJoinRequestModalProps {
  communityName: string;
  error?: string | null;
  forceMobile?: boolean;
  initialNote?: string;
  onOpenChange: (open: boolean) => void;
  onSubmit: (note: string) => Promise<void> | void;
  open: boolean;
  submitted?: boolean;
  submitting?: boolean;
}

const MAX_NOTE_LENGTH = 500;

export function CommunityJoinRequestModal({
  communityName,
  error,
  forceMobile,
  initialNote = "",
  onOpenChange,
  onSubmit,
  open,
  submitted = false,
  submitting = false,
}: CommunityJoinRequestModalProps) {
  const { copy } = useRouteMessages();
  const jc = copy.joinRequest;
  const textareaId = React.useId();
  const [note, setNote] = React.useState(() => initialNote.slice(0, MAX_NOTE_LENGTH));

  React.useEffect(() => {
    if (open) {
      setNote(initialNote.slice(0, MAX_NOTE_LENGTH));
    }
  }, [initialNote, open]);

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    await onSubmit(note.trim());
  };

  return (
    <Modal forceMobile={forceMobile} onOpenChange={onOpenChange} open={open}>
      <StandardModalContent>
        <StandardModalHeader
          description={submitted
            ? jc.submittedDescription
            : jc.description}
          icon={(
            <StandardModalIconBadge>
              {submitted ? <CheckCircle className="size-8" weight="duotone" /> : <UserPlus className="size-8" weight="duotone" />}
            </StandardModalIconBadge>
          )}
          title={submitted ? jc.submittedTitle : jc.title}
        />

        {submitted ? (
          <div className="mt-8">
            <Button className="h-14 w-full" onClick={() => onOpenChange(false)}>
              {jc.done}
            </Button>
          </div>
        ) : (
          <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
            <div className="flex flex-col gap-2">
              <div className="flex items-center justify-between gap-4">
                <label className={typeVariants({ variant: "body-strong" })} htmlFor={textareaId}>
                  {jc.messageOptional}
                </label>
                <Type as="span" className="shrink-0 text-muted-foreground" variant="caption">
                  {note.length}/{MAX_NOTE_LENGTH}
                </Type>
              </div>
              <Textarea
                disabled={submitting}
                id={textareaId}
                maxLength={MAX_NOTE_LENGTH}
                onChange={(event) => setNote(event.target.value)}
                placeholder={jc.whyJoinPlaceholder.replace("{communityName}", communityName)}
                rows={5}
                value={note}
              />
            </div>

            {error ? <FormNote tone="warning">{error}</FormNote> : null}

            <Button className="h-14 w-full" loading={submitting} type="submit">
              {jc.submit}
            </Button>
          </form>
        )}
      </StandardModalContent>
    </Modal>
  );
}
