// solid/src/features/wallet/wallet-hub.tsx
/** @jsxImportSource @solidjs/web */

import { createMemo, Show } from "solid-js";

import { Card, Type } from "../../design-system";
import { buildGroupedAssets, formatTotalBalanceUsd } from "./wallet-hub-model";
import { DesktopWalletHub, MobileWalletHub } from "./wallet-hub-view";
import type { WalletHubProps } from "./wallet-hub.types";

export function WalletHub(props: WalletHubProps) {
  const groupedAssets = createMemo(() => buildGroupedAssets(props.chainSections));
  const resolvedTotalBalanceUsd = createMemo(() => props.totalBalanceUsd ?? formatTotalBalanceUsd(props.chainSections));
  const claimableWipWei = () => props.claimableWipWei ?? "0";

  return (
    <Show
      when={groupedAssets().length > 0 || props.walletAddress || props.walletActionsPending}
      fallback={
        <Card class="border-border bg-card px-5 py-10 text-muted-foreground shadow-none sm:px-6">
          No wallet connected
        </Card>
      }
    >
      <DesktopWalletHub
        chainSections={props.chainSections}
        claimLoading={props.claimLoading}
        claimableWipWei={claimableWipWei()}
        onClaim={props.onClaim}
        onReceive={props.onReceive}
        onSend={props.onSend}
        onViewActivity={props.onViewActivity}
        recentActivity={props.recentActivity}
        rewardsSummary={props.rewardsSummary}
        totalBalanceUsd={resolvedTotalBalanceUsd()}
        title={props.title ?? "Wallet"}
        variant={props.variant ?? "route"}
        walletAddress={props.walletAddress}
        walletActionsPending={props.walletActionsPending}
        walletLabel={props.walletLabel}
      />
      <MobileWalletHub
        chainSections={props.chainSections}
        claimLoading={props.claimLoading}
        claimableWipWei={claimableWipWei()}
        onClaim={props.onClaim}
        onReceive={props.onReceive}
        onSend={props.onSend}
        recentActivity={props.recentActivity}
        rewardsSummary={props.rewardsSummary}
        totalBalanceUsd={resolvedTotalBalanceUsd()}
        variant={props.variant ?? "route"}
        walletAddress={props.walletAddress}
        walletActionsPending={props.walletActionsPending}
      />
    </Show>
  );
}

// src/components/compositions/wallet/wallet-hub/wallet-hub.tsx
"use client";

import * as React from "react";

import { Card } from "@/components/primitives/card";
import { useUiLocale } from "@/lib/ui-locale";
import { getLocaleMessages } from "@/locales";
import { buildGroupedAssets, formatTotalBalanceUsd } from "./wallet-hub-model";
export { buildGroupedAssets, formatTotalBalanceUsd } from "./wallet-hub-model";
export { MobileWalletHub } from "./wallet-hub-view";
import { DesktopWalletHub, MobileWalletHub } from "./wallet-hub-view";
import type { WalletHubProps } from "./wallet-hub.types";

export function WalletHub({
  variant = "route",
  title,
  walletLabel,
  walletAddress,
  walletActionsPending = false,
  totalBalanceUsd,
  claimableWipWei = "0",
  claimLoading = false,
  onClaim,
  onReceive,
  onSend,
  onViewActivity,
  rewardsSummary,
  chainSections,
  recentActivity,
}: WalletHubProps) {
  const { locale } = useUiLocale();
  const copy = getLocaleMessages(locale, "routes").wallet;
  const groupedAssets = React.useMemo(() => buildGroupedAssets(chainSections), [chainSections]);
  const resolvedTotalBalanceUsd = totalBalanceUsd ?? formatTotalBalanceUsd(chainSections);

  if (groupedAssets.length === 0 && !walletAddress && !walletActionsPending) {
    return (
      <Card className="border-border bg-card px-5 py-10 text-muted-foreground shadow-none sm:px-6">
        {copy.noWalletConnected}
      </Card>
    );
  }

  return (
    <>
      <DesktopWalletHub
        chainSections={chainSections}
        claimLoading={claimLoading}
        claimableWipWei={claimableWipWei}
        onClaim={onClaim}
        onReceive={onReceive}
        onSend={onSend}
        onViewActivity={onViewActivity}
        recentActivity={recentActivity}
        rewardsSummary={rewardsSummary}
        totalBalanceUsd={resolvedTotalBalanceUsd}
        title={title ?? copy.title}
        variant={variant}
        walletAddress={walletAddress}
        walletActionsPending={walletActionsPending}
        walletLabel={walletLabel}
      />
      <MobileWalletHub
        chainSections={chainSections}
        claimLoading={claimLoading}
        claimableWipWei={claimableWipWei}
        onClaim={onClaim}
        onReceive={onReceive}
        onSend={onSend}
        recentActivity={recentActivity}
        rewardsSummary={rewardsSummary}
        totalBalanceUsd={resolvedTotalBalanceUsd}
        variant={variant}
        walletAddress={walletAddress}
        walletActionsPending={walletActionsPending}
      />
    </>
  );
}
