// solid/src/features/posts/post-composer/post-composer.tsx
import { Show } from "solid-js";
import { createPostComposerController } from "./controller";
import type { PostComposerProps } from "./types";
import { Card, createIsMobile, Type } from "../../../design-system";
import { cn } from "../../../design-system";
import { ShellPill } from "./fields";
import { PostComposerDetailsStep } from "./details-step";
import { PostComposerPublishSettings } from "./publish-settings";
import { PostComposerSettingsHub } from "./settings-hub";
import { PostComposerDesktopFooter, PostComposerMobileSubmitBar } from "./submit-actions";
import { PostComposerWriteStep } from "./write-step";

export function PostComposer(props: PostComposerProps) {
  const controller = createPostComposerController(props, { isMobile: createIsMobile() });
  const heading = () => controller.step.isWriteStep
    ? "Create post"
    : controller.step.isDetailsStep
      ? "Post details"
      : controller.step.isSettingsStep
        ? "Post settings"
        : "Post preview";

  const content = () => controller.step.isWriteStep
    ? <PostComposerWriteStep controller={controller} />
    : controller.step.isDetailsStep
      ? <PostComposerDetailsStep controller={controller} />
      : controller.step.isSettingsStep
        ? <PostComposerSettingsHub controller={controller} />
        : <PostComposerPublishSettings controller={controller} />;

  return (
    <div class={cn("w-full space-y-4 pt-2", controller.isMobile() && "space-y-7 pt-0")}>
      <ShowMobileHeader controller={controller} heading={heading()} />
      <ShowDesktopHeader controller={controller} heading={heading()} />
      <Show when={!controller.isMobile()} fallback={content()}>
        <Card class="overflow-hidden bg-card shadow-none">
          {content()}
          <PostComposerDesktopFooter controller={controller} />
        </Card>
      </Show>
      <PostComposerMobileSubmitBar controller={controller} />
    </div>
  );
}

function ShowMobileHeader(props: { controller: ReturnType<typeof createPostComposerController>; heading: string }) {
  return (
    <Show when={props.controller.isMobile()}>
      <div class="flex w-full flex-wrap items-center justify-between gap-3">
        <Type as="h1" variant="h2" class="w-full">{props.heading}</Type>
        <ShellPill
          avatarSrc={props.controller.community.avatarSrc}
          class="w-full"
          communities={props.controller.community.items}
          emptyLabel={props.controller.community.emptyLabel}
          onSelectCommunity={props.controller.community.onSelect}
          pickerSearchPlaceholder={props.controller.community.pickerSearchPlaceholder}
          pickerTitle={props.controller.community.pickerTitle}
        >
          {props.controller.community.name}
        </ShellPill>
      </div>
    </Show>
  );
}

function ShowDesktopHeader(props: { controller: ReturnType<typeof createPostComposerController>; heading: string }) {
  return (
    <Show when={!props.controller.isMobile()}>
      <div class="flex items-center justify-between gap-3">
        <Type as="h1" variant="h2">{props.heading}</Type>
        <Show when={props.controller.step.isWriteStep}>
          <ShellPill
            avatarSrc={props.controller.community.avatarSrc}
            communities={props.controller.community.items}
            emptyLabel={props.controller.community.emptyLabel}
            onSelectCommunity={props.controller.community.onSelect}
            pickerSearchPlaceholder={props.controller.community.pickerSearchPlaceholder}
            pickerTitle={props.controller.community.pickerTitle}
          >
            {props.controller.community.name}
          </ShellPill>
        </Show>
      </div>
    </Show>
  );
}

// src/components/compositions/posts/post-composer/post-composer.tsx
"use client";

import { Card } from "@/components/primitives/card";
import { Type } from "@/components/primitives/type";

import type { PostComposerProps } from "./post-composer.types";
import { ShellPill } from "./post-composer-fields";
import { PostComposerDetailsStep } from "./post-composer-details-step";
import { PostComposerPublishSettings } from "./post-composer-publish-settings";
import { PostComposerSettingsHub } from "./post-composer-settings-hub";
import {
  PostComposerDesktopFooter,
  PostComposerMobileSubmitBar,
} from "./post-composer-submit-actions";
import { PostComposerWriteStep } from "./post-composer-write-step";
import { usePostComposerController } from "./use-post-composer-controller";

export function PostComposer(props: PostComposerProps) {
  const controller = usePostComposerController(props);
  const { community, isMobile, step } = controller;

  if (isMobile) {
    return (
      <div className="w-full space-y-7">
        {step.isWriteStep ? (
          <>
            <div className="flex w-full flex-wrap items-center justify-between gap-3">
              <ShellPill
                avatarSrc={community.avatarSrc}
                className="w-full"
                communities={community.items}
                emptyLabel={community.emptyLabel}
                onSelectCommunity={community.onSelect}
                pickerSearchPlaceholder={community.pickerSearchPlaceholder}
                pickerTitle={community.pickerTitle}
              >
                {community.name}
              </ShellPill>
            </div>

            <PostComposerWriteStep controller={controller} />
          </>
        ) : step.isDetailsStep ? (
          <PostComposerDetailsStep controller={controller} />
        ) : step.isSettingsStep ? (
          <PostComposerSettingsHub controller={controller} />
        ) : (
          <PostComposerPublishSettings controller={controller} />
        )}
        {step.isPublishStep ? <PostComposerMobileSubmitBar controller={controller} /> : null}
      </div>
    );
  }

  return (
    <div className="w-full space-y-4 pt-2">
      <div className="flex items-center justify-between gap-3">
        <Type as="h1" variant="h2">
          {step.isWriteStep
            ? "Create post"
            : step.isDetailsStep
              ? "Post details"
            : step.isSettingsStep
              ? "Post settings"
                : "Post preview"}
        </Type>
        {step.isWriteStep ? (
          <ShellPill
            avatarSrc={community.avatarSrc}
            communities={community.items}
            emptyLabel={community.emptyLabel}
            onSelectCommunity={community.onSelect}
            pickerSearchPlaceholder={community.pickerSearchPlaceholder}
            pickerTitle={community.pickerTitle}
          >
            {community.name}
          </ShellPill>
        ) : null}
      </div>

      <Card className="overflow-hidden bg-card shadow-none">
        {step.isWriteStep ? (
          <PostComposerWriteStep controller={controller} />
        ) : step.isDetailsStep ? (
          <PostComposerDetailsStep controller={controller} />
        ) : step.isSettingsStep ? (
          <PostComposerSettingsHub controller={controller} />
        ) : (
          <PostComposerPublishSettings controller={controller} />
        )}
        <PostComposerDesktopFooter controller={controller} />
      </Card>
    </div>
  );
}
