// src/components/compositions/profiles/song-item/song-item.tsx
import * as React from "react";
import { MusicNote } from "@phosphor-icons/react";

import {
  Item,
  ItemActions,
  ItemContent,
  ItemDescription,
  ItemMedia,
  ItemTitle,
} from "@/components/primitives/item";
import { cn } from "@/lib/utils";
import type { SongItemProps } from "./song-item.types";
import { Type } from "@/components/primitives/type";

function SongItemMeta({ items }: { items: NonNullable<SongItemProps["metaItems"]> }) {
  return (
    <Type as="div" variant="caption" className="flex flex-wrap items-center gap-x-2 gap-y-1 ">
      {items.map((item, index) => (
        <React.Fragment key={item.href ?? item.label}>
          {index > 0 ? <span aria-hidden>·</span> : null}
          {item.href ? (
            <a className="font-medium text-foreground hover:underline" href={item.href}>
              {item.label}
            </a>
          ) : (
            <span>{item.label}</span>
          )}
        </React.Fragment>
      ))}
    </Type>
  );
}

export function SongItem({
  artistName,
  artworkAlt,
  artworkSrc,
  className,
  metaItems,
  title,
  titleHref,
  trailingContent,
  ...props
}: SongItemProps) {
  return (
    <Item className={cn("gap-4 px-5 py-4", className)} {...props}>
      <ItemMedia className="size-16 overflow-hidden rounded-[var(--radius-lg)] bg-muted" variant="image">
        {artworkSrc ? (
          <img
            alt={artworkAlt ?? title}
            className="size-full object-cover"
            src={artworkSrc}
          />
        ) : (
          <MusicNote className="size-5 text-muted-foreground" />
        )}
      </ItemMedia>
      <ItemContent className="gap-2">
        {titleHref ? (
          <a className="w-fit hover:underline" href={titleHref}>
            <ItemTitle>{title}</ItemTitle>
          </a>
        ) : (
          <ItemTitle>{title}</ItemTitle>
        )}
        {artistName ? (
          <ItemDescription className="line-clamp-1">{artistName}</ItemDescription>
        ) : null}
        {metaItems?.length ? <SongItemMeta items={metaItems} /> : null}
      </ItemContent>
      {trailingContent ? <ItemActions>{trailingContent}</ItemActions> : null}
    </Item>
  );
}

// solid/src/features/profiles/song-item/song-item.tsx
/** @jsxImportSource @solidjs/web */

import type { JSX } from "@solidjs/web";
import { For, Show } from "solid-js";

import {
  IconMusicNote,
  Type,
  cn,
} from "../../../design-system";

export interface SongItemMetaItem {
  label: string;
  href?: string;
}

export interface SongItemProps {
  title: string;
  titleHref?: string;
  artistName?: string;
  artworkSrc?: string;
  artworkAlt?: string;
  metaItems?: SongItemMetaItem[];
  trailingContent?: JSX.Element;
  class?: string;
}

export function SongItem(props: SongItemProps) {
  const artworkSrc = () => props.artworkSrc?.trim() || "";

  return (
    <article class={cn("flex min-w-0 items-center gap-4 px-5 py-4", props.class)}>
      <div class="grid size-16 shrink-0 place-items-center overflow-hidden rounded-[var(--radius-lg)] bg-muted">
        <Show
          when={artworkSrc()}
          fallback={<IconMusicNote aria-hidden="true" class="size-5 text-muted-foreground" />}
        >
          {(src) => <img alt={props.artworkAlt ?? `${props.title} artwork`} class="size-full object-cover" src={src()} />}
        </Show>
      </div>

      <div class="flex min-w-0 flex-1 flex-col gap-2">
        <Show
          when={props.titleHref}
          fallback={<Type as="div" class="truncate" variant="body-strong">{props.title}</Type>}
        >
          {(href) => <a class="block truncate hover:underline" href={href()}><Type as="span" variant="body-strong">{props.title}</Type></a>}
        </Show>
        <Show when={props.artistName}>
          {(artist) => <Type as="div" class="truncate text-muted-foreground" variant="caption">{artist()}</Type>}
        </Show>
        <Show when={props.metaItems?.length}>
          <Type as="div" class="flex flex-wrap gap-x-2 gap-y-1 text-muted-foreground" variant="caption">
            <For each={props.metaItems}>
              {(item, index) => (
                <>
                  <Show when={index() > 0}><span aria-hidden="true">·</span></Show>
                  <Show when={item.href} fallback={<span>{item.label}</span>}>
                    {(href) => <a class="hover:underline" href={href()}>{item.label}</a>}
                  </Show>
                </>
              )}
            </For>
          </Type>
        </Show>
      </div>

      <Show when={props.trailingContent}>
        <div class="shrink-0">{props.trailingContent}</div>
      </Show>
    </article>
  );
}
