// src/components/compositions/community/membership-requests-page/community-membership-requests-page.tsx
"use client";

import type { MembershipRequestSummary } from "@pirate/api-contracts";

import { Avatar } from "@/components/primitives/avatar";
import { Button } from "@/components/primitives/button";
import { Card } from "@/components/primitives/card";
import { Separator } from "@/components/primitives/separator";
import { Type } from "@/components/primitives/type";
import { buildPublicProfilePath } from "@/lib/profile-routing";

export interface CommunityMembershipRequestsPageProps {
  loading?: boolean;
  onApprove: (request: MembershipRequestSummary) => void;
  onReject: (request: MembershipRequestSummary) => void;
  processingRequestId?: string | null;
  requests: MembershipRequestSummary[];
}

function formatDate(value: string | number): string {
  const date = typeof value === "number" ? new Date(value * 1000) : new Date(value);
  return date.toLocaleDateString(undefined, {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}

function getApplicantLabel(request: MembershipRequestSummary): string {
  return request.applicant_handle?.trim() || "Member";
}

function MembershipRequestApplicantContent({
  applicantLabel,
  request,
}: {
  applicantLabel: string;
  request: MembershipRequestSummary;
}) {
  return (
    <>
      <Avatar fallback={applicantLabel} fallbackSeed={request.applicant_user} size="md" src={request.applicant_avatar_ref ?? undefined} />
      <div className="min-w-0 flex-1">
        <div className="flex min-w-0 flex-wrap items-baseline gap-x-2 gap-y-1">
          <Type as="span" className="min-w-0 truncate" variant="body-strong">
            {applicantLabel}
          </Type>
          <Type as="span" className="text-muted-foreground" variant="caption">
            {formatDate(request.created)}
          </Type>
        </div>
        {request.note?.trim() ? (
          <Type as="p" className="mt-2 whitespace-pre-wrap text-muted-foreground" variant="body">
            {request.note}
          </Type>
        ) : (
          <Type as="p" className="mt-2 text-muted-foreground" variant="body">
            No message.
          </Type>
        )}
      </div>
    </>
  );
}

export function CommunityMembershipRequestsPage({
  loading = false,
  onApprove,
  onReject,
  processingRequestId,
  requests,
}: CommunityMembershipRequestsPageProps) {
  return (
    <section className="flex min-w-0 flex-col gap-6">
      <div className="space-y-2">
        <Type as="h1" variant="h2">Requests</Type>
        <Type as="p" className="max-w-2xl text-muted-foreground" variant="body">
          Review who can join this community.
        </Type>
      </div>

      <Card className="overflow-hidden">
        {loading ? (
          <div className="px-5 py-8 text-center">
            <Type as="p" className="text-muted-foreground" variant="body">Loading requests&hellip;</Type>
          </div>
        ) : requests.length === 0 ? (
          <div className="px-5 py-8 text-center">
            <Type as="p" className="text-muted-foreground" variant="body">No pending requests.</Type>
          </div>
        ) : (
          <div>
            {requests.map((request, index) => {
              const applicantLabel = getApplicantLabel(request);
              const profileHref = request.applicant_handle ? buildPublicProfilePath(request.applicant_handle) : null;
              const processing = processingRequestId === request.id;

              return (
                <div key={request.id}>
                  {index > 0 ? <Separator /> : null}
                  <div className="flex flex-col gap-4 p-5 md:flex-row md:items-start">
                    {profileHref ? (
                      <a
                        className="flex min-w-0 flex-1 items-start gap-3"
                        href={profileHref}
                      >
                        <MembershipRequestApplicantContent applicantLabel={applicantLabel} request={request} />
                      </a>
                    ) : (
                      <div className="flex min-w-0 flex-1 items-start gap-3">
                        <MembershipRequestApplicantContent applicantLabel={applicantLabel} request={request} />
                      </div>
                    )}

                    <div className="flex shrink-0 gap-2 md:justify-end">
                      <Button
                        disabled={processing}
                        loading={processing}
                        onClick={() => onApprove(request)}
                      >
                        Approve
                      </Button>
                      <Button
                        disabled={processing}
                        onClick={() => onReject(request)}
                        variant="secondary"
                      >
                        Reject
                      </Button>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </Card>
    </section>
  );
}

// solid/src/features/community/membership-requests-page/community-membership-requests-page.tsx
import { For, Show } from "solid-js";

import {
  Avatar,
  Button,
  Card,
  Separator,
  Type,
} from "../../../design-system";
import { resolveLocaleLanguageTag } from "../../../lib/ui-locale-core";
import { useUiLocale } from "../../../lib/ui-locale";
import {
  buildPublicProfilePath,
  formatMembershipRequestDate,
  getApplicantLabel,
  isMembershipRequestProcessing,
  type MembershipRequestSummary,
} from "./membership-requests-page-model";

export type { MembershipRequestSummary } from "./membership-requests-page-model";

export interface CommunityMembershipRequestsPageProps {
  loading?: boolean;
  onApprove: (request: MembershipRequestSummary) => void;
  onReject: (request: MembershipRequestSummary) => void;
  processingRequestId?: string | null;
  requests: MembershipRequestSummary[];
}

function MembershipRequestApplicantContent(props: {
  applicantLabel: string;
  dateLabel: string;
  request: MembershipRequestSummary;
}) {
  const request = () => props.request;
  const applicantLabel = () => props.applicantLabel;
  const dateLabel = () => props.dateLabel;

  return (
    <>
      <Avatar
        fallback={applicantLabel()}
        fallbackSeed={request().applicant_user}
        size="md"
        src={request().applicant_avatar_ref ?? undefined}
      />
      <div class="min-w-0 flex-1">
        <div class="flex min-w-0 flex-wrap items-baseline gap-x-2 gap-y-1">
          <Type as="span" class="min-w-0 truncate" variant="body-strong">
            {applicantLabel()}
          </Type>
          <Type as="span" class="text-muted-foreground" variant="caption">
            {dateLabel()}
          </Type>
        </div>
        <Show
          when={request().note?.trim()}
          fallback={
            <Type as="p" class="mt-2 text-muted-foreground" variant="body">
              No message.
            </Type>
          }
        >
          <Type as="p" class="mt-2 whitespace-pre-wrap text-muted-foreground" variant="body">
            {request().note}
          </Type>
        </Show>
      </div>
    </>
  );
}

function MembershipRequestRow(props: {
  dateLocale: string;
  onApprove: (request: MembershipRequestSummary) => void;
  onReject: (request: MembershipRequestSummary) => void;
  processingRequestId?: string | null;
  request: MembershipRequestSummary;
}) {
  const request = () => props.request;
  const applicantLabel = () => getApplicantLabel(request());
  const processing = () => isMembershipRequestProcessing(request().id, props.processingRequestId);
  const profileHref = () => {
    const applicantHandle = request().applicant_handle;
    return applicantHandle ? buildPublicProfilePath(applicantHandle) : null;
  };

  return (
    <div data-membership-request-id={request().id} data-testid={`membership-request-${request().id}`}>
      <div class="flex flex-col gap-4 p-5 md:flex-row md:items-start">
        <Show
          when={profileHref()}
          fallback={
            <div class="flex min-w-0 flex-1 items-start gap-3">
              <MembershipRequestApplicantContent
                applicantLabel={applicantLabel()}
                dateLabel={formatMembershipRequestDate(request().created, props.dateLocale)}
                request={request()}
              />
            </div>
          }
        >
          {(href) => (
            <a
              class="flex min-w-0 flex-1 items-start gap-3"
              href={href()}
            >
              <MembershipRequestApplicantContent
                applicantLabel={applicantLabel()}
                dateLabel={formatMembershipRequestDate(request().created, props.dateLocale)}
                request={request()}
              />
            </a>
          )}
        </Show>

        <div class="flex shrink-0 gap-2 md:justify-end">
          <Button
            disabled={processing()}
            loading={processing()}
            onClick={() => props.onApprove(request())}
          >
            Approve
          </Button>
          <Button
            disabled={processing()}
            onClick={() => props.onReject(request())}
            variant="secondary"
          >
            Reject
          </Button>
        </div>
      </div>
    </div>
  );
}

export function CommunityMembershipRequestsPage(props: CommunityMembershipRequestsPageProps) {
  const { locale } = useUiLocale();
  const loading = () => props.loading ?? false;
  const requests = () => props.requests;
  const processingRequestId = () => props.processingRequestId;
  const dateLocale = () => resolveLocaleLanguageTag(locale());

  return (
    <section class="flex min-w-0 flex-col gap-6" data-membership-requests-page>
      <div class="space-y-2">
        <Type as="h1" variant="h2">Requests</Type>
        <Type as="p" class="max-w-2xl text-muted-foreground" variant="body">
          Review who can join this community.
        </Type>
      </div>

      <Card class="overflow-hidden">
        <Show
          when={!loading()}
          fallback={
            <div class="px-5 py-8 text-center">
              <Type as="p" class="text-muted-foreground" variant="body">Loading requests&hellip;</Type>
            </div>
          }
        >
          <Show
            when={requests().length > 0}
            fallback={
              <div class="px-5 py-8 text-center">
                <Type as="p" class="text-muted-foreground" variant="body">No pending requests.</Type>
              </div>
            }
          >
            <div>
              <For each={requests()}>
                {(request, index) => (
                  <div>
                    <Show when={index() > 0}>
                      <Separator />
                    </Show>
                    <MembershipRequestRow
                      dateLocale={dateLocale()}
                      onApprove={props.onApprove}
                      onReject={props.onReject}
                      processingRequestId={processingRequestId()}
                      request={request}
                    />
                  </div>
                )}
              </For>
            </div>
          </Show>
        </Show>
      </Card>
    </section>
  );
}
