// packages/solid-ui/src/components/data-display/avatar/avatar.tsx
import type { JSX } from "@solidjs/web";
import {
  createMemo,
  createSignal,
  Show,
  untrack,
} from "solid-js";

import { Skeleton } from "@/components/feedback/skeleton/skeleton";
import { cn } from "@/lib/cn";

export type AvatarSize = "xs" | "sm" | "md" | "lg";

const sizeClasses: Record<AvatarSize, string> = {
  xs: "size-6",
  sm: "size-9 text-base",
  md: "size-12 text-base",
  lg: "size-14 text-base",
};

export function isRenderableImageSrc(src: string): boolean {
  const trimmed = src.trim();
  const normalized = trimmed.toLowerCase();

  if (!trimmed) {
    return false;
  }

  if (
    normalized.startsWith("data:")
    || normalized.startsWith("blob:")
    || normalized.startsWith("http://")
    || normalized.startsWith("https://")
    || normalized.startsWith("/")
  ) {
    return true;
  }

  return /^[a-z0-9][a-z0-9+.-]*\.[a-z0-9]{2,6}(?:[/?#]|$)/i.test(trimmed);
}

export function isRetryableImageSrc(src: string): boolean {
  const normalized = src.trim().toLowerCase();
  return isRenderableImageSrc(normalized) && !normalized.startsWith("data:");
}

export function buildRetriedImageSrc(src: string): string {
  const trimmed = src.trim();
  if (!trimmed) {
    return trimmed;
  }

  try {
    const url = typeof window === "undefined"
      ? new URL(trimmed, "http://localhost")
      : new URL(trimmed, window.location.href);
    url.searchParams.set("_img_retry", Date.now().toString());
    return url.toString();
  } catch {
    const separator = trimmed.includes("?") ? "&" : "?";
    return `${trimmed}${separator}_img_retry=${Date.now()}`;
  }
}

function buildInitials(seed: string): string {
  const parts = seed.trim().split(/\s+/).filter(Boolean);
  if (parts.length === 0) {
    return "";
  }
  const first = parts[0].charAt(0).toUpperCase();
  const last = parts.length > 1 ? parts[parts.length - 1].charAt(0).toUpperCase() : "";
  return `${first}${last}`;
}

export interface AvatarProps {
  class?: string;
  /** Accessible label and initials source for the generated fallback. */
  fallback: string;
  fallbackIcon?: JSX.Element;
  /** Alternate initials seed; defaults to `fallback`. */
  fallbackSeed?: string;
  /** Alternate image shown after the primary fails. */
  fallbackSrc?: string;
  size?: AvatarSize;
  src?: string;
}

interface RetryRecord {
  primary: string;
  url: string;
}

const MAX_FAILURE_KEYS = 30;

export function Avatar(props: AvatarProps) {
  const primarySrc = createMemo(() => {
    const trimmed = props.src?.trim() || "";
    return isRenderableImageSrc(trimmed) ? trimmed : "";
  });
  const alternateSrc = createMemo(() => {
    const trimmed = props.fallbackSrc?.trim() || "";
    return isRenderableImageSrc(trimmed) ? trimmed : "";
  });

  const [retry, setRetry] = createSignal<RetryRecord | null>(null);
  const [failed, setFailed] = createSignal<Set<string>>(new Set());

  const activeRetry = createMemo(() => {
    const current = retry();
    return current && current.primary === primarySrc() ? current.url : null;
  });

  const currentSrc = createMemo(() => {
    const failures = failed();
    if (primarySrc() && !failures.has(primarySrc()) && activeRetry() == null) return primarySrc();
    if (activeRetry() && !failures.has(activeRetry()!)) return activeRetry()!;
    if (alternateSrc() && !failures.has(alternateSrc())) return alternateSrc();
    return "";
  });

  const canRenderImage = createMemo(() => currentSrc() !== "");
  const initials = createMemo(() => buildInitials(props.fallbackSeed || props.fallback));

  const handleError = () => {
    untrack(() => {
      const current = currentSrc();
      const primary = primarySrc();
      const retriedUrl = activeRetry();

      if (
        primary
        && current === primary
        && retriedUrl == null
        && isRetryableImageSrc(primary)
      ) {
        setRetry({ primary, url: buildRetriedImageSrc(primary) });
        return;
      }

      setFailed((prev) => {
        const next = prev.size >= MAX_FAILURE_KEYS ? new Set<string>() : new Set(prev);
        if (current === primary) next.add(primary);
        if (retriedUrl) next.add(retriedUrl);
        next.add(current);
        return next;
      });
    });
  };

  const className = createMemo(() =>
    cn(
      "grid shrink-0 place-items-center overflow-hidden rounded-full border border-border-soft bg-surface-skeleton font-semibold text-foreground",
      sizeClasses[props.size ?? "md"],
      props.class,
    ),
  );
  const fallbackRole = createMemo(() =>
    !canRenderImage() && (initials() || props.fallbackIcon) ? "img" : undefined,
  );

  return (
    <div
      aria-label={fallbackRole() ? props.fallback : undefined}
      class={className()}
      role={fallbackRole()}
    >
      <Show
        when={canRenderImage()}
        fallback={
          <Show
            when={props.fallbackIcon}
            fallback={
              <Show when={initials()} fallback={<Skeleton aria-hidden="true" class="size-full rounded-full" />}>
                <span aria-hidden="true">{initials()}</span>
              </Show>
            }
          >
            {props.fallbackIcon}
          </Show>
        }
      >
        <img
          alt={props.fallback}
          class="size-full rounded-full object-cover"
          onError={handleError}
          src={currentSrc()}
        />
      </Show>
    </div>
  );
}

// src/components/primitives/avatar.tsx
"use client";

import * as React from "react";

import { buildDefaultAvatarSrc } from "@/lib/default-avatar";
import { logger } from "@/lib/logger";
import { cn } from "@/lib/utils";
import { Skeleton } from "./skeleton";

type AvatarSize = "xs" | "sm" | "md" | "lg";

const sizeClasses: Record<AvatarSize, string> = {
  xs: "h-6 w-6",
  sm: "h-9 w-9 text-base",
  md: "h-12 w-12 text-base",
  lg: "h-14 w-14 text-base",
};

export function isRetryableImageSrc(src: string): boolean {
  const normalized = src.trim().toLowerCase();
  return isRenderableImageSrc(normalized) && !normalized.startsWith("data:");
}

export function isRenderableImageSrc(src: string): boolean {
  const trimmed = src.trim();
  const normalized = trimmed.toLowerCase();

  if (!trimmed) {
    return false;
  }

  if (
    normalized.startsWith("data:")
    || normalized.startsWith("blob:")
    || normalized.startsWith("http://")
    || normalized.startsWith("https://")
    || normalized.startsWith("/")
    || normalized.startsWith("./")
    || normalized.startsWith("../")
  ) {
    return true;
  }

  return !/^[a-z][a-z0-9+.-]*:/iu.test(trimmed);
}

export function buildRetriedImageSrc(src: string): string {
  const trimmed = src.trim();
  if (!trimmed) {
    return trimmed;
  }

  try {
    const url = typeof window === "undefined"
      ? new URL(trimmed, "http://localhost")
      : new URL(trimmed, window.location.href);
    url.searchParams.set("_img_retry", Date.now().toString());
    return url.toString();
  } catch {
    const separator = trimmed.includes("?") ? "&" : "?";
    return `${trimmed}${separator}_img_retry=${Date.now()}`;
  }
}

export function Avatar({
  className,
  fallback,
  fallbackIcon,
  fallbackSrc,
  size = "md",
  src,
}: {
  className?: string;
  fallback: string;
  fallbackIcon?: React.ReactNode;
  fallbackSrc?: string;
  size?: AvatarSize;
  src?: string;
}) {
  const normalizedPrimarySrc = src?.trim() || "";
  const normalizedFallbackSrc = fallbackSrc?.trim() || "";
  const generatedFallbackSrc = React.useMemo(() => {
    if (normalizedFallbackSrc || fallbackIcon) {
      return "";
    }

    return buildDefaultAvatarSrc(fallback);
  }, [fallback, fallbackIcon, normalizedFallbackSrc]);
  const [imageFailed, setImageFailed] = React.useState(false);
  const [retriedPrimarySrc, setRetriedPrimarySrc] = React.useState<string | null>(null);
  const primarySrc = isRenderableImageSrc(normalizedPrimarySrc) ? normalizedPrimarySrc : "";
  const alternateSrc = isRenderableImageSrc(normalizedFallbackSrc) ? normalizedFallbackSrc : generatedFallbackSrc;
  const [currentSrc, setCurrentSrc] = React.useState(primarySrc || alternateSrc);

  React.useEffect(() => {
    setImageFailed(false);
    setRetriedPrimarySrc(null);
    setCurrentSrc(primarySrc || alternateSrc);
  }, [alternateSrc, primarySrc]);

  const canRenderImage = Boolean(currentSrc) && !imageFailed;

  return (
    <div
      className={cn(
        "grid shrink-0 place-items-center overflow-hidden rounded-full border border-border-soft bg-surface-skeleton font-semibold text-foreground",
        sizeClasses[size],
        className,
      )}
    >
      {canRenderImage ? (
        <img
          alt={fallback}
          className="h-full w-full object-cover"
          onError={() => {
            const currentPrimarySrc = retriedPrimarySrc ?? normalizedPrimarySrc;

            logger.warn("[avatar] image failed", {
              currentPrimarySrc,
              currentSrc,
              fallback,
              generatedFallbackSrcPresent: Boolean(generatedFallbackSrc),
              normalizedFallbackSrc,
              normalizedPrimarySrc,
              retriedPrimarySrc,
            });

            if (
              primarySrc
              && currentSrc === primarySrc
              && retriedPrimarySrc == null
              && isRetryableImageSrc(primarySrc)
            ) {
              const nextPrimarySrc = buildRetriedImageSrc(primarySrc);
              setRetriedPrimarySrc(nextPrimarySrc);
              setCurrentSrc(nextPrimarySrc);
              return;
            }

            if (currentPrimarySrc && currentSrc === currentPrimarySrc) {
              const nextFallbackSrc = alternateSrc;

              if (nextFallbackSrc && nextFallbackSrc !== currentSrc) {
                setCurrentSrc(nextFallbackSrc);
                return;
              }
            }
            setImageFailed(true);
          }}
          src={currentSrc}
        />
      ) : fallbackIcon ? (
        fallbackIcon
      ) : (
        <Skeleton aria-hidden className="h-full w-full rounded-full bg-[var(--color-surface-skeleton)]" />
      )}
    </div>
  );
}
