// packages/solid-ui/src/patterns/forms/option-card/option-card.tsx
import type { JSX } from "@solidjs/web";
import { createMemo, omit } from "solid-js";
import { Show } from "solid-js";

import { RadioIndicator } from "@/components/forms/radio-indicator/radio-indicator";
import { cn } from "@/lib/cn";
import { cva, type VariantProps } from "@/lib/recipe";

export const optionCardVariants = cva(
  "w-full cursor-pointer rounded-[var(--radius-lg)] border p-4 text-start transition-[border-color,background-color] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background",
  {
    variants: {
      variant: {
        default: "border-border-soft bg-background text-foreground hover:border-border",
        selected: "border-primary bg-primary-subtle text-foreground",
        disabled:
          "cursor-not-allowed border-border-soft bg-muted/30 opacity-60 text-muted-foreground",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  },
);

export interface OptionCardProps
  extends Omit<JSX.ButtonHTMLAttributes<HTMLButtonElement>, "class">,
    VariantProps<typeof optionCardVariants> {
  class?: string;
  title: string;
  description?: string;
  selected?: boolean;
  icon?: JSX.Element;
  disabledHint?: string;
}

/**
 * OptionCard - a single-choice card button with a RadioIndicator, title,
 * description, and optional leading icon. Used inside forms as a friendly
 * alternative to a bare RadioGroup; the host owns selection state. Do not
 * use it for multi-select (that is a CheckboxCard).
 */
export function OptionCard(props: OptionCardProps) {
  const className = createMemo(() => {
    const variant = props.disabled
      ? "disabled"
      : props.selected
        ? "selected"
        : (props.variant ?? "default");
    return cn(optionCardVariants({ variant }), props.class);
  });
  const rest = omit(
    props,
    "class",
    "variant",
    "title",
    "description",
    "selected",
    "icon",
    "disabledHint",
  );

  const indicator = <RadioIndicator checked={props.selected ?? false} />;

  return (
    <button {...rest} type={props.type ?? "button"} class={className()}>
      <div class="flex items-center gap-3">
        <Show when={props.icon} fallback={indicator}>
          <span class="flex size-12 shrink-0 items-center justify-center overflow-hidden rounded-full bg-card">
            {props.icon}
          </span>
        </Show>
        <div class="min-w-0 flex-1 space-y-1">
          <p
            class={cn(
              "text-base font-semibold leading-tight",
              props.disabled && "text-muted-foreground",
            )}
          >
            {props.title}
          </p>
          <Show when={props.description}>
            <p class="text-base leading-6 text-muted-foreground">
              {props.description}
            </p>
          </Show>
          <Show when={props.disabled && props.disabledHint}>
            <p class="text-base leading-6 text-warning">{props.disabledHint}</p>
          </Show>
        </div>
        <Show when={props.icon}>{indicator}</Show>
      </div>
    </button>
  );
}

// src/components/primitives/option-card.tsx
"use client";

import * as React from "react";
import { cva, type VariantProps } from "class-variance-authority";

import { RadioIndicator } from "@/components/primitives/radio-indicator";
import { cn } from "@/lib/utils";

const optionCardVariants = cva(
  "w-full cursor-pointer rounded-[var(--radius-lg)] border px-4 py-4 text-start transition-[border-color,background-color]",
  {
    variants: {
      variant: {
        default:
          "border-border-soft bg-background text-foreground hover:border-border",
        selected: "border-primary bg-primary/5 text-foreground",
        disabled:
          "cursor-not-allowed border-border-soft bg-muted/30 opacity-60 text-muted-foreground",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  },
);

export interface OptionCardProps
  extends
    React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof optionCardVariants> {
  title: string;
  description?: string;
  selected?: boolean;
  icon?: React.ReactNode;
  disabledHint?: string;
}

const OptionCard = React.forwardRef<HTMLButtonElement, OptionCardProps>(
  (
    {
      className,
      description,
      disabled,
      disabledHint,
      icon,
      selected = false,
      title,
      variant,
      type = "button",
      ...props
    },
    ref,
  ) => {
    const resolvedVariant = disabled
      ? "disabled"
      : selected
        ? "selected"
        : (variant ?? "default");
    const indicator = <RadioIndicator checked={selected} />;

    return (
      <button
        className={cn(
          optionCardVariants({ variant: resolvedVariant }),
          className,
        )}
        disabled={disabled}
        ref={ref}
        type={type}
        {...props}
      >
        <div className="flex items-center gap-3">
          {icon ? (
            <span className="flex size-12 shrink-0 items-center justify-center overflow-hidden rounded-full bg-white">
              {icon}
            </span>
          ) : (
            indicator
          )}
          <div className="min-w-0 flex-1 space-y-1">
            <p
              className={cn(
                "text-base font-semibold leading-tight",
                disabled && "text-muted-foreground",
              )}
            >
              {title}
            </p>
            {description ? (
              <p className="text-base leading-6 text-muted-foreground">
                {description}
              </p>
            ) : null}
            {disabled && disabledHint ? (
              <p className="text-base leading-6 text-warning">{disabledHint}</p>
            ) : null}
          </div>
          {icon ? indicator : null}
        </div>
      </button>
    );
  },
);
OptionCard.displayName = "OptionCard";

export { OptionCard, optionCardVariants };
