// packages/solid-ui/src/components/forms/radio-group/radio-group.tsx
import {
  RadioGroup as KRadioGroup,
  type RadioGroupDescriptionProps as KRadioGroupDescriptionProps,
  type RadioGroupErrorMessageProps as KRadioGroupErrorMessageProps,
  type RadioGroupItemProps as KRadioGroupItemProps,
  type RadioGroupLabelProps as KRadioGroupLabelProps,
  type RadioGroupRootProps,
} from "@kobalte/core/radio-group";
import { createMemo, omit, type ParentProps } from "solid-js";

import { cn } from "@/lib/cn";

export interface RadioGroupProps extends RadioGroupRootProps {
  class?: string;
  /** Accessible name for the group. */
  "aria-label"?: string;
}

/**
 * RadioGroup - a segmented set of mutually exclusive choices. Items are
 * RadioGroupItem children; arrow keys move the selection between items
 * through the shared native radio inputs. Use it for short lists of options
 * that all need to stay visible.
 */
export function RadioGroup(props: ParentProps<RadioGroupProps>) {
  const className = createMemo(() =>
    cn(
      "grid rounded-[calc(var(--radius-lg)+0.25rem)] bg-muted/40 p-1.5",
      props.class,
    ),
  );
  const rest = omit(props, "class", "children");

  return (
    <KRadioGroup {...rest} class={className()}>
      {props.children}
    </KRadioGroup>
  );
}

export interface RadioGroupItemProps
  extends Pick<KRadioGroupItemProps, "value" | "disabled"> {
  class?: string;
  /** Extra classes for the visible item surface. */
  labelClass?: string;
}

/**
 * RadioGroupItem - one choice inside a RadioGroup. Renders a hidden native
 * radio input and a styled label surface that reflects the selected state.
 */
export function RadioGroupItem(props: ParentProps<RadioGroupItemProps>) {
  const className = createMemo(() => cn("relative", props.class));
  const rest = omit(props, "class", "labelClass", "children");

  return (
    <KRadioGroup.Item {...rest} class={className()}>
      <KRadioGroup.ItemInput class="peer" />
      <KRadioGroup.ItemLabel
        class={cn(
          "flex min-h-12 cursor-pointer items-center justify-center rounded-[var(--radius-lg)] px-4 py-2.5 text-base font-medium text-muted-foreground transition-colors hover:text-foreground peer-focus-visible:ring-2 peer-focus-visible:ring-ring peer-focus-visible:ring-offset-2 peer-focus-visible:ring-offset-background data-checked:bg-card data-checked:text-foreground data-disabled:cursor-not-allowed data-disabled:opacity-50",
          props.labelClass,
        )}
      >
        {props.children}
      </KRadioGroup.ItemLabel>
    </KRadioGroup.Item>
  );
}

export function RadioGroupLabel(
  props: ParentProps<KRadioGroupLabelProps & { class?: string }>,
) {
  const className = createMemo(() =>
    cn("text-base font-medium text-foreground", props.class),
  );
  const rest = omit(props, "class", "children");

  return (
    <KRadioGroup.Label class={className()} {...rest}>
      {props.children}
    </KRadioGroup.Label>
  );
}

export function RadioGroupDescription(
  props: ParentProps<KRadioGroupDescriptionProps & { class?: string }>,
) {
  const className = createMemo(() =>
    cn("text-base text-muted-foreground", props.class),
  );
  const rest = omit(props, "class", "children");

  return (
    <KRadioGroup.Description class={className()} {...rest}>
      {props.children}
    </KRadioGroup.Description>
  );
}

export function RadioGroupErrorMessage(
  props: ParentProps<KRadioGroupErrorMessageProps & { class?: string }>,
) {
  const className = createMemo(() =>
    cn("text-base text-destructive-text", props.class),
  );
  const rest = omit(props, "class", "children");

  return (
    <KRadioGroup.ErrorMessage class={className()} {...rest}>
      {props.children}
    </KRadioGroup.ErrorMessage>
  );
}

// src/components/primitives/radio-group.tsx
"use client";

import * as React from "react";

import { cn } from "@/lib/utils";

type RadioGroupContextValue = {
  disabled: boolean;
  name: string;
  onValueChange: (value: string) => void;
  value: string | undefined;
};

const RadioGroupContext = React.createContext<RadioGroupContextValue | null>(null);

function useRadioGroupContext() {
  const context = React.use(RadioGroupContext);

  if (!context) {
    throw new Error("RadioGroupItem must be used within RadioGroup.");
  }

  return context;
}

interface RadioGroupProps extends React.ComponentProps<"div"> {
  defaultValue?: string;
  disabled?: boolean;
  name?: string;
  onValueChange?: (value: string) => void;
  value?: string;
}

function RadioGroup({ children, className, defaultValue, disabled = false, name, onValueChange, ref, value, ...props }: RadioGroupProps) {
  const generatedName = React.useId();
  const [uncontrolledValue, setUncontrolledValue] = React.useState(defaultValue);
  const isControlled = value !== undefined;
  const currentValue = isControlled ? value : uncontrolledValue;

  const handleValueChange = React.useCallback((nextValue: string) => {
    if (!isControlled) {
      setUncontrolledValue(nextValue);
    }
    onValueChange?.(nextValue);
  }, [isControlled, onValueChange]);

  const contextValue = React.useMemo<RadioGroupContextValue>(() => ({
    disabled,
    name: name ?? generatedName,
    onValueChange: handleValueChange,
    value: currentValue,
  }), [currentValue, disabled, generatedName, handleValueChange, name]);

  return (
    <RadioGroupContext.Provider value={contextValue}>
      <div
        ref={ref}
        className={cn(
          "grid rounded-[calc(var(--radius-lg)+0.25rem)] bg-muted/40 p-1.5",
          className,
        )}
        role="radiogroup"
        {...props}
      >
        {children}
      </div>
    </RadioGroupContext.Provider>
  );
}

interface RadioGroupItemProps extends Omit<React.ComponentProps<"input">, "checked" | "defaultChecked" | "onChange" | "type"> {
  indicatorClassName?: string;
  labelClassName?: string;
  value: string;
}

function RadioGroupItem({ children, className, disabled, indicatorClassName, labelClassName, ref, value, ...props }: RadioGroupItemProps) {
  const group = useRadioGroupContext();
  const checked = group.value === value;
  const itemDisabled = group.disabled || disabled;

  return (
    <label
      className={cn(
        "cursor-pointer",
        itemDisabled && "cursor-not-allowed opacity-50",
        labelClassName,
      )}
      data-disabled={itemDisabled ? "" : undefined}
      data-state={checked ? "checked" : "unchecked"}
    >
      <input
        {...props}
        ref={ref}
        checked={checked}
        className={cn("peer sr-only", className)}
        disabled={itemDisabled}
        name={group.name}
        onChange={() => group.onValueChange(value)}
        type="radio"
        value={value}
      />
      <span
        className={cn(
          "flex min-h-12 items-center justify-center rounded-[var(--radius-lg)] px-4 py-2.5 text-base font-medium transition-colors peer-focus-visible:ring-2 peer-focus-visible:ring-ring peer-focus-visible:ring-offset-2 peer-focus-visible:ring-offset-background",
          checked ? "bg-card text-foreground" : "text-muted-foreground hover:text-foreground",
          indicatorClassName,
        )}
      >
        {children}
      </span>
    </label>
  );
}

export { RadioGroup, RadioGroupItem };
