// packages/solid-ui/src/components/forms/select/select.tsx
import {
  Select as KSelect,
  type SelectRootItemComponentProps,
} from "@kobalte/core/select";
import type { JSX } from "@solidjs/web";
import { createMemo, type Component } from "solid-js";

import { IconArrowDown, IconCheck } from "@/components/media/icons";
import { cn } from "@/lib/cn";

export interface SelectProps<Option> {
  /** Available options. */
  options: Option[];
  /** Extract the submitted value of an option. */
  optionValue: (option: Option) => string;
  /** Extract the display label of an option. */
  optionLabel: (option: Option) => string;
  /** Extract the disabled flag of an option. */
  optionDisabled?: (option: Option) => boolean;
  /** Controlled selected value. */
  value?: string | null;
  /** Uncontrolled default selected value. */
  defaultValue?: string;
  /** Called when the selection changes. */
  onChange?: (value: string | null) => void;
  /** Rendered in the trigger when no value is selected. */
  placeholder?: JSX.Element;
  disabled?: boolean;
  class?: string;
  /** Extra classes for the trigger button. */
  triggerClass?: string;
  /** Extra classes for the popup content. */
  contentClass?: string;
  /** Preferred popper placement for the option list. */
  placement?: "top" | "top-start" | "top-end" | "bottom" | "bottom-start" | "bottom-end" | "left" | "left-start" | "left-end" | "right" | "right-start" | "right-end";
  /** Provider-neutral rendering for an option's visible label content. */
  renderOption?: (option: Option) => JSX.Element;
  /** Provider-neutral rendering for the selected trigger value. */
  renderValue?: (option: Option | null) => JSX.Element;
  /** Native form name for the hidden select control. */
  name?: string;
  /** Accessible name for the select trigger. */
  "aria-label"?: string;
}

function SelectItem(
  props: SelectRootItemComponentProps<unknown> & {
    renderOption?: (option: unknown) => JSX.Element;
  },
) {
  const item = props.item;

  return (
    <KSelect.Item
      item={item}
      class="relative flex w-full cursor-pointer select-none items-center rounded-lg px-8 py-2.5 text-base outline-none transition-colors text-popover-foreground data-highlighted:bg-muted data-highlighted:text-foreground data-selected:text-foreground data-disabled:pointer-events-none data-disabled:opacity-50"
    >
      <KSelect.ItemIndicator class="absolute start-2.5 flex size-5 items-center justify-center text-primary">
        <IconCheck class="size-4" />
      </KSelect.ItemIndicator>
      <KSelect.ItemLabel class="min-w-0 truncate">
        {props.renderOption ? props.renderOption(item.rawValue) : item.textValue}
      </KSelect.ItemLabel>
    </KSelect.Item>
  );
}

/**
 * Select - a popup menu of mutually exclusive options. Data-driven: feed it
 * options plus optionValue/optionLabel accessors and it renders the trigger,
 * popup listbox, and hidden form input. Use it for long option lists where a
 * RadioGroup would dominate the screen.
 */
export function Select<Option>(props: SelectProps<Option>) {
  const className = createMemo(() =>
    cn("flex w-full flex-col gap-1.5", props.class),
  );

  const findOption = (value: string) =>
    props.options.find((option) => props.optionValue(option) === value);

  const selectedOption = () =>
    props.value == null ? null : (findOption(props.value) ?? null);

  const defaultOption = () =>
    props.defaultValue == null ? undefined : findOption(props.defaultValue);

  const rootProps = () =>
    ({
      options: props.options,
      optionValue: props.optionValue,
      optionTextValue: props.optionLabel,
      optionDisabled: props.optionDisabled,
      value: selectedOption(),
      defaultValue: defaultOption(),
      onChange: (option: Option | Option[] | null) => {
        const first = Array.isArray(option) ? option[0] : option;
        props.onChange?.(
          first == null ? null : props.optionValue(first),
        );
      },
      placeholder: props.placeholder,
      disabled: props.disabled,
      name: props.name,
      placement: props.placement,
      multiple: false,
      itemComponent: ((itemProps: SelectRootItemComponentProps<Option>) => (
        <SelectItem
          {...itemProps}
          renderOption={props.renderOption as ((option: unknown) => JSX.Element) | undefined}
        />
      )) as Component<SelectRootItemComponentProps<Option>>,
    }) as const;

  return (
    <KSelect {...rootProps()} class={className()}>
      <KSelect.Trigger
        aria-label={props["aria-label"]}
        class={cn(
          "flex h-11 w-full cursor-pointer items-center justify-between rounded-full border border-input bg-background px-4 py-2 text-base shadow-sm transition-[color,box-shadow,border-color] data-disabled:cursor-not-allowed data-disabled:opacity-50 data-expanded:border-border data-expanded:ring-1 data-expanded:ring-border-soft data-[placeholder-shown]:text-muted-foreground",
          props.triggerClass,
        )}
      >
        <KSelect.Value<Option> class="truncate">
          {(state) =>
            props.renderValue
              ? props.renderValue(state.selectedOption())
              : state.selectedOption() != null
                ? props.optionLabel(state.selectedOption()!)
                : undefined
          }
        </KSelect.Value>
        <KSelect.Icon class="group ms-2 shrink-0 text-muted-foreground">
          <IconArrowDown class="size-4 transition-transform group-data-[expanded]:rotate-180" />
        </KSelect.Icon>
      </KSelect.Trigger>
      <KSelect.Portal>
        <KSelect.Content
          class={cn(
            "z-50 max-w-[var(--kb-popper-anchor-width)] min-w-32 overflow-hidden rounded-[var(--radius-lg)] border border-border bg-popover p-1 text-popover-foreground shadow-md",
            props.contentClass,
          )}
        >
          <KSelect.Listbox class="max-h-80 overflow-y-auto py-0 outline-none" />
        </KSelect.Content>
      </KSelect.Portal>
      <KSelect.HiddenSelect name={props.name} />
    </KSelect>
  );
}

// src/components/primitives/select.tsx
"use client";

import * as React from "react";
import * as SelectPrimitive from "@radix-ui/react-select";

import { cn } from "@/lib/utils";

const Select = SelectPrimitive.Root;
const SelectGroup = SelectPrimitive.Group;
const SelectValue = SelectPrimitive.Value;

function SelectTrigger({ children, className, ref, ...props }: React.ComponentProps<typeof SelectPrimitive.Trigger>) {
  return (
    <SelectPrimitive.Trigger
      className={cn(
        "flex h-11 w-full cursor-pointer items-center justify-between rounded-full border border-input bg-background px-4 py-2 text-base shadow-sm transition-[color,box-shadow,border-color] focus-visible:border-border focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-border-soft disabled:cursor-not-allowed disabled:opacity-50 data-[placeholder]:text-muted-foreground",
        className,
      )}
      ref={ref}
      {...props}
    >
      {children}
      <SelectPrimitive.Icon asChild>
        <span aria-hidden="true" className="ms-2 text-base text-muted-foreground">
          ▾
        </span>
      </SelectPrimitive.Icon>
    </SelectPrimitive.Trigger>
  );
}

function SelectScrollUpButton({ className, ref, ...props }: React.ComponentProps<typeof SelectPrimitive.ScrollUpButton>) {
  return (
    <SelectPrimitive.ScrollUpButton
      className={cn(
        "flex cursor-default items-center justify-center py-1 text-muted-foreground",
        className,
      )}
      ref={ref}
      {...props}
    >
      <span aria-hidden="true">▴</span>
    </SelectPrimitive.ScrollUpButton>
  );
}

function SelectScrollDownButton({ className, ref, ...props }: React.ComponentProps<typeof SelectPrimitive.ScrollDownButton>) {
  return (
    <SelectPrimitive.ScrollDownButton
      className={cn(
        "flex cursor-default items-center justify-center py-1 text-muted-foreground",
        className,
      )}
      ref={ref}
      {...props}
    >
      <span aria-hidden="true">▾</span>
    </SelectPrimitive.ScrollDownButton>
  );
}

function SelectContent({ children, className, position = "popper", ref, ...props }: React.ComponentProps<typeof SelectPrimitive.Content>) {
  return (
    <SelectPrimitive.Portal>
      <SelectPrimitive.Content
        className={cn(
          "relative z-50 max-h-96 min-w-32 overflow-hidden rounded-[var(--radius-lg)] border border-border bg-popover text-popover-foreground shadow-md data-[state=open]:animate-in data-[state=closed]:animate-out",
          position === "popper" &&
            "data-[side=bottom]:translate-y-1 data-[side=left]:-translate-x-1 data-[side=right]:translate-x-1 data-[side=top]:-translate-y-1",
          className,
        )}
        position={position}
        ref={ref}
        {...props}
      >
        <SelectScrollUpButton />
        <SelectPrimitive.Viewport
          className={cn(
            "p-0",
            position === "popper" &&
              "h-[var(--radix-select-trigger-height)] w-full min-w-[var(--radix-select-trigger-width)]",
          )}
        >
          {children}
        </SelectPrimitive.Viewport>
        <SelectScrollDownButton />
      </SelectPrimitive.Content>
    </SelectPrimitive.Portal>
  );
}

function SelectLabel({ className, ref, ...props }: React.ComponentProps<typeof SelectPrimitive.Label>) {
  return (
    <SelectPrimitive.Label
      className={cn(
        "px-2 py-1.5 text-base font-semibold text-foreground",
        className,
      )}
      ref={ref}
      {...props}
    />
  );
}

function SelectItem({ children, className, ref, ...props }: React.ComponentProps<typeof SelectPrimitive.Item>) {
  return (
    <SelectPrimitive.Item
      className={cn(
        "relative flex w-full cursor-pointer select-none items-center rounded-none py-2.5 pe-3 ps-8 text-base outline-none transition-colors text-popover-foreground hover:text-foreground data-[state=checked]:bg-muted data-[state=checked]:text-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50",
        className,
      )}
      ref={ref}
      {...props}
    >
      <span className="absolute start-2.5 flex size-5 items-center justify-center text-base">
        <SelectPrimitive.ItemIndicator>✓</SelectPrimitive.ItemIndicator>
      </span>
      <SelectPrimitive.ItemText>{children}</SelectPrimitive.ItemText>
    </SelectPrimitive.Item>
  );
}

function SelectSeparator({ className, ref, ...props }: React.ComponentProps<typeof SelectPrimitive.Separator>) {
  return (
    <SelectPrimitive.Separator
      className={cn("-mx-1 my-1 h-px bg-border", className)}
      ref={ref}
      {...props}
    />
  );
}

export {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectSeparator,
  SelectTrigger,
  SelectValue,
};
