// packages/solid-ui/src/components/disclosure/tabs/tabs.tsx
import {
  Tabs as KTabs,
  type TabsContentProps as KTabsContentProps,
  type TabsListProps as KTabsListProps,
  type TabsTriggerProps as KTabsTriggerProps,
} from "@kobalte/core/tabs";
import {
  createMemo,
  omit,
  type ParentProps,
} from "solid-js";

import { cn } from "@/lib/cn";

const Tabs = KTabs;

export interface TabsContentProps extends KTabsContentProps {
  class?: string;
}

function TabsList(props: ParentProps<KTabsListProps & { class?: string }>) {
  const className = createMemo(() =>
    cn(
      "inline-flex h-11 items-center justify-center gap-1 rounded-full bg-muted p-1 text-muted-foreground",
      props.class,
    ),
  );
  const rest = omit(props, "class", "children");

  return (
    <KTabs.List class={className()} {...rest}>
      {props.children}
    </KTabs.List>
  );
}

function TabsTrigger(props: ParentProps<KTabsTriggerProps & { class?: string }>) {
  const className = createMemo(() =>
    cn(
      "inline-flex cursor-pointer items-center justify-center whitespace-nowrap rounded-full px-4 py-2 text-base font-medium transition-all motion-reduce:transition-none focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 ring-offset-background disabled:pointer-events-none disabled:opacity-50 data-[selected]:bg-card data-[selected]:text-foreground data-[selected]:shadow-sm",
      props.class,
    ),
  );
  const rest = omit(props, "class", "children");

  return (
    <KTabs.Trigger class={className()} {...rest}>
      {props.children}
    </KTabs.Trigger>
  );
}

function TabsContent(props: ParentProps<TabsContentProps>) {
  const className = createMemo(() =>
    cn(
      "mt-4 ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2",
      props.class,
    ),
  );
  const rest = omit(props, "class", "children");

  return (
    <KTabs.Content class={className()} {...rest}>
      {props.children}
    </KTabs.Content>
  );
}

export { Tabs, TabsContent, TabsList, TabsTrigger };

// src/components/primitives/tabs.tsx
"use client";

import * as React from "react";
import * as TabsPrimitive from "@radix-ui/react-tabs";

import { cn } from "@/lib/utils";

const Tabs = TabsPrimitive.Root;

function TabsList({ className, ref, ...props }: React.ComponentProps<typeof TabsPrimitive.List>) {
  return (
    <TabsPrimitive.List
      className={cn(
        "inline-flex h-11 items-center justify-center rounded-full bg-muted p-1 text-muted-foreground",
        className,
      )}
      ref={ref}
      {...props}
    />
  );
}

function TabsTrigger({ className, ref, ...props }: React.ComponentProps<typeof TabsPrimitive.Trigger>) {
  return (
    <TabsPrimitive.Trigger
      className={cn(
        "inline-flex items-center justify-center whitespace-nowrap rounded-full px-4 py-2 text-base font-medium transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 ring-offset-background disabled:pointer-events-none disabled:opacity-50 data-[state=active]:bg-card data-[state=active]:text-foreground data-[state=active]:shadow-sm",
        className,
      )}
      ref={ref}
      {...props}
    />
  );
}

function TabsContent({ className, ref, ...props }: React.ComponentProps<typeof TabsPrimitive.Content>) {
  return (
    <TabsPrimitive.Content
      className={cn(
        "mt-4 ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2",
        className,
      )}
      ref={ref}
      {...props}
    />
  );
}

export { Tabs, TabsContent, TabsList, TabsTrigger };
