// packages/solid-ui/src/components/overlays/tooltip/tooltip.tsx
import { Tooltip as KTooltip } from "@kobalte/core/tooltip";
import { createMemo, omit, type ParentProps } from "solid-js";

import { cn } from "@/lib/cn";

const Tooltip = KTooltip;
const TooltipTrigger = KTooltip.Trigger;

function TooltipContent(
  props: ParentProps<Parameters<typeof KTooltip.Content>[0]>,
) {
  const className = createMemo(() =>
    cn(
      "z-50 overflow-hidden rounded-md border border-border-soft bg-card px-3 py-1.5 text-base text-card-foreground shadow-md",
      props.class,
    ),
  );
  const rest = omit(props, "class", "children");

  return (
    <KTooltip.Portal>
      <KTooltip.Content gutter={4} class={className()} {...rest}>
        {props.children}
      </KTooltip.Content>
    </KTooltip.Portal>
  );
}

export { Tooltip, TooltipContent, TooltipTrigger };

// src/components/primitives/tooltip.tsx
"use client";

import * as React from "react";
import * as TooltipPrimitive from "@radix-ui/react-tooltip";

import { cn } from "@/lib/utils";

const TooltipProvider = TooltipPrimitive.Provider;

const Tooltip = TooltipPrimitive.Root;

const TooltipTrigger = TooltipPrimitive.Trigger;

function TooltipContent({ className, ref, sideOffset = 4, ...props }: React.ComponentProps<typeof TooltipPrimitive.Content>) {
  return (
    <TooltipPrimitive.Portal>
      <TooltipPrimitive.Content
        ref={ref}
        sideOffset={sideOffset}
        className={cn(
          "z-50 overflow-hidden rounded-md border border-border-soft bg-card px-3 py-1.5 text-base text-card-foreground shadow-md animate-in fade-in-0 zoom-in-95 data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 origin-[--radix-tooltip-content-transform-origin]",
          className,
        )}
        {...props}
      />
    </TooltipPrimitive.Portal>
  );
}

export { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider };
