// solid/src/features/bookings/bookings-list/bookings-list.tsx
import { For, Show } from "solid-js";

import { Avatar, Card, CardContent, Type, cn } from "../../../design-system";
import { formatBookingDate, formatCentsAsUsdc, formatSlotTime } from "../booking-format";
import type { BookingState, IanaTz, IsoInstant } from "../view-models";
import { bookingStateGroup, bookingStateLabel } from "./bookings-list-model";

export interface BookingListItem {
  id: string;
  hostName: string;
  hostPhotoSrc?: string | null;
  startUtc: IsoInstant;
  endUtc: IsoInstant;
  state: BookingState;
  priceCents: number;
}

export interface BookingsListProps {
  items: BookingListItem[];
  viewerTimezone: IanaTz;
  onSelectBooking?: (item: BookingListItem) => void;
  class?: string;
}

export function BookingsList(props: BookingsListProps) {
  return (
    <Show when={props.items.length > 0} fallback={<Card class={props.class}><CardContent class="p-6 text-center"><Type variant="caption">No bookings yet.</Type></CardContent></Card>}>
      <div class={cn("flex flex-col gap-3", props.class)} data-bookings-count={props.items.length}>
        <For each={props.items}>
          {(item) => <button aria-label={`${item.hostName}, ${bookingStateLabel(item.state)}`} class="flex items-center gap-4 rounded-[var(--radius-lg)] border border-border-soft bg-card p-4 text-left transition-colors hover:bg-card/85 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" onClick={() => props.onSelectBooking?.(item)} type="button">
            <Avatar fallback={item.hostName} src={item.hostPhotoSrc ?? undefined} />
            <div class="flex min-w-0 flex-1 flex-col gap-1">
              <div class="flex items-center justify-between gap-2"><Type class="truncate" variant="body-strong">{item.hostName}</Type><Type class="shrink-0" variant="body-strong">{formatCentsAsUsdc(item.priceCents)}</Type></div>
              <div class="flex flex-wrap items-center justify-between gap-2"><Type variant="caption">{formatBookingDate(item.startUtc, props.viewerTimezone)}{" at "}{formatSlotTime(item.startUtc, props.viewerTimezone)}</Type><Type class={cn(bookingStateGroup(item.state) === "cancelled" && "text-warning")} variant="caption">{bookingStateLabel(item.state)}</Type></div>
            </div>
          </button>}
        </For>
      </div>
    </Show>
  );
}

// src/components/compositions/bookings/bookings-list/bookings-list.tsx

import { Avatar } from "@/components/primitives/avatar";
import { Card, CardContent } from "@/components/primitives/card";
import { Type } from "@/components/primitives/type";
import { formatCentsAsUsdc } from "@/lib/formatting/currency";
import { cn } from "@/lib/utils";
import type { BookingState, IanaTz, IsoInstant } from "../view-models";

import {
  formatBookingDate,
  formatSlotTime,
} from "../booking-format";

export interface BookingListItem {
  id: string;
  hostName: string;
  hostPhotoSrc: string;
  startUtc: IsoInstant;
  endUtc: IsoInstant;
  state: BookingState;
  priceCents: number;
}

export interface BookingsListProps {
  items: BookingListItem[];
  viewerTimezone: IanaTz;
  onSelectBooking?: (item: BookingListItem) => void;
  className?: string;
}

function stateLabel(state: BookingState): string {
  switch (state) {
    case "hold":
      return "Slot held";
    case "quoted":
      return "Quote ready";
    case "pending_payment":
      return "Payment verifying";
    case "confirmed":
      return "Confirmed";
    case "live":
      return "In progress";
    case "completed":
      return "Completed";
    case "settled":
      return "Settled";
    case "expired_hold":
      return "Hold expired";
    case "cancelled_before_payment":
      return "Cancelled";
    case "cancelled_by_host":
      return "Cancelled by host";
    case "cancelled_by_booker":
      return "Cancelled";
    case "no_show_host":
      return "Host no-show";
    case "no_show_booker":
      return "No-show";
    case "refunded":
      return "Refunded";
    case "disputed":
      return "Under review";
  }
}

export function BookingsList({ items, viewerTimezone, onSelectBooking, className }: BookingsListProps) {
  if (items.length === 0) {
    return (
      <Card>
        <CardContent className="p-6 text-center">
          <Type variant="caption">No bookings yet.</Type>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className={cn("flex flex-col gap-3", className)}>
      {items.map((item) => (
        <button
          key={item.id}
          className="flex items-center gap-4 rounded-[var(--radius-lg)] border border-border-soft bg-card p-4 text-left transition-colors hover:bg-card/85"
          onClick={() => onSelectBooking?.(item)}
          type="button"
        >
          <Avatar fallback={item.hostName} src={item.hostPhotoSrc} />
          <div className="flex flex-1 flex-col gap-1">
            <div className="flex items-center justify-between gap-2">
              <Type variant="body-strong">{item.hostName}</Type>
              <Type variant="body-strong">{formatCentsAsUsdc(item.priceCents)}</Type>
            </div>
            <div className="flex items-center justify-between gap-2">
              <Type variant="caption">
                {formatBookingDate(item.startUtc, viewerTimezone)} at{" "}
                {formatSlotTime(item.startUtc, viewerTimezone)}
              </Type>
              <Type variant="caption">{stateLabel(item.state)}</Type>
            </div>
          </div>
        </button>
      ))}
    </div>
  );
}
